const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(require('path').join(__dirname,'../dist/game.js'),'utf8');const storage=new Map();
function boot(cloud){const els=new Map();let draws=0,clock=1000,seed=52;const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,uniform3fv:(u,v)=>assert.ok(v.every(Number.isFinite),'finite vector'),uniformMatrix4fv:(u,t,v)=>assert.ok([...v].every(Number.isFinite)),drawArrays:()=>draws++},{get:(o,k)=>o[k]||(()=>({}))});function el(id){if(!els.has(id)){const classes=new Set();els.set(id,{value:'65',textContent:'',style:{},classList:{add:v=>classes.add(v),remove:v=>classes.delete(v),toggle(){},contains:v=>classes.has(v)},checked:false,disabled:false,addEventListener(){},getContext:()=>gl,requestPointerLock(){},setPointerCapture(){},firstElementChild:{style:{}},children:[],replaceChildren(){this.children=[]},appendChild(v){this.children.push(v)}});}return els.get(id);}const math=Object.create(Math);math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);const ctx={console,Math:math,Date,Float32Array,Set,Map,performance:{now:()=>clock},crypto:{randomUUID:()=> 'test-run-'+seed},localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},fetch:()=>{throw Error('unexpected fetch')},devicePixelRatio:1,innerWidth:1440,innerHeight:900,requestAnimationFrame(){},window:{IronCloud:cloud,addEventListener(){}},document:{getElementById:el,querySelectorAll:()=>[],createElement:()=>({...el('new'+seed+Math.random())}),addEventListener(){},exitPointerLock(){}}};ctx.globalThis=ctx;
const exposed=source.replace(/\}\)\(\);\s*$/,`globalThis.t={start,update,render,spawn,spawnBoss,spawnQuad,waveRoster,waveStart,advanceSector,updateSpawnQueue,randomizeArena,damagePlayer,applyDamage,fireEnemy,partBox,trace,rayBox,shieldFaces,updateBoss,executeBossPattern,updateBossAttacks,activeParts,cancelBrokenPattern,sweepRadius,updateDroneShield,beamData,kill,finish,checkpointRank,syncCloudRank,readRecords,writeRecords,mergeRecords,importRecords,recordDocument,namedResult,showLeaderboard,alertAttack,robotSound,playerExplosion,switchWeapon,shoot,throwGrenade,collectHealth,keys,enemies,world,obstacles,gates,spawnQueue,vents,bolts,lasers,sweeps,scheduled,pickups,playerOrdnance,types,get:()=>({state,rankResult,rankRemote,rankCloudResult,rankCheckpoints,hp,score,wave,pos,ammo,rpgAmmo,grenades,threatTimer,combatTime,invulnerableUntil,stageStats}),set:v=>{if(v.pos)pos=v.pos;if(v.mode)mode=v.mode;if(v.wave!==undefined)wave=v.wave;if(v.score!==undefined)score=v.score;if(v.hp!==undefined)hp=v.hp;if(v.combatTime!==undefined)combatTime=v.combatTime;if(v.state)state=v.state;if(v.stageStats)stageStats=v.stageStats;if(v.dt!==undefined)lastDt=v.dt;if(v.difficulty!==undefined)difficulty=v.difficulty;if(v.yaw!==undefined)yaw=v.yaw;cooldown=0;},clear:()=>{enemies.length=spawnQueue.length=bolts.length=lasers.length=sweeps.length=scheduled.length=playerOrdnance.length=0;}};})();`);vm.runInNewContext(exposed,ctx);el('playername');return {t:ctx.t,els,clock:v=>clock=v,draws:()=>draws};}
(async()=>{
 const x=boot(),t=x.t;t.render(0);await t.start();assert.equal(t.spawnQueue.length,5);assert.equal(t.enemies.length,0);const cover=t.world.filter(b=>b.randomCover).map(b=>b.p.join(','));t.randomizeArena();assert.notDeepEqual(t.world.filter(b=>b.randomCover).map(b=>b.p.join(',')),cover);assert.equal(t.vents.length,42);t.updateSpawnQueue(8);assert.ok(t.enemies.every(e=>e.dropping&&e.p[1]===12));t.update(.5);assert.ok(t.enemies.every(e=>!e.dropping));
 t.set({hp:100,combatTime:1});t.damagePlayer(10);t.damagePlayer(10);assert.equal(t.get().hp,90);assert.equal(x.els.get('damage').style.opacity,'1');t.set({combatTime:1.0011});t.damagePlayer(10);assert.equal(t.get().hp,80);
 t.clear();t.set({wave:1,pos:[0,1.7,-32]});t.gates[0].open=true;t.waveStart();assert.equal(t.gates[0].open,false);assert.ok(t.gates[0].sealed);assert.ok(t.get().pos[2]<-31);
 t.clear();t.set({pos:[0,1.7,5],wave:1,difficulty:1});const heavy=t.spawn(2,0,0),shield=heavy.parts.find(p=>p.shield),originalHP=heavy.hp;t.applyDamage(shield,120);assert.equal(heavy.hp,originalHP);assert.equal(shield.hp,shield.max-120);assert.ok(t.shieldFaces(heavy,shield,[0,0,-1]));assert.ok(!t.shieldFaces(heavy,shield,[0,0,1]));const hit=t.trace([0,1.7,5],[0,0,-1]);assert.equal(hit.obj,shield);const rear=t.trace([0,1.7,-5],[0,0,1]);assert.ok(rear.obj&&!rear.obj.shield);t.applyDamage(shield,10000);assert.ok(shield.destroyed);assert.equal(heavy.hp,originalHP);
 for(const type of [3,4,5]){t.clear();const e=t.spawn(type,0,0);assert.equal(t.activeParts(e,'다리').length,4);if(type===5){assert.equal(t.activeParts(e,'팔').length,2);assert.ok(e.type.speed>t.types[0].speed*2);t.set({pos:[0,1.7,1],combatTime:2});t.fireEnemy(e,2);assert.ok(e.attackAnim>0);}else{t.set({pos:[0,1.7,10]});t.fireEnemy(e,0);assert.equal(type===3?t.lasers.length:t.bolts.length,1);if(type===3){const beam=t.beamData(t.lasers[0]);assert.ok(beam.dir[1]>0);}}t.render(1000);}
 t.clear();t.set({mode:'ranked',wave:5,pos:[0,1.7,12]});let boss=t.spawnBoss(0,0,false);t.executeBossPattern(boss,0);assert.ok(boss.charge>0);assert.equal(t.sweeps.length,0);const start=boss.p[2];t.updateBoss(boss,.1);assert.ok(boss.p[2]>start+1);for(let i=0;i<20;i++)t.updateBoss(boss,.1);assert.ok(t.sweeps.length>0);assert.equal(x.els.get('bossname').textContent,'WARDEN');t.render(2000);
 t.clear();t.set({wave:10});boss=t.spawnBoss(0,0,true);assert.equal(boss.parts.filter(p=>p.name!=='장갑').length,13);const core=t.activeParts(boss,'가슴 코어')[0];core.hp=core.max*.25;const drone=boss.parts.find(p=>p.drone);const old=[...drone.local];t.updateDroneShield(boss,.1);assert.equal(boss.protectedPart,'가슴 코어');assert.notDeepEqual([...drone.local],old);assert.equal(t.sweepRadius(boss),12);t.executeBossPattern(boss,5);assert.equal(boss.aerial,10);const health=boss.hp;t.applyDamage(core,100);assert.equal(boss.hp,health);t.updateBoss(boss,.55);assert.equal(t.bolts.length,6);assert.ok(boss.p[1]>0);for(let i=0;i<95;i++)t.updateBoss(boss,.1);assert.equal(boss.aerial,0);assert.ok(t.bolts.length>=90);t.bolts.length=0;t.executeBossPattern(boss,1);t.updateBossAttacks(2);assert.equal(t.bolts.length,12);t.bolts.length=0;t.executeBossPattern(boss,3);t.updateBossAttacks(2);assert.equal(t.bolts.length,6);t.bolts.length=0;t.executeBossPattern(boss,4);assert.equal(t.bolts.length,14);t.render(4000);
 t.clear();t.set({mode:'ranked'});await t.start();assert.equal(t.get().state,'play');assert.equal(t.get().rankRemote,null);t.alertAttack({p:[0,0,0]});assert.equal(t.get().threatTimer,0);t.set({score:2300,combatTime:5,hp:10});x.clock(9000);t.damagePlayer(100);assert.equal(t.get().state,'end');assert.equal(t.get().rankResult.outcome,'dead');assert.equal(t.get().rankResult.score,2300);x.els.get('playername').value='테스트';await x.els.get('rankform').onsubmit({preventDefault(){}});assert.equal(t.readRecords()[0].score,2300);assert.equal(boot().t.readRecords()[0].outcome,'dead');assert.ok(x.draws()>1000);
 const calls=[];const online=boot({start:async()=>({id:'remote-1'}),checkpoint:async(id,e)=>{calls.push(e);return {id,score:700,elapsedMs:4000,stage:e.stage,outcome:'dead',createdAt:1}},submit:async(id,name)=>({id,name,score:700}),board:async()=>({rows:[]})});online.t.set({mode:'ranked'});await online.t.start();online.t.set({hp:1,score:700,stageStats:{kills:[1,0,0,0,0,0],parts:0,bossParts:0,boss:false}});online.t.damagePlayer(100);online.els.get('playername').value='온라인';await online.els.get('rankform').onsubmit({preventDefault(){}});assert.equal(calls.length,1);assert.equal(calls[0].outcome,'dead');assert.ok(online.els.get('submitstatus').textContent.includes('온라인 등록 완료'));
 console.log('PASS: ceiling drops, random cover, sealed retreat, 1ms hit immunity/red flash, independent frontal shield/rear hits, 3 quadruped archetypes, charge-sweep, 13 final boss parts, drone protection, 10s invulnerable barrage, boosted missile/burst/blade counts, no ranked warning, offline death persistence, authenticated death sync, finite rendering.');
})().catch(e=>{console.error(e);process.exitCode=1});
