const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const root=require('path').join(__dirname,'../firebase/functions/'),V=require(root+'validation.js');const docs=new Map();let now=100000;const clock={now:()=>now};class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const ref=path=>({path,collection:n=>collection(path+'/'+n)});function collection(path){return {doc:id=>ref(path+'/'+id),orderBy(){return this},limit(){return this},async get(){return {docs:[...docs.entries()].filter(([k])=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')).map(([,v])=>({data:()=>v})).sort((a,b)=>b.data().score-a.data().score||a.data().elapsedMs-b.data().elapsedMs).slice(0,100)}}};}
const db={collection,async runTransaction(fn){const changes=[];const tx={get:async r=>({exists:docs.has(r.path),data:()=>structuredClone(docs.get(r.path))}),set:(r,v)=>changes.push([r.path,v]),create:(r,v)=>{if(docs.has(r.path))throw Error('duplicate');changes.push([r.path,v]);},update:(r,v)=>changes.push([r.path,{...docs.get(r.path),...v}])};const result=await fn(tx);for(const [p,v] of changes)docs.set(p,structuredClone(v));return result;}};
const handlers={};const context={exports:handlers,Date:clock,require:name=>name==='firebase-functions/v2/https'?{onCall:(options,run)=>({options,run}),HttpsError}:name==='firebase-admin/app'?{initializeApp(){}}:name==='firebase-admin/firestore'?{getFirestore:()=>db,Timestamp:{fromMillis:v=>v}}:name==='node:crypto'?crypto:V};vm.runInNewContext(fs.readFileSync(root+'index.js','utf8'),context);
function request(fn,uid,data){return handlers[fn].run({auth:uid?{uid}:null,data});}async function rejects(fn,code){await assert.rejects(fn,e=>e.code===code);}
(async()=>{for(const fn of Object.values(handlers)){assert.equal(fn.options.enforceAppCheck,true);assert.equal(fn.options.maxInstances,2);assert.ok(fn.options.cors.includes('https://minjaninja94.github.io'));}await rejects(()=>request('startRankedRun',null,{version:5,nonce:'a'}),'unauthenticated');const a=await request('startRankedRun','alice',{version:5,nonce:'a'});assert.equal((await request('startRankedRun','alice',{version:5,nonce:'a'})).id,a.id);await rejects(()=>request('startRankedRun','alice',{version:5,nonce:'b'}),'resource-exhausted');await rejects(()=>request('submitRankedResult','bob',{id:a.id,name:'도용'}),'permission-denied');await rejects(()=>request('submitRankedResult','alice',{id:a.id,name:'조기'}),'failed-precondition');await rejects(()=>request('checkpointRankedRun','alice',{id:a.id,stage:2,kills:[0,0,0,0,0,0],parts:0,bossParts:0,boss:false,outcome:'dead'}),'failed-precondition');await rejects(()=>request('checkpointRankedRun','alice',{id:a.id,stage:1,kills:[999,0,0,0,0,0],parts:0,bossParts:0,boss:false,outcome:'dead'}),'invalid-argument');
 let expected=0;for(let stage=1;stage<=10;stage++){now+=10000;const entry={id:a.id,stage,kills:V.roster(stage),parts:0,bossParts:0,boss:stage%5===0,outcome:'clear'};expected+=V.stageScore(entry);const r=await request('checkpointRankedRun','alice',entry);assert.equal(r.score,expected);const duplicate=await request('checkpointRankedRun','alice',entry);assert.equal(duplicate.score,expected);}const clear=await request('submitRankedResult','alice',{id:a.id,name:'우승자'});assert.equal(clear.score,expected);assert.equal(clear.outcome,'clear');const again=await request('submitRankedResult','alice',{id:a.id,name:'변경불가'});assert.equal(again.name,'우승자');assert.ok(!('uid' in clear));assert.ok(!('startedAt' in clear));
 now+=20000;const b=await request('startRankedRun','alice',{version:5,nonce:'dead-run'});now+=4500;const death={id:b.id,stage:1,kills:[1,0,0,0,0,0],parts:1,bossParts:0,boss:false,outcome:'dead'};const result=await request('checkpointRankedRun','alice',death);assert.equal(result.score,800);assert.equal(result.elapsedMs,4500);assert.equal(result.outcome,'dead');await rejects(()=>request('checkpointRankedRun','alice',{...death,parts:2}),'already-exists');const row=await request('submitRankedResult','alice',{id:b.id,name:'전사자'});assert.equal(row.score,800);const board=await request('getRankedBoard','bob',{});assert.equal(board.rows.length,2);assert.ok(board.rows.every(r=>Object.keys(r).sort().join(',')==='createdAt,elapsedMs,id,name,outcome,score,stage'));assert.equal(board.rows[0].name,'우승자');assert.throws(()=>V.playerName('a\nscript'));assert.ok(fs.readFileSync(root+'../firestore.rules','utf8').includes('allow read, write: if false;'));
 now+=20000;const corridor=await request('startRankedRun','alice',{version:5,nonce:'corridor'});await request('checkpointRankedRun','alice',{id:corridor.id,stage:1,kills:V.roster(1),parts:0,bossParts:0,boss:false,outcome:'clear'});const stopped=await request('finishRankedRun','alice',{id:corridor.id});assert.equal(stopped.outcome,'dead');assert.equal(stopped.stage,1);assert.equal(stopped.score,V.stageScore({stage:1,kills:V.roster(1),parts:0,bossParts:0,boss:false,outcome:'clear'}));
 console.log('PASS: mandatory App Check config, authentication, run ownership, rate limit, exact stage order, server-computed score, 10-stage clear, partial death result, replay idempotency, immutable names, public field projection, deny-all DB rules.');})().catch(e=>{console.error(e);process.exitCode=1});
