'use strict';
(()=>{
const $=id=>document.getElementById(id), canvas=$('game');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){$('error').classList.remove('hidden');return;}
const vs=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uVP;uniform vec3 uPos;uniform vec3 uSize;uniform float uAngle;varying vec3 vNormal;varying vec3 vWorld;void main(){float c=cos(uAngle),s=sin(uAngle);mat3 r=mat3(c,0.,-s,0.,1.,0.,s,0.,c);vWorld=r*(aPos*uSize)+uPos;vNormal=r*aNormal;gl_Position=uVP*vec4(vWorld,1.);}`;
const fs=`precision mediump float;uniform vec3 uColor;uniform vec3 uEye;uniform float uGlow;uniform float uFog;varying vec3 vNormal;varying vec3 vWorld;void main(){float light=.35+max(dot(normalize(vNormal),normalize(vec3(-.5,.9,.3))),0.)*.75;vec3 col=uColor*(light+uGlow);float fog=1.-exp(-distance(vWorld,uEye)*uFog);gl_FragColor=vec4(mix(col,vec3(.045,.085,.09),fog),1.);}`;
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Renderer link');gl.useProgram(program);
const U={};for(const n of ['VP','Pos','Size','Angle','Color','Eye','Glow','Fog'])U[n]=gl.getUniformLocation(program,'u'+n);
const verts=[];const faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]],[[0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]]];for(const f of faces)for(const i of [1,2,3,1,3,4])verts.push(...f[i],...f[0]);for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const x=Math.cos(a)*.5,y=Math.sin(a)*.5,X=Math.cos(b)*.5,Y=Math.sin(b)*.5;for(const v of [[x,y,-.5],[X,Y,-.5],[X,Y,.5],[x,y,-.5],[X,Y,.5],[x,y,.5]])verts.push(...v,Math.cos((a+b)/2),Math.sin((a+b)/2),0);for(const z of [-.5,.5])for(const v of [[0,0,z],[x,y,z],[X,Y,z]])verts.push(...v,0,0,Math.sign(z));}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);for(const [n,offset]of [['aPos',0],['aNormal',12]]){let a=gl.getAttribLocation(program,n);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);
const C={floor:[.17,.22,.21],wall:[.19,.25,.25],dark:[.065,.105,.105],metal:[.28,.34,.32],lime:[.65,.95,.37],amber:[1,.45,.13],red:[.9,.18,.10],blue:[.24,.7,.8]};
const world=[], obstacles=[], gates=[], pickups=[], debris=[], bolts=[], particles=[], enemies=[];let gun=[];
const box=(p,s,c,a=0,g=0)=>({p:[...p],s:[...s],c,a,g});
function add(p,s,c,a=0,g=0,solid=false){const b=box(p,s,c,a,g);b.blocksShots=solid||s[1]>.25;world.push(b);if(solid)obstacles.push(b);return b;}
function draw(b){if(b.open)return;gl.uniform3fv(U.Pos,b.p);gl.uniform3fv(U.Size,b.s);gl.uniform3fv(U.Color,b.c);gl.uniform1f(U.Angle,b.a||0);gl.uniform1f(U.Glow,b.g||0);gl.drawArrays(gl.TRIANGLES,b.kind==='cylinder'?36:0,b.kind==='cylinder'?144:36);}
function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function view(eye,yaw,pitch){let sy=Math.sin(yaw),cy=Math.cos(yaw),sp=Math.sin(pitch),cp=Math.cos(pitch);let right=[cy,0,-sy],up=[sy*sp,cp,cy*sp],back=[sy*cp,-sp,cy*cp];return new Float32Array([right[0],up[0],back[0],0,right[1],up[1],back[1],0,right[2],up[2],back[2],0,-dot(right,eye),-dot(up,eye),-dot(back,eye),1]);}
function projection(fov){let f=1/Math.tan(fov/2),n=.025,far=160;return new Float32Array([f/(canvas.width/canvas.height),0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function norm(v){let l=Math.hypot(...v)||1;return v.map(x=>x/l);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
// Five connected foundry halls. Each cleared gate opens toward the next hall.
function container(x,z,w,d,h,c){add([x,h/2,z],[w,h,d],c,0,0,true);for(let k=-w/2+.25;k<w/2;k+=.55)add([x+k,h/2,z+d/2+.025],[.09,h-.12,.08],c.map(v=>v*1.15));add([x,h+.05,z],[w+.12,.1,d+.1],C.metal);}
for(let sector=0;sector<5;sector++){
 const z=-sector*60;
 add([0,-.25,z],[44,.5,60],C.floor);
 for(const x of [-22,22])add([x,4,z],[1,8,60],C.wall,0,0,true);
 for(let k=-28;k<=28;k+=4){add([0,.009,z+k],[43,.012,.023],[.25,.32,.29]);add([k*.7,.006,z],[.023,.012,60],[.25,.32,.29]);}
 for(const x of [-18,18])for(const dz of [-22,-5,15]){add([x,4,z+dz],[.75,8,.75],C.dark,0,0,true);add([x,5,z+dz+.4],[.12,2,.08],C.lime,0,.8);}
 container(-12,z-9,5,3,3,[.16,.30,.31]);container(12,z-18,5,3,3.4,[.35,.26,.19]);container(-15,z+15,4,5,2.8,[.27,.32,.27]);
 for(const [x,dz]of [[-6,4],[7,-5],[10,17]]){add([x,.7,z+dz],[2.6,1.4,1.8],C.metal,0,0,true);add([x,1.43,z+dz],[2.7,.08,1.9],C.dark);}
 for(const x of [-13,13])add([x,4,z-30],[18,8,.8],C.wall,0,0,true);
 if(sector<4){let gate=add([0,3,z-30],[8,6,.6],[.25,.32,.30],0,0,true);gate.sector=sector;gates.push(gate);}
 else add([0,4,z-30],[8,8,.8],C.wall,0,0,true);
 for(const x of [-4.2,4.2])add([x,3,z-29.5],[.16,6,.1],C.amber,0,1);
 for(let dz=20;dz>-28;dz-=6){add([-.48,.015,z+dz],[.12,.025,1.1],C.lime,-.55,.3);add([.48,.015,z+dz],[.12,.025,1.1],C.lime,.55,.3);}
}
add([0,4,30],[44,8,1],C.wall,0,0,true);
// HK416-inspired placeholder: receiver, stock, rail, handguard, barrel, magazine and sights.
function gb(p,s,c=C.dark,a=0){gun.push(box(p,s,c,a));}
gb([.24,-.24,-.42],[.115,.13,.36],[.13,.15,.145]);gb([.24,-.28,-.24],[.14,.14,.15],[.11,.125,.12]);gb([.24,-.18,-.59],[.125,.12,.30],[.20,.23,.20]);gb([.24,-.174,-.86],[.033,.035,.27],[.09,.1,.09]);gb([.24,-.174,-1.015],[.052,.054,.075],C.dark);gb([.24,-.36,-.45],[.085,.23,.115],[.15,.16,.145],-.06);gb([.24,-.37,-.23],[.067,.16,.085],C.dark);gb([.24,-.27,-.08],[.09,.065,.23],C.dark);gb([.24,-.285,.01],[.135,.17,.17],[.12,.14,.12]);gb([.24,-.13,-.44],[.052,.024,.52],[.13,.15,.13]);for(let i=0;i<20;i++)gb([.24,-.11,-.20-i*.026],[.084,.018,.011],[.20,.23,.20]);for(let i=0;i<7;i++){gb([.307,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);gb([.174,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);}for(const z of [-.33,-.71]){gb([.24,-.087,z],[.03,.065,.027],C.dark);gb([.216,-.056,z],[.015,.045,.025],C.dark);gb([.264,-.056,z],[.015,.045,.025],C.dark);}gb([.24,-.29,-.65],[.06,.12,.065],C.dark);gb([.295,-.237,-.35],[.012,.026,.073],[.38,.41,.36]);
// Gloved hands.
gb([.235,-.41,-.23],[.11,.13,.13],[.24,.28,.22]);gb([.08,-.44,-.05],[.18,.17,.38],[.17,.22,.17],-.22);gb([.21,-.35,-.63],[.14,.12,.13],[.24,.28,.22]);gb([.0,-.49,-.45],[.14,.14,.34],[.17,.22,.17],-.5);
const types=[{name:'정찰형',hp:70,scale:.78,speed:3.8,c:[.05,.80,.95],accent:[1,.76,.10],arm:24,leg:25,head:32,damage:8,rate:2.3},{name:'전투형',hp:150,scale:1.1,speed:2.2,c:[1,.38,.055],accent:[.12,.75,.98],arm:44,leg:44,head:56,damage:12,rate:1.65},{name:'중장갑형',hp:400,scale:1.7,speed:1.35,c:[.67,.20,.95],accent:[1,.78,.10],arm:90,leg:95,head:110,damage:18,rate:1.3}];
let state='menu',difficulty=1,wave=0,hp=100,ammo=30,reload=0,kills=0,broken=0,shots=0,hits=0,elapsed=0,yaw=0,pitch=0,pos=[0,1.7,19],jumpV=0,fire=false,aim=false,cooldown=0,recoil=0,hitTimer=0,damageTimer=0,noticeTimer=0,intermission=0,feedTimer=0,feet=0,sensitivity=1,lockedFallback=false,sectorCleared=false,threatTimer=0;let threatSource=null;
const keys=new Set(),touch='ontouchstart'in window;let joystick=[0,0],lookPointer=null,lastLook=[0,0],audioCtx;
function sound(f,d=.08,volume=.05,noise=false,source=null){if(!$('sound').checked)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const g=audioCtx.createGain();const distance=source?Math.hypot(source[0]-pos[0],source[2]-pos[2]):0;g.gain.setValueAtTime(volume*(source?clamp(14/(distance+7),.2,1):1),audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);if(source&&audioCtx.createStereoPanner){const pan=audioCtx.createStereoPanner();const dx=source[0]-pos[0],dz=source[2]-pos[2];pan.pan.value=clamp((Math.cos(yaw)*dx-Math.sin(yaw)*dz)/(distance||1),-1,1);g.connect(pan);pan.connect(audioCtx.destination);}else g.connect(audioCtx.destination);let o;if(noise){let b=audioCtx.createBuffer(1,audioCtx.sampleRate*d,audioCtx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1);o=audioCtx.createBufferSource();o.buffer=b;let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=f;o.connect(filter);filter.connect(g);}else{o=audioCtx.createOscillator();o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.5,audioCtx.currentTime+d);o.connect(g);}o.start();o.stop(audioCtx.currentTime+d);}catch{}}
function part(e,name,p,s,h,c){const b=box(p,s,c||e.type.c);b.name=name;b.hp=h;b.max=h;b.e=e;b.local=p;e.parts.push(b);}
function spawn(type,x,z){const t=types[type],m=[.72,1,1.45][difficulty]*(1+(wave-1)*.12),e={type:t,p:[x,0,z],parts:[],hp:t.hp*m,max:t.hp*m,scale:t.scale,timer:1.5+Math.random()*2,phase:Math.random()*6,dead:false,stagger:0,angle:0,age:0,warning:0};part(e,'코어',[0,1.27,0],[.68,.7,.43],999);part(e,'머리',[0,2.02,0],[.36,.68,.38],t.head*m);part(e,'왼팔',[-.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'오른팔',[.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'왼다리',[-.21,.44,0],[.27,.83,.31],t.leg*m);part(e,'오른다리',[.21,.44,0],[.27,.83,.31],t.leg*m);enemies.push(e);}
function partBox(e,p){const legs=e.parts.filter(p=>p.hp>0&&p.name.includes('다리')).length;let y=legs===0?-.60:legs===1?-.13:0;let step=p.name.includes('다리')&&legs>0?Math.sin(feet*2+e.phase+(p.name==='왼다리'?0:Math.PI))*.09:0;const c=Math.cos(e.angle),s=Math.sin(e.angle);return {...p,a:e.angle,p:[e.p[0]+(c*p.local[0]+s*p.local[2])*e.scale,e.p[1]+(p.local[1]+y+step)*e.scale,e.p[2]+(-s*p.local[0]+c*p.local[2])*e.scale],s:p.s.map(x=>x*e.scale)};}
function announce(s,time=2.8){$('notice').textContent=s;noticeTimer=time;}
function log(s){$('feed').textContent=s;feedTimer=2.5;}
function waveStart(){wave++;sectorCleared=false;const count=3+wave*2,z=-(wave-1)*60;for(let i=0;i<count;i++){const x=-8+(i%5)*4,depth=z-14-Math.floor(i/5)*4;const type=wave===1?(i%3===0?1:0):wave>=4?(i%3===0?2:1):i%3;spawn(type,x,depth);}announce('구역 '+wave+' · 전방 적 접근',3.5);sound(420,.22,.04);updateHud();}
function dropChance(health,d=difficulty){return [.99,.50,.30][d]*clamp((100-health)/99,0,1);}
function dropHealth(e){if(Math.random()<dropChance(hp))pickups.push({p:[e.p[0],.45,e.p[2]],heal:[50,30,20][difficulty]});}
function collectHealth(){for(let i=pickups.length-1;i>=0;i--){const item=pickups[i],dist=Math.hypot(pos[0]-item.p[0],pos[2]-item.p[2]);if(hp<100&&dist<1.25){const direction=norm(item.p.map((v,j)=>v-pos[j]));if(trace(pos,direction,false,Math.hypot(...item.p.map((v,j)=>v-pos[j]))-.1).obj)continue;const amount=Math.min(item.heal,100-hp);hp+=amount;pickups.splice(i,1);sound(720,.25,.07);log('회복 키트 +'+Math.round(amount)+' HP');updateHud();}}}
function alertAttack(e){threatSource=[...e.p];threatTimer=1.1;sound(190+e.scale*80,.20,.13,false,e.p);}
function fireEnemy(e,arms){const origin=[e.p[0],e.scale*1.37,e.p[2]],delta=pos.map((p,i)=>p-origin[i]),dist=Math.hypot(...delta);if(trace(origin,norm(delta),false,dist).obj)return;alertAttack(e);if(arms&&dist<25){const direction=norm(delta);bolts.push({p:origin,v:direction.map(v=>v*([11,15,19][difficulty])),s:[.15,.15,.15],c:C.red,g:2,life:4,source:[...e.p],damage:e.type.damage*([.65,1,1.3][difficulty])*(arms===1?.65:1)});sound(650,.16,.18,true,e.p);}else if(dist<2){sound(110,.2,.18,true,e.p);damagePlayer(arms?e.type.damage:4,e.p);}}
function advanceSector(){if(enemies.some(e=>!e.dead))return;if(!sectorCleared){sectorCleared=true;bolts.length=0;ammo=30;reload=0;if(wave===5){announce('모든 구역 확보',2);intermission=2;}else{gates[wave-1].open=true;announce('구역 확보 · 녹색 통로로 전진',4);}updateHud();}if(wave===5){intermission-=lastDt;if(intermission<=0)finish(true);}else if(pos[2]<-30-(wave-1)*60-1)waveStart();}
let lastDt=0;
function updateHud(){$('hp').innerHTML=Math.max(0,Math.ceil(hp))+' <em>/ 100</em>';$('hpbar').style.width=hp+'%';$('hpbar').style.background=hp<30?'#f07e55':'#b9f97b';$('ammo').innerHTML=ammo+' <em>/ ∞</em>';$('gunstatus').textContent=reload>0?'재장전 중…':'5.56 × 45 MM';$('wave').textContent='WAVE '+String(wave).padStart(2,'0');$('remaining').textContent=sectorCleared?'구역 확보 · 다음 구역으로 전진':'적 '+enemies.filter(e=>!e.dead).length+'기 남음';$('sectorlabel').textContent='SECTOR '+String(wave).padStart(2,'0')+' / 05 · FOUNDRY';$('healinfo').textContent='회복 드롭 '+Math.round(dropChance(hp)*100)+'% · 키트 +'+[50,30,20][difficulty]+' HP';}
function start(){enemies.length=debris.length=bolts.length=particles.length=pickups.length=0;for(const g of gates)g.open=false;sectorCleared=false;threatTimer=0;threatSource=null;wave=0;hp=100;ammo=30;reload=0;kills=broken=shots=hits=elapsed=0;pos=[0,1.7,19];yaw=pitch=jumpV=0;intermission=cooldown=0;state='play';for(const id of ['menu','pause','end'])$(id).classList.add('hidden');$('hud').classList.remove('hidden');if(touch)$('touch').classList.remove('hidden');waveStart();lock();sound(350,.2,.03);}
function lock(){if(touch)return;try{const p=canvas.requestPointerLock();if(p&&p.catch)p.catch(()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});}catch{lockedFallback=true;}}
function pause(){if(state!=='play')return;state='pause';fire=aim=false;keys.clear();joystick=[0,0];$('pause').classList.remove('hidden');$('touch').classList.add('hidden');document.exitPointerLock?.();}
function resume(){state='play';$('pause').classList.add('hidden');if(touch)$('touch').classList.remove('hidden');lock();}
function toMenu(){state='menu';fire=false;keys.clear();document.exitPointerLock?.();for(const id of ['pause','end','hud','touch'])$(id).classList.add('hidden');$('menu').classList.remove('hidden');enemies.length=bolts.length=debris.length=particles.length=pickups.length=0;for(const g of gates)g.open=false;wave=1;spawn(0,0,-1);spawn(1,5,-5);spawn(2,11,-10);}
function finish(win){state='end';fire=false;document.exitPointerLock?.();$('end').classList.remove('hidden');$('touch').classList.add('hidden');$('resultlabel').textContent=win?'SECTOR SECURED':'OPERATOR DOWN';$('resulttitle').textContent=win?'구역 확보 완료.':'작전 종료.';$('stats').innerHTML=`${wave} / 5 웨이브 · ${kills}기 제압 · ${broken}개 부위 파괴<br>명중률 ${shots?Math.round(hits/shots*100):0}% · ${Math.floor(elapsed/60)}분 ${Math.floor(elapsed%60)}초`;sound(win?660:100,.5,.06);}
function beginReload(){if(state!=='play'||reload>0||ammo===30)return;reload=2.05;fire=false;updateHud();sound(850,.12,.035,true);}
function rayBox(o,d,b){if(b.open)return null;if(b.a){const c=Math.cos(b.a),s=Math.sin(b.a),x=o[0]-b.p[0],z=o[2]-b.p[2];o=[c*x-s*z+b.p[0],o[1],s*x+c*z+b.p[2]];d=[c*d[0]-s*d[2],d[1],s*d[0]+c*d[2]];}let tmin=0,tmax=500;for(let i=0;i<3;i++){let lo=b.p[i]-b.s[i]/2,hi=b.p[i]+b.s[i]/2;if(Math.abs(d[i])<1e-7){if(o[i]<lo||o[i]>hi)return null;}else{let a=(lo-o[i])/d[i],v=(hi-o[i])/d[i];if(a>v)[a,v]=[v,a];tmin=Math.max(tmin,a);tmax=Math.min(tmax,v);if(tmin>tmax)return null;}}return tmin;}
function trace(o,d,includeEnemies=true,max=100){let closest=max,obj=null;for(const b of world){if(!b.blocksShots||b.open)continue;const t=rayBox(o,d,b);if(t!==null&&t<closest){closest=t;obj=b;}}if(includeEnemies)for(const e of enemies)if(!e.dead)for(const p of e.parts)if(p.hp>0){const t=rayBox(o,d,partBox(e,p));if(t!==null&&t<closest){closest=t;obj=p;}}return {t:closest,obj};}
function sparks(p,color,n=7){for(let i=0;i<n;i++)particles.push({p:[...p],s:[.045,.045,.045],c:color,g:1,v:[(Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5],life:.25+Math.random()*.3});}
function detach(e,p){const b=partBox(e,p);debris.push({...b,p:[...b.p],v:[(Math.random()-.5)*4,2.8,(Math.random()-.5)*4],life:8,a:Math.random()*6});p.hp=0;}
function kill(e){if(e.dead)return;e.dead=true;kills++;for(const p of e.parts)if(p.hp>0)detach(e,p);sparks([e.p[0],e.scale,e.p[2]],C.amber,15);dropHealth(e);log(e.type.name+' 제압 +'+(e.type.hp*10));updateHud();}
function shoot(){if(state!=='play'||cooldown>0||reload>0)return;if(ammo===0){beginReload();return;}ammo--;shots++;cooldown=.105;recoil=.07;let spread=aim?.0018:.009;const dir=norm([-Math.sin(yaw)*Math.cos(pitch)+(Math.random()-.5)*spread,Math.sin(pitch)+(Math.random()-.5)*spread,-Math.cos(yaw)*Math.cos(pitch)]);let hit=trace(pos,dir),impact=pos.map((v,i)=>v+dir[i]*hit.t);const muzzle=[pos[0]+Math.cos(yaw)*.22-Math.sin(yaw)*.6,pos[1]-.15,pos[2]-Math.sin(yaw)*.22-Math.cos(yaw)*.6];const muzzleDelta=muzzle.map((v,i)=>v-pos[i]);const nearWall=trace(pos,norm(muzzleDelta),false,Math.hypot(...muzzleDelta));if(nearWall.obj){hit=nearWall;impact=pos.map((v,i)=>v+norm(muzzleDelta)[i]*hit.t);}else{const toImpact=impact.map((v,i)=>v-muzzle[i]),gunHit=trace(muzzle,norm(toImpact),true,Math.hypot(...toImpact)+.02);if(gunHit.obj){hit=gunHit;impact=muzzle.map((v,i)=>v+norm(toImpact)[i]*hit.t);}}sparks(impact,hit.obj?.e?C.amber:C.metal,hit.obj?6:0);if(hit.obj?.e){hits++;hitTimer=.12;const p=hit.obj,e=p.e,damage=p.name==='머리'?38:p.name==='코어'?30:26;e.hp-=damage;p.hp-=damage;if(p.hp<=0&&p.name!=='코어'){detach(e,p);broken++;log(p.name+' 파괴 · '+(p.name.includes('다리')?'이동 능력 저하':p.name.includes('팔')?'공격 능력 저하':'치명타'));if(p.name==='머리')e.hp=0;}if(e.hp<=0)kill(e);sound(920,.06,.028);}pitch=clamp(pitch+.003,-1.35,1.35);sound(1800,.10,.12,true);updateHud();}
function canMove(x,z,r=.38){if(Math.abs(x)>21.4-r||z>29.4-r||z<-269.4+r)return false;for(const b of obstacles){if(b.open||b.s[1]<.4||b.p[1]-b.s[1]/2>3)continue;if(Math.abs(x-b.p[0])<b.s[0]/2+r&&Math.abs(z-b.p[2])<b.s[2]/2+r)return false;}return true;}
function move(p,dx,dz,r){if(canMove(p[0]+dx,p[2],r))p[0]+=dx;if(canMove(p[0],p[2]+dz,r))p[2]+=dz;}
function damagePlayer(amount,source=null){if(state!=='play')return;if(source){threatSource=[...source];threatTimer=1.4;}hp=Math.max(0,hp-amount);damageTimer=.45;sound(70,.16,.065);if(hp<=0)finish(false);updateHud();}
function update(dt){if(state!=='play')return;lastDt=dt;elapsed+=dt;collectHealth();threatTimer=Math.max(0,threatTimer-dt);if(threatTimer>0&&threatSource){const dx=threatSource[0]-pos[0],dz=threatSource[2]-pos[2],right=Math.cos(yaw)*dx-Math.sin(yaw)*dz,forward=-Math.sin(yaw)*dx-Math.cos(yaw)*dz;const bearing=Math.atan2(right,forward);$('threat').style.opacity='1';$('threatarrow').style.transform='rotate('+bearing+'rad)';$('threattext').textContent=(forward<0?'후방':Math.abs(right)>Math.abs(forward)?(right>0?'오른쪽':'왼쪽'):'전방')+' 공격 · '+Math.round(Math.hypot(dx,dz))+'m';}else $('threat').style.opacity='0';if(sectorCleared&&wave<5){const distance=Math.max(0,Math.round(pos[2]-(-31-(wave-1)*60)));$('objective').textContent='↓ 다음 구역 · '+distance+'m';}else $('objective').textContent='전방 적을 모두 제압하세요';feet+=dt*5;cooldown=Math.max(0,cooldown-dt);recoil=Math.max(0,recoil-dt*.5);hitTimer=Math.max(0,hitTimer-dt);damageTimer=Math.max(0,damageTimer-dt);noticeTimer-=dt;feedTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';if(feedTimer<=0)$('feed').textContent='';$('hit').style.opacity=hitTimer>0?1:0;$('damage').style.opacity=damageTimer;let fw=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joystick[1],rt=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joystick[0],l=Math.max(1,Math.hypot(fw,rt));const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')?7:4.7)*(aim?.57:1);move(pos,(-Math.sin(yaw)*fw+Math.cos(yaw)*rt)*speed*dt/l,(-Math.cos(yaw)*fw-Math.sin(yaw)*rt)*speed*dt/l,.35);if(pos[1]>1.7||jumpV>0){jumpV-=15*dt;pos[1]+=jumpV*dt;if(pos[1]<1.7){pos[1]=1.7;jumpV=0;}}if(reload>0){reload-=dt;if(reload<=0){reload=0;ammo=30;sound(500,.07,.025,true);updateHud();}}if(fire)shoot();
for(const e of enemies){if(e.dead)continue;e.age+=dt;let dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],dist=Math.hypot(dx,dz),legs=e.parts.filter(p=>p.hp>0&&p.name.includes('다리')).length,arms=e.parts.filter(p=>p.hp>0&&p.name.includes('팔')).length;const line=trace([e.p[0],e.scale*1.3,e.p[2]],norm([dx,pos[1]-e.scale*1.3,dz]),false,dist);e.angle=Math.atan2(dx,dz);const blocked=!!line.obj;let sp=e.type.speed*([.75,1,1.18][difficulty])*(legs===2?1:legs===1?.48:.12);let reach=arms?8:1.4;if(dist>reach||blocked){let nx=dx/(dist||1),nz=dz/(dist||1),mx=nx*sp*dt,mz=nz*sp*dt;const ox=e.p[0],oz=e.p[2];move(e.p,mx,mz,.45*e.scale);if(Math.hypot(e.p[0]-ox,e.p[2]-oz)<sp*dt*.3){let side=Math.sin(e.phase)>0?1:-1;move(e.p,-nz*sp*dt*side,nx*sp*dt*side,.45*e.scale);}}
// Separate enemies, without pushing them into cover.
for(const other of enemies){if(other===e||other.dead)continue;let sx=e.p[0]-other.p[0],sz=e.p[2]-other.p[2],sl=Math.hypot(sx,sz),minimum=.45*(e.scale+other.scale);if(sl>0&&sl<minimum)move(e.p,sx/sl*dt,sz/sl*dt,.45*e.scale);}
e.timer-=dt;if(e.warning>0){e.warning-=dt;if(e.warning<=0)fireEnemy(e,arms);}else if(e.age>2.5&&e.timer<=0&&!blocked&&dist<(arms?25:1.8)){e.timer=e.type.rate*(arms===1?1.8:1)*([1.3,1,.8][difficulty])+.55;e.warning=.55;alertAttack(e);}}
for(let i=bolts.length-1;i>=0;i--){const b=bolts[i],prev=[...b.p],speed=Math.hypot(...b.v),d=b.v.map(v=>v/speed),travel=speed*dt;const wall=trace(prev,d,false,travel+.001);const body=box([pos[0],pos[1]-.45,pos[2]],[.7,1.25,.7],C.dark),playerT=rayBox(prev,d,body);if(playerT!==null&&playerT<=travel&&(!wall.obj||playerT<wall.t)){damagePlayer(b.damage,b.source);bolts.splice(i,1);continue;}if(wall.obj){sparks(prev.map((v,j)=>v+d[j]*wall.t),C.amber,4);bolts.splice(i,1);continue;}b.p=b.p.map((v,j)=>v+b.v[j]*dt);b.life-=dt;if(b.life<=0)bolts.splice(i,1);}
for(const arr of [particles,debris])for(let i=arr.length-1;i>=0;i--){const b=arr[i];b.life-=dt;b.v[1]-=9*dt;for(let j=0;j<3;j++)b.p[j]+=b.v[j]*dt;if(b.p[1]<b.s[1]/2){b.p[1]=b.s[1]/2;b.v[1]=Math.abs(b.v[1])*.18;b.v[0]*=.88;b.v[2]*=.88;}if(arr===debris)b.a+=dt*b.v[0];if(b.life<=0)arr.splice(i,1);}
advanceSector();
const d=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],t=trace(pos,d);if(t.obj?.e){const e=t.obj.e,p=t.obj;$('target').textContent=e.type.name+' · '+p.name+' '+(p.name==='코어'?Math.ceil(e.hp):Math.ceil(p.hp))+' HP';}else $('target').textContent='';
}
// Armor plates and joints follow the destructible part, so every detail detaches with it.
function robotDetail(b,offset,size,color,kind='box',glow=0){const c=Math.cos(b.a),s=Math.sin(b.a),p=[b.p[0]+c*offset[0]+s*offset[2],b.p[1]+offset[1],b.p[2]-s*offset[0]+c*offset[2]];draw({...box(p,size,color,b.a,glow),kind});}
function drawRobot(e,time){const S=e.scale,accent=e.type.accent,white=[.86,.91,.85],joint=[.09,.12,.15];for(const part of e.parts)if(part.hp>0){let b=partBox(e,part);const damaged=part.hp<part.max*.5&&part.name!=='코어';const color=damaged?e.type.c.map(x=>x*.65):e.type.c;const detail=(off,size,c,kind='box',g=0)=>robotDetail(b,off.map(x=>x*S),size.map(x=>x*S),c,kind,g);
 if(part.name==='머리'){draw({...b,c:color});detail([0,.25,0],[.29,.12,.32],accent);detail([0,-.01,.205],[.28,.39,.065],joint);detail([0,0,.247],[.23,.23,.035],[.38,.025,.035],'cylinder');detail([0,0,.273],[.15,.15,.035],[1,.005,.018],'cylinder',2.2);detail([0,0,.296],[.055,.09,.02],[1,.12,.16],'cylinder',1.5);detail([0,-.25,.2],[.24,.08,.06],white);
 }else if(part.name==='코어'){draw({...b,c:joint});detail([-.23,.13,.02],[.23,.40,.44],color);detail([.23,.13,.02],[.23,.40,.44],color);detail([0,0,.245],[.44,.44,.11],accent,'cylinder');detail([0,0,.31],[.31,.31,.035],joint,'cylinder');detail([0,0,.34],[.13,.13,.04],C.amber,'cylinder',.6);detail([0,-.25,.05],[.61,.15,.43],color);detail([0,.34,0],[.15,.12,.17],joint);
 }else if(part.name.includes('팔')){draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.55)),c:joint});detail([0,.26,0],[.37,.29,.36],color);detail([0,.29,.20],[.25,.14,.07],accent);detail([0,-.02,.02],[.25,.23,.33],white,'cylinder');detail([0,-.27,0],[.33,.25,.34],color);detail([0,-.28,.21],[.14,.14,.12],joint,'cylinder');if(e.warning>0)detail([0,-.28,.30],[.15,.15,.04],C.red,'cylinder',2.5);
 }else {draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.6)),c:joint});detail([0,.20,0],[.26,.27,.30],color);detail([0,-.025,.08],[.25,.22,.22],accent,'cylinder');detail([0,-.23,0],[.27,.28,.30],color);detail([0,-.34,.04],[.27,.12,.31],white);}}
 const top=2.57*S;draw(box([e.p[0],top,e.p[2]],[.85*S,.05,.035],C.dark));draw(box([e.p[0]-(1-e.hp/e.max)*.425*S,top,e.p[2]+.025],[.85*S*clamp(e.hp/e.max,0,1),.055,.035],e.type.c,0,.8));}
function render(time){let eye=pos,y=yaw,p=pitch;if(state==='menu'){eye=[17,6.1,22];y=.43+Math.sin(time*.00008)*.10;p=-.13;}
const fov=state==='play'&&aim?.70:1.18;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.045,.085,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,multiply(projection(fov),view(eye,y,p)));gl.uniform3fv(U.Eye,eye);gl.uniform1f(U.Fog,.020);for(const b of world)if(Math.abs(b.p[2]-eye[2])<85)draw(b);
for(const e of enemies)if(!e.dead){if(state==='menu')e.angle=Math.atan2(eye[0]-e.p[0],eye[2]-e.p[2]);drawRobot(e,time);}for(const item of pickups){const h=.55+Math.sin(time*.003)*.12;draw(box([item.p[0],h,item.p[2]],[.65,.42,.50],[.09,.45,.19],time*.001));draw(box([item.p[0],h+.26,item.p[2]],[.13,.10,.44],C.lime,0,1.2));draw(box([item.p[0],h+.26,item.p[2]],[.44,.10,.13],C.lime,0,1.2));draw(box([item.p[0],.03,item.p[2]],[.9,.035,.9],[.14,.5,.15],0,.3));}
if(sectorCleared&&wave<5){const z=-30-(wave-1)*60;for(const x of [-3.9,3.9])draw(box([x,2,z],[.12,4,.12],C.lime,0,1.5));}
for(const arr of [debris,bolts,particles])for(const b of arr)draw(b);
if(state!=='menu'){gl.clear(gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,projection(1.0));gl.uniform3fv(U.Eye,[0,0,0]);gl.uniform1f(U.Fog,0);const moving=state==='play'&&(keys.has('KeyW')||keys.has('KeyA')||keys.has('KeyS')||keys.has('KeyD')||Math.hypot(...joystick)>.1);let bob=moving?Math.sin(time*.013)*.008:Math.sin(time*.002)*.002;let reloadDrop=reload>0?Math.sin((2.05-reload)/2.05*Math.PI)*.35:0;for(const b of gun)draw({...b,p:[b.p[0]-(aim?.24:0),b.p[1]+(aim?.065:0)+bob-reloadDrop,b.p[2]+recoil]});if(recoil>.046){draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.085],[.085,.085,.19],C.amber,time*.1,2));draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.1],[.14,.025,.14],C.lime,0,3));}}
}
function resize(){let d=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);}window.addEventListener('resize',resize);resize();
$('start').onclick=start;$('retry').onclick=start;$('resume').onclick=resume;$('quit').onclick=toMenu;$('back').onclick=toMenu;$('sensitivity').oninput=e=>sensitivity=Number(e.target.value);document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{difficulty=Number(b.dataset.d);document.querySelectorAll('[data-d]').forEach(x=>x.classList.toggle('active',x===b));});
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&state==='play'){pause();return;}if(state!=='play')return;keys.add(e.code);if(e.code==='KeyR')beginReload();if(e.code==='Space'&&pos[1]<=1.71)jumpV=6;});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(state==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='play'&&!lockedFallback&&!touch)pause();});document.addEventListener('pointerlockerror',()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('mousedown',e=>{if(state!=='play'||e.target!==canvas)return;if(e.button===0)fire=true;if(e.button===2)aim=true;});window.addEventListener('mouseup',e=>{if(e.button===0)fire=false;if(e.button===2)aim=false;});window.addEventListener('mousemove',e=>{if(state==='play'&&(document.pointerLockElement===canvas||lockedFallback&&e.buttons)){yaw-=e.movementX*.002*sensitivity*(aim?.6:1);pitch=clamp(pitch-e.movementY*.002*sensitivity*(aim?.6:1),-1.35,1.35);}});
canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='play'){lookPointer=e.pointerId;lastLook=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(e.pointerId===lookPointer){yaw-=(e.clientX-lastLook[0])*.005;pitch=clamp(pitch-(e.clientY-lastLook[1])*.005,-1.35,1.35);lastLook=[e.clientX,e.clientY];}});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{if(e.pointerId===lookPointer)lookPointer=null;});
const stick=$('stick');function stickMove(e){const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38,l=Math.max(1,Math.hypot(x,y));joystick=[x/l,y/l];stick.firstElementChild.style.transform=`translate(${joystick[0]*28}px,${joystick[1]*28}px)`;}let stickId=null;stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===stickId)stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{stickId=null;joystick=[0,0];stick.firstElementChild.style.transform='';};$('touchfire').onpointerdown=e=>{e.preventDefault();fire=true;$('touchfire').setPointerCapture(e.pointerId);};$('touchfire').onpointerup=$('touchfire').onpointercancel=()=>fire=false;$('touchreload').onclick=beginReload;$('touchpause').onclick=pause;
let last=performance.now();function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;update(dt);render(t);requestAnimationFrame(frame);}toMenu();requestAnimationFrame(frame);
})();
