'use strict';
(()=>{
const $=id=>document.getElementById(id), canvas=$('game');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){$('error').classList.remove('hidden');return;}
const vs=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uVP;uniform vec3 uPos;uniform vec3 uSize;uniform float uAngle;uniform float uTilt;varying vec3 vNormal;varying vec3 vWorld;void main(){float c=cos(uAngle),s=sin(uAngle);mat3 r=mat3(c,0.,-s,0.,1.,0.,s,0.,c);float ct=cos(uTilt),st=sin(uTilt);mat3 rx=mat3(1.,0.,0.,0.,ct,st,0.,-st,ct);r=r*rx;vWorld=r*(aPos*uSize)+uPos;vNormal=r*aNormal;gl_Position=uVP*vec4(vWorld,1.);}`;
const fs=`precision mediump float;uniform vec3 uColor;uniform vec3 uEye;uniform float uGlow;uniform float uFog;varying vec3 vNormal;varying vec3 vWorld;void main(){float light=.35+max(dot(normalize(vNormal),normalize(vec3(-.5,.9,.3))),0.)*.75;vec3 col=uColor*(light+uGlow);float fog=1.-exp(-distance(vWorld,uEye)*uFog);gl_FragColor=vec4(mix(col,vec3(.045,.085,.09),fog),1.);}`;
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Renderer link');gl.useProgram(program);
const U={};for(const n of ['VP','Pos','Size','Angle','Tilt','Color','Eye','Glow','Fog'])U[n]=gl.getUniformLocation(program,'u'+n);
const verts=[];const faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]],[[0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]]];for(const f of faces)for(const i of [1,2,3,1,3,4])verts.push(...f[i],...f[0]);for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const x=Math.cos(a)*.5,y=Math.sin(a)*.5,X=Math.cos(b)*.5,Y=Math.sin(b)*.5;for(const v of [[x,y,-.5],[X,Y,-.5],[X,Y,.5],[x,y,-.5],[X,Y,.5],[x,y,.5]])verts.push(...v,Math.cos((a+b)/2),Math.sin((a+b)/2),0);for(const z of [-.5,.5])for(const v of [[0,0,z],[x,y,z],[X,Y,z]])verts.push(...v,0,0,Math.sign(z));}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);for(const [n,offset]of [['aPos',0],['aNormal',12]]){let a=gl.getAttribLocation(program,n);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);
const C={floor:[.17,.22,.21],wall:[.19,.25,.25],dark:[.065,.105,.105],metal:[.28,.34,.32],lime:[.65,.95,.37],amber:[1,.45,.13],red:[.9,.18,.10],blue:[.24,.7,.8]};
const world=[], obstacles=[], gates=[], pickups=[], debris=[], bolts=[], particles=[], enemies=[];let gun=[];
const box=(p,s,c,a=0,g=0)=>({p:[...p],s:[...s],c,a,g});
function add(p,s,c,a=0,g=0,solid=false){const b=box(p,s,c,a,g);b.blocksShots=solid||s[1]>.25;world.push(b);if(solid)obstacles.push(b);return b;}
function draw(b){if(b.open)return;gl.uniform3fv(U.Pos,b.p);gl.uniform3fv(U.Size,b.s);gl.uniform3fv(U.Color,b.c);gl.uniform1f(U.Angle,b.a||0);gl.uniform1f(U.Tilt,b.tilt||0);gl.uniform1f(U.Glow,b.g||0);gl.drawArrays(gl.TRIANGLES,b.kind==='cylinder'?36:0,b.kind==='cylinder'?144:36);}
function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function view(eye,yaw,pitch){let sy=Math.sin(yaw),cy=Math.cos(yaw),sp=Math.sin(pitch),cp=Math.cos(pitch);let right=[cy,0,-sy],up=[sy*sp,cp,cy*sp],back=[sy*cp,-sp,cy*cp];return new Float32Array([right[0],up[0],back[0],0,right[1],up[1],back[1],0,right[2],up[2],back[2],0,-dot(right,eye),-dot(up,eye),-dot(back,eye),1]);}
function projection(fov){let f=1/Math.tan(fov/2),n=.025,far=160;return new Float32Array([f/(canvas.width/canvas.height),0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function norm(v){let l=Math.hypot(...v)||1;return v.map(x=>x/l);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
// Five connected foundry halls. Each cleared gate opens toward the next hall.
function container(x,z,w,d,h,c){add([x,h/2,z],[w,h,d],c,0,0,true);for(let k=-w/2+.25;k<w/2;k+=.55)add([x+k,h/2,z+d/2+.025],[.09,h-.12,.08],c.map(v=>v*1.15));add([x,h+.05,z],[w+.12,.1,d+.1],C.metal);}
for(let sector=0;sector<10;sector++){
 const z=-sector*60;
 add([0,-.25,z],[44,.5,60],C.floor);
 for(const x of [-22,22])add([x,4,z],[1,8,60],C.wall,0,0,true);
 for(let k=-28;k<=28;k+=4){add([0,.009,z+k],[43,.012,.023],[.25,.32,.29]);add([k*.7,.006,z],[.023,.012,60],[.25,.32,.29]);}
 for(const x of [-18,18])for(const dz of [-22,-5,15]){add([x,4,z+dz],[.75,8,.75],C.dark,0,0,true);add([x,5,z+dz+.4],[.12,2,.08],C.lime,0,.8);}
 container(-12,z-9,5,3,3,[.16,.30,.31]);container(12,z-18,5,3,3.4,[.35,.26,.19]);container(-15,z+15,4,5,2.8,[.27,.32,.27]);
 for(const [x,dz]of [[-6,4],[7,-5],[10,17]]){add([x,.7,z+dz],[2.6,1.4,1.8],C.metal,0,0,true);add([x,1.43,z+dz],[2.7,.08,1.9],C.dark);}
 for(const x of [-13,13])add([x,4,z-30],[18,8,.8],C.wall,0,0,true);
 if(sector<9){let gate=add([0,3,z-30],[8,6,.6],[.25,.32,.30],0,0,true);gate.sector=sector;gates.push(gate);}
 else add([0,4,z-30],[8,8,.8],C.wall,0,0,true);
 for(const x of [-4.2,4.2])add([x,3,z-29.5],[.16,6,.1],C.amber,0,1);
 for(let dz=20;dz>-28;dz-=6){add([-.48,.015,z+dz],[.12,.025,1.1],C.lime,-.55,.3);add([.48,.015,z+dz],[.12,.025,1.1],C.lime,.55,.3);}
}
add([0,4,30],[44,8,1],C.wall,0,0,true);
// HK416-inspired placeholder: receiver, stock, rail, handguard, barrel, magazine and sights.
function gb(p,s,c=C.dark,a=0){gun.push(box(p,s,c,a));}
gb([.24,-.24,-.42],[.115,.13,.36],[.13,.15,.145]);gb([.24,-.28,-.24],[.14,.14,.15],[.11,.125,.12]);gb([.24,-.18,-.59],[.125,.12,.30],[.20,.23,.20]);gb([.24,-.174,-.86],[.033,.035,.27],[.09,.1,.09]);gb([.24,-.174,-1.015],[.052,.054,.075],C.dark);gb([.24,-.36,-.45],[.085,.23,.115],[.15,.16,.145],-.06);gb([.24,-.37,-.23],[.067,.16,.085],C.dark);gb([.24,-.27,-.08],[.09,.065,.23],C.dark);gb([.24,-.285,.01],[.135,.17,.17],[.12,.14,.12]);gb([.24,-.13,-.44],[.052,.024,.52],[.13,.15,.13]);for(let i=0;i<20;i++)gb([.24,-.11,-.20-i*.026],[.084,.018,.011],[.20,.23,.20]);for(let i=0;i<7;i++){gb([.307,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);gb([.174,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);}for(const z of [-.33,-.71]){gb([.24,-.087,z],[.03,.065,.027],C.dark);gb([.216,-.056,z],[.015,.045,.025],C.dark);gb([.264,-.056,z],[.015,.045,.025],C.dark);}gb([.24,-.29,-.65],[.06,.12,.065],C.dark);gb([.295,-.237,-.35],[.012,.026,.073],[.38,.41,.36]);
// Gloved hands.
gb([.235,-.41,-.23],[.11,.13,.13],[.24,.28,.22]);gb([.08,-.44,-.05],[.18,.17,.38],[.17,.22,.17],-.22);gb([.21,-.35,-.63],[.14,.12,.13],[.24,.28,.22]);gb([.0,-.49,-.45],[.14,.14,.34],[.17,.22,.17],-.5);
const types=[{name:'정찰형',hp:70,scale:.78,speed:7.4,melee:true,c:[.05,.80,.95],accent:[1,.76,.10],arm:24,leg:25,head:32,damage:12,rate:1.1},{name:'전투형',hp:150,scale:1.1,speed:2.2,c:[1,.38,.055],accent:[.12,.75,.98],arm:44,leg:44,head:56,damage:12,rate:1.65},{name:'중장갑형',hp:400,scale:1.7,speed:1.35,c:[.67,.20,.95],accent:[1,.78,.10],arm:90,leg:95,head:110,damage:18,rate:1.3}];
let state='menu',difficulty=1,wave=0,hp=100,ammo=30,reload=0,kills=0,broken=0,shots=0,hits=0,elapsed=0,yaw=0,pitch=0,pos=[0,1.7,19],jumpV=0,fire=false,aim=false,cooldown=0,recoil=0,hitTimer=0,damageTimer=0,noticeTimer=0,intermission=0,feedTimer=0,feet=0,sensitivity=1,lockedFallback=false,sectorCleared=false,threatTimer=0;let threatSource=null;let chosenDifficulty=1;let rankCheckpoints=[];let mode='standard',sprinting=false,sprintBlend=0,sprintTouch=false,stepTimer=0,score=0,rankRun=null,rankResult=null,rankStart=0,rankSync=Promise.resolve(),rankError='',runEpoch=0,stageStats={kills:[0,0,0],parts:0,bossParts:0,boss:false};const scheduled=[],lasers=[],sweeps=[];const totalStages=()=>mode==='ranked'?10:5;const bulletSpeed=()=>mode==='ranked'?26:[11,15,19][difficulty];const SPRINT_SPEED=32;
const keys=new Set(),touch='ontouchstart'in window;let joystick=[0,0],lookPointer=null,lastLook=[0,0],audioCtx;
function sound(f,d=.08,volume=.05,noise=false,source=null){if(!$('sound').checked)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const g=audioCtx.createGain();const distance=source?Math.hypot(source[0]-pos[0],source[2]-pos[2]):0;g.gain.setValueAtTime(volume*(Number($('soundlevel').value)/100)*(source?clamp(14/(distance+7),.2,1):1),audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);if(source&&audioCtx.createStereoPanner){const pan=audioCtx.createStereoPanner();const dx=source[0]-pos[0],dz=source[2]-pos[2];pan.pan.value=clamp((Math.cos(yaw)*dx-Math.sin(yaw)*dz)/(distance||1),-1,1);g.connect(pan);pan.connect(audioCtx.destination);}else g.connect(audioCtx.destination);let o;if(noise){let b=audioCtx.createBuffer(1,audioCtx.sampleRate*d,audioCtx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1);o=audioCtx.createBufferSource();o.buffer=b;let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=f;o.connect(filter);filter.connect(g);}else{o=audioCtx.createOscillator();o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.5,audioCtx.currentTime+d);o.connect(g);}o.start();o.stop(audioCtx.currentTime+d);}catch{}}
const robotBuffers=new Map(),robotVoices=[];let audioLoad=null,robotBus=null;
function prepareRobotAudio(){if(!audioCtx)return Promise.resolve();if(audioLoad)return audioLoad;const files=[];for(const kind of ['scout','soldier','heavy','boss'])for(const event of ['move','alert','attack','death',...(kind==='boss'?['sweep','missiles','laser','burst','blades']:[])])files.push(kind+'-'+event);audioLoad=Promise.all(files.map(async key=>{try{const r=await fetch('audio/'+key+'.wav');if(!r.ok)throw Error('Audio unavailable');robotBuffers.set(key,await audioCtx.decodeAudioData(await r.arrayBuffer()));}catch{}}));return audioLoad;}
function robotSound(e,event){if(!$('sound').checked)return;const kind=e.boss?'boss':['scout','soldier','heavy'][e.typeIndex],key=kind+'-'+event;if(!audioCtx){sound(60,.01,0);prepareRobotAudio();}const buffer=robotBuffers.get(key);if(!buffer){sound(e.boss?48:e.typeIndex===2?62:e.typeIndex===1?120:210,event==='death'?.4:.16,.075,event!=='alert',e.p);return;}const distance=Math.hypot(e.p[0]-pos[0],e.p[2]-pos[2]);if(distance>65||robotVoices.length>=(event==='move'?10:24))return;
if(!robotBus){robotBus=audioCtx.createDynamicsCompressor();robotBus.threshold.value=-18;robotBus.knee.value=16;robotBus.ratio.value=4;robotBus.attack.value=.005;robotBus.release.value=.2;robotBus.connect(audioCtx.destination);}const src=audioCtx.createBufferSource(),gain=audioCtx.createGain(),pan=audioCtx.createStereoPanner(),filter=audioCtx.createBiquadFilter();src.buffer=buffer;e.voicePitch??=.94+Math.random()*.12;src.playbackRate.value=e.voicePitch*(event==='move'?1+Math.random()*.08:1);filter.type='lowpass';const blocked=!lineOfSight(pos,[e.p[0],1.2,e.p[2]]);filter.frequency.value=blocked?900:7000;src.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(robotBus);const voice={src,gain,pan,e,event,blocked};robotVoices.push(voice);src.onended=()=>{const i=robotVoices.indexOf(voice);if(i>=0)robotVoices.splice(i,1);src.disconnect();filter.disconnect();gain.disconnect();pan.disconnect();};setVoicePosition(voice);src.start();}
function setVoicePosition(v){const dx=v.e.p[0]-pos[0],dz=v.e.p[2]-pos[2],distance=Math.hypot(dx,dz);v.pan.pan.value=clamp((Math.cos(yaw)*dx-Math.sin(yaw)*dz)/(distance||1),-1,1);const level=Number($('soundlevel').value)/100;v.gain.gain.value=level*(v.event==='move'?.33:.60)*(v.e.boss?1.2:1)*clamp(14/(distance+5),.05,1)*(v.blocked?.4:1);}
function stopRobotSounds(e=null,event=null){for(const v of [...robotVoices])if((!e||v.e===e)&&(!event||v.event===event)){try{v.src.stop();}catch{}}}
function updateRobotAudio(dt){for(const v of robotVoices)setVoicePosition(v);for(const e of enemies){if(e.dead)continue;const moving=e.audioPos&&Math.hypot(e.p[0]-e.audioPos[0],e.p[2]-e.audioPos[1])>.006;e.audioPos=[e.p[0],e.p[2]];e.stepClock=(e.stepClock??Math.random()*.4)-dt;if(moving&&e.stepClock<=0){robotSound(e,'move');e.stepClock=e.boss?.85:e.typeIndex===2?.70:e.typeIndex===1?.43:.23;}}}
$('sound').onchange=()=>{if(!$('sound').checked)stopRobotSounds();};

function part(e,name,p,s,h,c){const b=box(p,s,c||e.type.c);b.name=name;b.hp=h;b.max=h;b.e=e;b.local=p;e.parts.push(b);}
function spawn(type,x,z){const t=types[type],m=[.72,1,1.45][difficulty]*(1+(wave-1)*.12),e={type:t,p:[x,0,z],parts:[],hp:t.hp*m,max:t.hp*m,scale:t.scale,timer:1.5+Math.random()*2,phase:Math.random()*6,dead:false,stagger:0,angle:0,age:0,warning:0};part(e,'코어',[0,1.27,0],[.68,.7,.43],999);part(e,'머리',[0,2.02,0],[.36,.68,.38],t.head*m);part(e,'왼팔',[-.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'오른팔',[.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'왼다리',[-.21,.44,0],[.27,.83,.31],t.leg*m);part(e,'오른다리',[.21,.44,0],[.27,.83,.31],t.leg*m);e.typeIndex=type;enemies.push(e);return e;}
function partBox(e,p){const legs=e.parts.filter(p=>p.hp>0&&p.name.includes('다리')).length;let y=e.boss?0:legs===0?-.60:legs===1?-.13:0;let step=p.name.includes('다리')&&legs>0?Math.sin(feet*2+e.phase+(p.name==='왼다리'?0:Math.PI))*.09:0;const c=Math.cos(e.angle),s=Math.sin(e.angle);return {...p,a:e.angle,p:[e.p[0]+(c*p.local[0]+s*p.local[2])*e.scale,e.p[1]+(p.local[1]+y+step)*e.scale,e.p[2]+(-s*p.local[0]+c*p.local[2])*e.scale],s:p.s.map(x=>x*e.scale)};}
function announce(s,time=2.8){$('notice').textContent=s;noticeTimer=time;}
function log(s){$('feed').textContent=s;feedTimer=2.5;}
const WEAPONS=[{name:'HK416 · AUTO',capacity:30,reload:2.05,delay:.105,damage:30},{name:'PISTOL · SEMI',capacity:12,reload:1.35,delay:.25,damage:48},{name:'RPG · EXPLOSIVE',capacity:5,reload:0,delay:.9,damage:650}];
let weapon=0,magazines=[30,12],rpgAmmo=0,grenades=0,punchTimer=0,meleeCooldown=0,grenadeCooldown=0;const playerOrdnance=[];
const rifle=gun,pistol=[],rpg=[];function weaponBox(arr,p,s,c=C.dark,kind='box'){arr.push({...box(p,s,c),kind});}
weaponBox(pistol,[.24,-.23,-.46],[.11,.11,.34],[.35,.37,.39]);weaponBox(pistol,[.24,-.32,-.32],[.085,.19,.11],[.10,.11,.12]);weaponBox(pistol,[.24,-.20,-.65],[.06,.06,.06],C.dark);weaponBox(pistol,[.24,-.165,-.55],[.018,.035,.025],C.lime);weaponBox(pistol,[.24,-.36,-.27],[.13,.14,.15],[.24,.28,.22]);
weaponBox(rpg,[.30,-.28,-.55],[.24,.24,.95],[.28,.40,.16],'cylinder');weaponBox(rpg,[.30,-.28,-1.06],[.27,.27,.09],[.67,.64,.23],'cylinder');weaponBox(rpg,[.30,-.28,-1.11],[.19,.19,.02],C.dark,'cylinder');weaponBox(rpg,[.30,-.28,-.08],[.35,.35,.15],[.18,.22,.11],'cylinder');weaponBox(rpg,[.30,-.43,-.33],[.08,.19,.10],C.dark);weaponBox(rpg,[.30,-.09,-.52],[.04,.20,.04],C.dark);weaponBox(rpg,[.30,-.47,-.27],[.13,.14,.15],[.24,.28,.22]);const weaponModels=[rifle,pistol,rpg];
function switchWeapon(n){if(state!=='play'||n===weapon)return;if(weapon<2)magazines[weapon]=ammo;weapon=n;ammo=n===2?rpgAmmo:magazines[n];reload=0;fire=false;cooldown=.25;recoil=0;updateHud();sound(600,.07,.03,true);}
function destroyPart(e,p){if(p.name==='장갑'||p.name==='코어'||p.destroyed)return;if(p.hp>0)return;p.destroyed=true;detach(e,p);broken++;if(e.boss){stageStats.bossParts++;score+=500;cancelBrokenPattern(e);}else{stageStats.parts++;score+=100;}log(p.name+' 파괴');if(p.name==='머리'&&!e.boss)e.hp=0;}
function applyDamage(p,damage){const e=p.e;if(e.dead||p.destroyed)return;e.hp-=damage;p.hp-=damage;destroyPart(e,p);if(e.hp<=0)kill(e);}
function playerExplosion(point,damage,radius){sparks(point,C.amber,30);sound(65,.4,.18,true,point);for(const e of enemies){if(e.dead)continue;const target=[e.p[0],Math.min(1.5,e.scale*1.1),e.p[2]],distance=Math.hypot(...target.map((v,j)=>v-point[j]));if(distance>radius||!lineOfSight(point,target))continue;const amount=damage*(1-.65*distance/radius);e.hp-=amount;for(const p of e.parts)if(p.hp>0){const bp=partBox(e,p).p;if(Math.hypot(...bp.map((v,j)=>v-point[j]))<radius){p.hp-=amount*.65;destroyPart(e,p);}}if(e.hp<=0)kill(e);}const selfDist=Math.hypot(...pos.map((v,j)=>v-point[j]));if(selfDist<radius*.55&&lineOfSight(point,pos))damagePlayer(Math.min(55,damage*.12)*(1-selfDist/radius),point);updateHud();}
function throwGrenade(){if(state!=='play'||grenadeCooldown>0)return;if(grenades<=0){log('수류탄이 없습니다 · 청록 보급품을 획득하세요');return;}grenades--;grenadeCooldown=.65;const dir=norm([-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch)+.35,-Math.cos(yaw)*Math.cos(pitch)]);playerOrdnance.push({kind:'grenade',p:pos.map((v,j)=>v+dir[j]*.25),v:dir.map((v,j)=>v*13+(j===1?3:0)),s:[.2,.25,.2],c:C.blue,life:1.8,damage:300,radius:5.5});updateHud();sound(600,.09,.03,true);}
function punch(){if(state!=='play'||meleeCooldown>0)return;meleeCooldown=.65;punchTimer=.35;const d=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)];const h=trace(pos,d,true,2.4);sound(180,.15,.07,true);if(h.obj?.e){applyDamage(h.obj,65);hitTimer=.15;sparks(pos.map((v,j)=>v+d[j]*h.t),C.amber,8);sound(70,.15,.08);updateHud();}}
function updateOrdnance(dt){punchTimer=Math.max(0,punchTimer-dt);meleeCooldown=Math.max(0,meleeCooldown-dt);grenadeCooldown=Math.max(0,grenadeCooldown-dt);for(let i=playerOrdnance.length-1;i>=0;i--){const b=playerOrdnance[i];b.life-=dt;if(b.kind==='grenade')b.v[1]-=12*dt;const speed=Math.hypot(...b.v),dir=norm(b.v),distance=speed*dt,hit=trace(b.p,dir,b.kind==='rocket',distance+.01);if(hit.obj){const impact=b.p.map((v,j)=>v+dir[j]*Math.max(0,hit.t-.09));if(b.kind==='rocket'){playerExplosion(impact,b.damage,b.radius);playerOrdnance.splice(i,1);continue;}b.p=impact;if(hit.obj.p[1]+hit.obj.s[1]/2<.1){b.v[1]=Math.abs(b.v[1])*.4;b.v[0]*=.65;b.v[2]*=.65;}else{b.v[0]*=-.45;b.v[2]*=-.45;}}else b.p=b.p.map((v,j)=>v+b.v[j]*dt);if(b.life<=0){playerExplosion(b.p,b.damage,b.radius);playerOrdnance.splice(i,1);}}}
function ammoDropChance(kind,d=difficulty){return kind==='rpg'?[.24,.14,.07][d]:[.30,.20,.10][d];}
function dropAmmo(e){for(const kind of ['rpg','grenade'])if(Math.random()<ammoDropChance(kind))pickups.push({kind,p:[e.p[0]+(kind==='rpg'?.65:-.65),.45,e.p[2]],amount:1});}

function waveStart(){wave++;sectorCleared=false;stageStats={kills:[0,0,0],parts:0,bossParts:0,boss:false};const bossStage=mode==='ranked'&&wave%5===0;const count=mode==='ranked'?(bossStage?4:4+wave):3+wave*2,z=-(wave-1)*60;for(let i=0;i<count;i++){const x=-8+(i%5)*4,depth=z-14-Math.floor(i/5)*4;const type=mode==='ranked'?i%3:wave===1?(i%3===0?1:0):wave>=4?(i%3===0?2:1):i%3;spawn(type,x,depth);}if(bossStage)spawnBoss(0,z-20,wave===10);announce(bossStage?'BOSS · '+(wave===10?'OMEGA':'WARDEN'):'구역 '+wave+' · 전방 적 접근',3.5);sound(420,.22,.04);updateHud();}
function dropChance(health,d=difficulty){return [.99,.50,.30][d]*clamp((100-health)/99,0,1);}
function dropHealth(e){if(Math.random()<dropChance(hp))pickups.push({p:[e.p[0],.45,e.p[2]],heal:[50,30,20][difficulty]});}
function collectHealth(){for(let i=pickups.length-1;i>=0;i--){const item=pickups[i],dist=Math.hypot(pos[0]-item.p[0],pos[2]-item.p[2]);const can=item.kind==='rpg'?rpgAmmo<5:item.kind==='grenade'?grenades<4:hp<100;if(can&&dist<1.25){if(!lineOfSight(pos,item.p))continue;if(item.kind==='rpg'){rpgAmmo=Math.min(5,rpgAmmo+1);if(weapon===2)ammo=rpgAmmo;log('RPG 탄약 +1');}else if(item.kind==='grenade'){grenades=Math.min(4,grenades+1);log('수류탄 +1');}else{const amount=Math.min(item.heal,100-hp);hp+=amount;log('회복 키트 +'+Math.round(amount)+' HP');}pickups.splice(i,1);sound(720,.25,.07);updateHud();}}}
function alertAttack(e){threatSource=[...e.p];threatTimer=1.1;robotSound(e,'alert');}
function fireEnemy(e,arms){const origin=[e.p[0],e.scale*1.37,e.p[2]],delta=pos.map((p,i)=>p-origin[i]),dist=Math.hypot(...delta);if(trace(origin,norm(delta),false,dist).obj)return;alertAttack(e);robotSound(e,'attack');if(arms&&!e.type.melee&&dist<25){const direction=norm(delta);bolts.push({p:origin,v:direction.map(v=>v*bulletSpeed()),s:[.15,.15,.15],c:C.red,g:2,life:4,source:[...e.p],damage:e.type.damage*([.65,1,1.3][difficulty])*(arms===1?.65:1)});sound(650,.16,.18,true,e.p);}else if(dist<2){sound(110,.2,.18,true,e.p);damagePlayer(arms?e.type.damage:4,e.p);}}
function advanceSector(){if(enemies.some(e=>!e.dead))return;if(!sectorCleared){sectorCleared=true;score+=1000;if(mode==='ranked')checkpointRank();bolts.length=lasers.length=sweeps.length=scheduled.length=playerOrdnance.length=0;magazines=[30,12];ammo=weapon===2?rpgAmmo:magazines[weapon];reload=0;if(wave===totalStages()){announce('모든 구역 확보',2);intermission=2;}else{gates[wave-1].open=true;announce('구역 확보 · 녹색 통로로 전진',4);}updateHud();}if(wave===totalStages()){intermission-=lastDt;if(intermission<=0)finish(true);}else if(pos[2]<-30-(wave-1)*60-1)waveStart();}
let lastDt=0;
function updateHud(){$('hp').innerHTML=Math.max(0,Math.ceil(hp))+' <em>/ 100</em>';$('hpbar').style.width=hp+'%';$('hpbar').style.background=hp<30?'#f07e55':'#b9f97b';$('ammo').innerHTML=ammo+' <em>/ '+(weapon===2?'5':'∞')+'</em>';$('weaponlabel').textContent=WEAPONS[weapon].name;$('inventory').textContent='1 소총 · 2 권총 · 3 RPG '+rpgAmmo+'/5 · G 수류탄 '+grenades+'/4 · F 주먹';$('gunstatus').textContent=reload>0?'재장전 중…':weapon===2?'탄약 보급품을 주워 사용':weapon===1?'9 MM · SEMI':'5.56 × 45 MM';$('wave').textContent='WAVE '+String(wave).padStart(2,'0');$('remaining').textContent=sectorCleared?'구역 확보 · 다음 구역으로 전진':'적 '+enemies.filter(e=>!e.dead).length+'기 남음';$('sectorlabel').textContent='SECTOR '+String(wave).padStart(2,'0')+' / '+String(totalStages()).padStart(2,'0')+' · '+(mode==='ranked'?'RANKED':'FOUNDRY');$('healinfo').textContent='회복 드롭 '+Math.round(dropChance(hp)*100)+'% · 키트 +'+[50,30,20][difficulty]+' HP';}
async function start(){if(state==='starting')return;stopRobotSounds();sound(60,.01,0);prepareRobotAudio();if(mode==='ranked'){state='starting';lock();$('start').disabled=true;$('start').textContent='랭킹 연결 중…';try{const data=await rankApi('/api/runs',{method:'POST',body:JSON.stringify({version:3})});rankRun=data.id;rankCheckpoints=[];rankStart=performance.now();rankSync=Promise.resolve();rankError='';rankResult=null;difficulty=2;}catch(e){state='menu';document.exitPointerLock?.();$('end').classList.add('hidden');$('menu').classList.remove('hidden');$('rankstatus').textContent='랭킹 서버에 연결할 수 없습니다. 일반 모드는 플레이할 수 있습니다.';$('start').disabled=false;$('start').textContent='작전 시작 ↗';return;}$('start').disabled=false;$('start').textContent='작전 시작 ↗';}else rankRun=null;runEpoch++;score=0;weapon=0;magazines=[30,12];rpgAmmo=grenades=0;punchTimer=meleeCooldown=grenadeCooldown=0;playerOrdnance.length=0;sprintBlend=0;sprinting=false;sprintTouch=false;scheduled.length=lasers.length=sweeps.length=0;fire=aim=false;keys.clear();enemies.length=debris.length=bolts.length=particles.length=pickups.length=0;for(const g of gates)g.open=false;sectorCleared=false;threatTimer=0;threatSource=null;wave=0;hp=100;ammo=30;reload=0;kills=broken=shots=hits=elapsed=0;pos=[0,1.7,19];yaw=pitch=jumpV=0;intermission=cooldown=0;state='play';$('rankform').classList.add('hidden');$('submitstatus').textContent='';for(const id of ['menu','pause','end'])$(id).classList.add('hidden');$('hud').classList.remove('hidden');if(touch)$('touch').classList.remove('hidden');waveStart();lock();sound(350,.2,.03);}
function lock(){if(touch||document.pointerLockElement===canvas)return;try{const p=canvas.requestPointerLock();if(p&&p.catch)p.catch(()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});}catch{lockedFallback=true;}}
function pause(){stopRobotSounds();if(state!=='play')return;state='pause';sprinting=false;sprintTouch=false;fire=aim=false;keys.clear();joystick=[0,0];$('pause').classList.remove('hidden');$('touch').classList.add('hidden');document.exitPointerLock?.();}
function resume(){state='play';$('pause').classList.add('hidden');if(touch)$('touch').classList.remove('hidden');lock();}
function toMenu(){stopRobotSounds();runEpoch++;scheduled.length=lasers.length=sweeps.length=playerOrdnance.length=0;state='menu';fire=false;keys.clear();document.exitPointerLock?.();for(const id of ['pause','end','hud','touch'])$(id).classList.add('hidden');$('menu').classList.remove('hidden');enemies.length=bolts.length=debris.length=particles.length=pickups.length=0;for(const g of gates)g.open=false;wave=1;spawn(0,0,-1);spawn(1,5,-5);spawn(2,11,-10);}
function finish(win){if(state!=='play')return;state='end';stopRobotSounds();sprinting=false;sprintTouch=false;if(mode==='ranked')elapsed=(performance.now()-rankStart)/1000;fire=false;document.exitPointerLock?.();$('end').classList.remove('hidden');$('touch').classList.add('hidden');$('resultlabel').textContent=win?'SECTOR SECURED':'OPERATOR DOWN';$('resulttitle').textContent=win?'구역 확보 완료.':'작전 종료.';$('stats').innerHTML=`${wave} / ${totalStages()} 스테이지 · ${score.toLocaleString()}점 · ${kills}기 제압 · ${broken}개 부위 파괴<br>명중률 ${shots?Math.round(hits/shots*100):0}% · ${Math.floor(elapsed/60)}분 ${Math.floor(elapsed%60)}초`;sound(win?660:100,.5,.06);if(win&&mode==='ranked')prepareRankResult();}
function beginReload(){if(state!=='play'||weapon===2||reload>0||ammo===WEAPONS[weapon].capacity)return;reload=WEAPONS[weapon].reload;fire=false;updateHud();sound(850,.12,.035,true);}
function rayBox(o,d,b){if(b.open)return null;if(b.a){const c=Math.cos(b.a),s=Math.sin(b.a),x=o[0]-b.p[0],z=o[2]-b.p[2];o=[c*x-s*z+b.p[0],o[1],s*x+c*z+b.p[2]];d=[c*d[0]-s*d[2],d[1],s*d[0]+c*d[2]];}let tmin=0,tmax=500;for(let i=0;i<3;i++){let lo=b.p[i]-b.s[i]/2,hi=b.p[i]+b.s[i]/2;if(Math.abs(d[i])<1e-7){if(o[i]<lo||o[i]>hi)return null;}else{let a=(lo-o[i])/d[i],v=(hi-o[i])/d[i];if(a>v)[a,v]=[v,a];tmin=Math.max(tmin,a);tmax=Math.min(tmax,v);if(tmin>tmax)return null;}}return tmin;}
function trace(o,d,includeEnemies=true,max=100){let closest=max,obj=null;for(const b of world){if(!b.blocksShots||b.open)continue;const t=rayBox(o,d,b);if(t!==null&&t<closest){closest=t;obj=b;}}if(includeEnemies)for(const e of enemies)if(!e.dead)for(const p of e.parts)if(p.hp>0){const t=rayBox(o,d,partBox(e,p));if(t!==null&&t<closest){closest=t;obj=p;}}return {t:closest,obj};}
function sparks(p,color,n=7){for(let i=0;i<n;i++)particles.push({p:[...p],s:[.045,.045,.045],c:color,g:1,v:[(Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5],life:.25+Math.random()*.3});}
function detach(e,p){const b=partBox(e,p);debris.push({...b,p:[...b.p],v:[(Math.random()-.5)*4,2.8,(Math.random()-.5)*4],life:8,a:Math.random()*6});p.hp=0;}
function kill(e){if(e.dead)return;e.dead=true;stopRobotSounds(e);robotSound(e,'death');kills++;if(e.boss){stageStats.boss=true;score+=wave===10?40000:20000;}else{stageStats.kills[e.typeIndex]++;score+=e.type.hp*10;}for(const p of e.parts)if(p.hp>0)detach(e,p);sparks([e.p[0],e.scale,e.p[2]],C.amber,15);dropHealth(e);dropAmmo(e);log(e.type.name+' 제압 +'+(e.boss?(wave===10?40000:20000):e.type.hp*10));updateHud();}
function shoot(){if(state!=='play'||sprinting||sprintBlend>.15||cooldown>0||reload>0)return;if(ammo===0){if(weapon===2){log('RPG 탄약이 없습니다 · 주황 보급품을 획득하세요');fire=false;}else beginReload();return;}ammo--;if(weapon===2)rpgAmmo=ammo;else magazines[weapon]=ammo;shots++;cooldown=WEAPONS[weapon].delay;recoil=weapon===1?.1:.07;if(weapon===2){const d=norm([-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)]);playerOrdnance.push({kind:'rocket',p:[...pos],v:d.map(v=>v*42),s:[.16,.16,.6],c:C.amber,life:4,damage:650,radius:6});sound(140,.3,.17,true);fire=false;updateHud();return;}if(weapon===1)fire=false;let spread=aim?.0018:.009;const dir=norm([-Math.sin(yaw)*Math.cos(pitch)+(Math.random()-.5)*spread,Math.sin(pitch)+(Math.random()-.5)*spread,-Math.cos(yaw)*Math.cos(pitch)]);let hit=trace(pos,dir),impact=pos.map((v,i)=>v+dir[i]*hit.t);const muzzle=[pos[0]+Math.cos(yaw)*.22-Math.sin(yaw)*.6,pos[1]-.15,pos[2]-Math.sin(yaw)*.22-Math.cos(yaw)*.6];const muzzleDelta=muzzle.map((v,i)=>v-pos[i]);const nearWall=trace(pos,norm(muzzleDelta),false,Math.hypot(...muzzleDelta));if(nearWall.obj){hit=nearWall;impact=pos.map((v,i)=>v+norm(muzzleDelta)[i]*hit.t);}else{const toImpact=impact.map((v,i)=>v-muzzle[i]),gunHit=trace(muzzle,norm(toImpact),true,Math.hypot(...toImpact)+.02);if(gunHit.obj){hit=gunHit;impact=muzzle.map((v,i)=>v+norm(toImpact)[i]*hit.t);}}sparks(impact,hit.obj?.e?C.amber:C.metal,hit.obj?6:0);if(hit.obj?.e){hits++;hitTimer=.12;const p=hit.obj,damage=WEAPONS[weapon].damage*(p.name==='머리'?1.3:1);applyDamage(p,damage);sound(920,.06,.028);}pitch=clamp(pitch+.003,-1.35,1.35);sound(1800,.10,.12,true);updateHud();}
function canMove(x,z,r=.38){if(Math.abs(x)>21.4-r||z>29.4-r||z<(-60*(totalStages()-1)-29.4+r))return false;for(const b of obstacles){if(b.open||b.s[1]<.4||b.p[1]-b.s[1]/2>3)continue;if(Math.abs(x-b.p[0])<b.s[0]/2+r&&Math.abs(z-b.p[2])<b.s[2]/2+r)return false;}return true;}
function move(p,dx,dz,r){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.18));for(let i=0;i<steps;i++){if(canMove(p[0]+dx/steps,p[2],r))p[0]+=dx/steps;if(canMove(p[0],p[2]+dz/steps,r))p[2]+=dz/steps;}}
function damagePlayer(amount,source=null){if(state!=='play')return;if(source){threatSource=[...source];threatTimer=1.4;}hp=Math.max(0,hp-amount);damageTimer=.45;sound(70,.16,.065);if(hp<=0)finish(false);updateHud();}
function update(dt){if(state!=='play')return;lastDt=dt;elapsed=mode==='ranked'?(performance.now()-rankStart)/1000:elapsed+dt;collectHealth();threatTimer=Math.max(0,threatTimer-dt);if(threatTimer>0&&threatSource){const dx=threatSource[0]-pos[0],dz=threatSource[2]-pos[2],right=Math.cos(yaw)*dx-Math.sin(yaw)*dz,forward=-Math.sin(yaw)*dx-Math.cos(yaw)*dz;const bearing=Math.atan2(right,forward);$('threat').style.opacity='1';$('threatarrow').style.transform='rotate('+bearing+'rad)';$('threattext').textContent=(forward<0?'후방':Math.abs(right)>Math.abs(forward)?(right>0?'오른쪽':'왼쪽'):'전방')+' 공격 · '+Math.round(Math.hypot(dx,dz))+'m';}else $('threat').style.opacity='0';if(sectorCleared&&wave<totalStages()){const distance=Math.max(0,Math.round(pos[2]-(-31-(wave-1)*60)));$('objective').textContent='↓ 다음 구역 · '+distance+'m';}else $('objective').textContent='전방 적을 모두 제압하세요';feet+=dt*5;cooldown=Math.max(0,cooldown-dt);recoil=Math.max(0,recoil-dt*.5);hitTimer=Math.max(0,hitTimer-dt);damageTimer=Math.max(0,damageTimer-dt);noticeTimer-=dt;feedTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';if(feedTimer<=0)$('feed').textContent='';$('hit').style.opacity=hitTimer>0?1:0;$('damage').style.opacity=damageTimer;let fw=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joystick[1],rt=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joystick[0],l=Math.max(1,Math.hypot(fw,rt));sprinting=(keys.has('ShiftLeft')||keys.has('ShiftRight')||sprintTouch)&&Math.hypot(fw,rt)>.1;if(sprinting)aim=false;sprintBlend+=(Number(sprinting)-sprintBlend)*Math.min(1,dt*10);const speed=sprinting?SPRINT_SPEED:5.8*(aim?.57:1);stepTimer-=dt;if(sprinting&&stepTimer<=0){sound(85,.10,.035,true);stepTimer=.17;}$('sprintstatus').textContent=sprinting?'SPRINT · 32 m/s':'SHIFT · 질주';$('runscore').textContent=score.toLocaleString()+' PT · '+formatTime(elapsed*1000);move(pos,(-Math.sin(yaw)*fw+Math.cos(yaw)*rt)*speed*dt/l,(-Math.cos(yaw)*fw-Math.sin(yaw)*rt)*speed*dt/l,.35);if(pos[1]>1.7||jumpV>0){jumpV-=15*dt;pos[1]+=jumpV*dt;if(pos[1]<1.7){pos[1]=1.7;jumpV=0;}}if(reload>0){reload-=dt;if(reload<=0){reload=0;ammo=WEAPONS[weapon].capacity;if(weapon<2)magazines[weapon]=ammo;sound(500,.07,.025,true);updateHud();}}updateOrdnance(dt);if(fire)shoot();
for(const e of enemies){if(e.dead)continue;if(e.boss){updateBoss(e,dt);continue;}e.age+=dt;let dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],dist=Math.hypot(dx,dz),legs=e.parts.filter(p=>p.hp>0&&p.name.includes('다리')).length,arms=e.parts.filter(p=>p.hp>0&&p.name.includes('팔')).length;const line=trace([e.p[0],e.scale*1.3,e.p[2]],norm([dx,pos[1]-e.scale*1.3,dz]),false,dist);e.angle=Math.atan2(dx,dz);const blocked=!!line.obj;let sp=e.type.speed*([.75,1,1.18][difficulty])*(legs===2?1:legs===1?.48:.12);let reach=e.type.melee?1.1:arms?8:1.4;if(dist>reach||blocked){let nx=dx/(dist||1),nz=dz/(dist||1),mx=nx*sp*dt,mz=nz*sp*dt;const ox=e.p[0],oz=e.p[2];move(e.p,mx,mz,.45*e.scale);if(Math.hypot(e.p[0]-ox,e.p[2]-oz)<sp*dt*.3){let side=Math.sin(e.phase)>0?1:-1;move(e.p,-nz*sp*dt*side,nx*sp*dt*side,.45*e.scale);}}
// Separate enemies, without pushing them into cover.
for(const other of enemies){if(other===e||other.dead)continue;let sx=e.p[0]-other.p[0],sz=e.p[2]-other.p[2],sl=Math.hypot(sx,sz),minimum=.45*(e.scale+other.scale);if(sl>0&&sl<minimum)move(e.p,sx/sl*dt,sz/sl*dt,.45*e.scale);}
e.timer-=dt;if(e.warning>0){e.warning-=dt;if(e.warning<=0)fireEnemy(e,arms);}else if(e.age>2.5&&e.timer<=0&&!blocked&&dist<(arms&&!e.type.melee?25:1.8)){e.timer=e.type.rate*(arms===1?1.8:1)*([1.3,1,.8][difficulty])+.55;e.warning=.55;alertAttack(e);}}
updateBossAttacks(dt);for(let i=bolts.length-1;i>=0;i--){const b=bolts[i];if(b.kind==='missile'){b.age=(b.age||0)+dt;const target=b.age<.65?[pos[0],6,pos[2]]:pos;const desired=norm(target.map((v,j)=>v-b.p[j]));const old=norm(b.v),turn=Math.min(1,dt*2.4);b.v=norm(old.map((v,j)=>v*(1-turn)+desired[j]*turn)).map(v=>v*22);}const prev=[...b.p],speed=Math.hypot(...b.v),d=b.v.map(v=>v/speed),travel=speed*dt;const wall=trace(prev,d,false,travel+.001);const body=box([pos[0],pos[1]-.45,pos[2]],[.7,1.25,.7],C.dark),playerT=rayBox(prev,d,body);if(playerT!==null&&playerT<=travel&&(!wall.obj||playerT<wall.t)){if(b.kind==='missile')explode(b,prev.map((v,j)=>v+d[j]*playerT));else damagePlayer(b.damage,b.source);bolts.splice(i,1);continue;}if(wall.obj){const impact=prev.map((v,j)=>v+d[j]*wall.t);if(b.kind==='missile')explode(b,impact);sparks(impact,C.amber,4);bolts.splice(i,1);continue;}b.p=b.p.map((v,j)=>v+b.v[j]*dt);b.life-=dt;if(b.life<=0){if(b.kind==='missile')explode(b,b.p);bolts.splice(i,1);}}
for(const arr of [particles,debris])for(let i=arr.length-1;i>=0;i--){const b=arr[i];b.life-=dt;b.v[1]-=9*dt;for(let j=0;j<3;j++)b.p[j]+=b.v[j]*dt;if(b.p[1]<b.s[1]/2){b.p[1]=b.s[1]/2;b.v[1]=Math.abs(b.v[1])*.18;b.v[0]*=.88;b.v[2]*=.88;}if(arr===debris)b.a+=dt*b.v[0];if(b.life<=0)arr.splice(i,1);}
updateRobotAudio(dt);advanceSector();
const d=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],t=trace(pos,d);if(t.obj?.e){const e=t.obj.e,p=t.obj;$('target').textContent=e.type.name+' · '+p.name+' '+(p.name==='코어'?Math.ceil(e.hp):Math.ceil(p.hp))+' HP';}else $('target').textContent='';
}
// Armor plates and joints follow the destructible part, so every detail detaches with it.
function robotDetail(b,offset,size,color,kind='box',glow=0){const c=Math.cos(b.a),s=Math.sin(b.a),p=[b.p[0]+c*offset[0]+s*offset[2],b.p[1]+offset[1],b.p[2]-s*offset[0]+c*offset[2]];draw({...box(p,size,color,b.a,glow),kind});}
function drawRobot(e,time){if(e.boss){drawBoss(e,time);return;}const S=e.scale,accent=e.type.accent,white=[.86,.91,.85],joint=[.09,.12,.15];for(const part of e.parts)if(part.hp>0){let b=partBox(e,part);const damaged=part.hp<part.max*.5&&part.name!=='코어';const color=damaged?e.type.c.map(x=>x*.65):e.type.c;const detail=(off,size,c,kind='box',g=0)=>robotDetail(b,off.map(x=>x*S),size.map(x=>x*S),c,kind,g);
 if(part.name==='머리'){draw({...b,c:color});detail([0,.25,0],[.29,.12,.32],accent);detail([0,-.01,.205],[.28,.39,.065],joint);detail([0,0,.247],[.23,.23,.035],[.38,.025,.035],'cylinder');detail([0,0,.273],[.15,.15,.035],[1,.005,.018],'cylinder',2.2);detail([0,0,.296],[.055,.09,.02],[1,.12,.16],'cylinder',1.5);detail([0,-.25,.2],[.24,.08,.06],white);
 }else if(part.name==='코어'){draw({...b,c:joint});detail([-.23,.13,.02],[.23,.40,.44],color);detail([.23,.13,.02],[.23,.40,.44],color);detail([0,0,.245],[.44,.44,.11],accent,'cylinder');detail([0,0,.31],[.31,.31,.035],joint,'cylinder');detail([0,0,.34],[.13,.13,.04],C.amber,'cylinder',.6);detail([0,-.25,.05],[.61,.15,.43],color);detail([0,.34,0],[.15,.12,.17],joint);
 }else if(part.name.includes('팔')){draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.55)),c:joint});detail([0,.26,0],[.37,.29,.36],color);detail([0,.29,.20],[.25,.14,.07],accent);detail([0,-.02,.02],[.25,.23,.33],white,'cylinder');detail([0,-.27,0],[.33,.25,.34],color);detail([0,-.28,.21],[.14,.14,.12],joint,'cylinder');if(e.warning>0)detail([0,-.28,.30],[.15,.15,.04],C.red,'cylinder',2.5);
 }else {draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.6)),c:joint});detail([0,.20,0],[.26,.27,.30],color);detail([0,-.025,.08],[.25,.22,.22],accent,'cylinder');detail([0,-.23,0],[.27,.28,.30],color);detail([0,-.34,.04],[.27,.12,.31],white);}}
 const top=2.57*S;draw(box([e.p[0],top,e.p[2]],[.85*S,.05,.035],C.dark));draw(box([e.p[0]-(1-e.hp/e.max)*.425*S,top,e.p[2]+.025],[.85*S*clamp(e.hp/e.max,0,1),.055,.035],e.type.c,0,.8));}
function render(time){let eye=pos,y=yaw,p=pitch;if(state==='menu'){eye=[17,6.1,22];y=.43+Math.sin(time*.00008)*.10;p=-.13;}
const fov=state==='play'&&aim?.70:1.18+sprintBlend*.22;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.045,.085,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,multiply(projection(fov),view(eye,y,p)));gl.uniform3fv(U.Eye,eye);gl.uniform1f(U.Fog,.020);for(const b of world)if(Math.abs(b.p[2]-eye[2])<85)draw(b);
for(const e of enemies)if(!e.dead){if(state==='menu')e.angle=Math.atan2(eye[0]-e.p[0],eye[2]-e.p[2]);drawRobot(e,time);}for(const item of pickups){const h=.55+Math.sin(time*.003)*.12,c=item.kind==='rpg'?C.amber:item.kind==='grenade'?C.blue:C.lime;draw(box([item.p[0],h,item.p[2]],[.65,.42,.50],c.map(v=>v*.55),time*.001));if(item.kind){draw({...box([item.p[0],h+.35,item.p[2]],[item.kind==='rpg'?.15:.24,.15,item.kind==='rpg'?.75:.25],c,0,1),kind:'cylinder'});}else{draw(box([item.p[0],h+.26,item.p[2]],[.13,.10,.44],c,0,1.2));draw(box([item.p[0],h+.26,item.p[2]],[.44,.10,.13],c,0,1.2));}draw(box([item.p[0],.03,item.p[2]],[.9,.035,.9],c.map(v=>v*.5),0,.3));}
if(sectorCleared&&wave<totalStages()){const z=-30-(wave-1)*60;for(const x of [-3.9,3.9])draw(box([x,2,z],[.12,4,.12],C.lime,0,1.5));}
drawBossAttacks(time);for(const arr of [debris,bolts,particles,playerOrdnance])for(const b of arr)draw(b);
if(state!=='menu'){gl.clear(gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,projection(1.0));gl.uniform3fv(U.Eye,[0,0,0]);gl.uniform1f(U.Fog,0);const moving=state==='play'&&(keys.has('KeyW')||keys.has('KeyA')||keys.has('KeyS')||keys.has('KeyD')||Math.hypot(...joystick)>.1);let bob=moving?Math.sin(time*.013)*.008:Math.sin(time*.002)*.002;let reloadDrop=reload>0?Math.sin((WEAPONS[weapon].reload-reload)/Math.max(.01,WEAPONS[weapon].reload)*Math.PI)*.35:0;for(const b of weaponModels[weapon]){const t=-.58*sprintBlend,gy=b.p[1]+(aim?.065:0),gz=b.p[2]+recoil;draw({...b,tilt:t,p:[b.p[0]-(aim?.24:0)+Math.sin(time*.024)*.045*sprintBlend,gy*Math.cos(t)-gz*Math.sin(t)+bob-reloadDrop-.12*sprintBlend+Math.sin(time*.032)*.04*sprintBlend,gy*Math.sin(t)+gz*Math.cos(t)+.12*sprintBlend]});}if(punchTimer>0){draw(box([-.20,-.12,-.40-Math.sin(punchTimer/.35*Math.PI)*.35],[.20,.20,.24],[.25,.3,.22]));}if(recoil>.046&&!sprinting){draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.085],[.085,.085,.19],C.amber,time*.1,2));draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.1],[.14,.025,.14],C.lime,0,3));}}
}
function resize(){let d=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);}window.addEventListener('resize',resize);resize();
$('start').onclick=start;$('retry').onclick=start;$('resume').onclick=resume;$('quit').onclick=toMenu;$('back').onclick=toMenu;$('sensitivity').oninput=e=>sensitivity=Number(e.target.value);document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{chosenDifficulty=difficulty=Number(b.dataset.d);document.querySelectorAll('[data-d]').forEach(x=>x.classList.toggle('active',x===b));});
window.addEventListener('keydown',e=>{if(e.target?.tagName==='INPUT')return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&state==='play'){pause();return;}if(state!=='play')return;keys.add(e.code);if(e.code==='KeyR')beginReload();if(!e.repeat&&e.code==='KeyF')punch();if(!e.repeat&&e.code==='KeyG')throwGrenade();if(['Digit1','Digit2','Digit3'].includes(e.code))switchWeapon(Number(e.code.slice(-1))-1);if(e.code==='Space'&&pos[1]<=1.71)jumpV=6;});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(state==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='play'&&!lockedFallback&&!touch)pause();});document.addEventListener('pointerlockerror',()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('mousedown',e=>{if(state!=='play'||e.target!==canvas)return;if(!touch&&document.pointerLockElement!==canvas)lock();if(e.button===0)fire=true;if(e.button===2)aim=true;});window.addEventListener('mouseup',e=>{if(e.button===0)fire=false;if(e.button===2)aim=false;});window.addEventListener('mousemove',e=>{if(state==='play'&&(document.pointerLockElement===canvas||lockedFallback&&e.buttons)){yaw-=e.movementX*.002*sensitivity*(aim?.6:1);pitch=clamp(pitch-e.movementY*.002*sensitivity*(aim?.6:1),-1.35,1.35);}});
canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='play'){lookPointer=e.pointerId;lastLook=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(e.pointerId===lookPointer){yaw-=(e.clientX-lastLook[0])*.005;pitch=clamp(pitch-(e.clientY-lastLook[1])*.005,-1.35,1.35);lastLook=[e.clientX,e.clientY];}});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{if(e.pointerId===lookPointer)lookPointer=null;});
const stick=$('stick');function stickMove(e){const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38,l=Math.max(1,Math.hypot(x,y));joystick=[x/l,y/l];stick.firstElementChild.style.transform=`translate(${joystick[0]*28}px,${joystick[1]*28}px)`;}let stickId=null;stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===stickId)stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{stickId=null;joystick=[0,0];stick.firstElementChild.style.transform='';};$('touchfire').onpointerdown=e=>{e.preventDefault();fire=true;$('touchfire').setPointerCapture(e.pointerId);};$('touchfire').onpointerup=$('touchfire').onpointercancel=()=>fire=false;$('touchreload').onclick=beginReload;$('touchpause').onclick=pause;$('touchswap').onclick=()=>switchWeapon((weapon+1)%3);$('touchgrenade').onclick=throwGrenade;$('touchpunch').onclick=punch;$('touchsprint').onpointerdown=e=>{e.preventDefault();sprintTouch=true;$('touchsprint').setPointerCapture(e.pointerId);};$('touchsprint').onpointerup=$('touchsprint').onpointercancel=()=>sprintTouch=false;
function activeParts(e,fragment){return e.parts.filter(p=>p.hp>0&&p.name.includes(fragment));}
function spawnBoss(x,z,final){const e={boss:true,final,type:{name:final?'OMEGA':'WARDEN',c:final?[.8,.14,.36]:[.96,.57,.1],accent:[.1,.75,.95],hp:final?4800:3200},p:[x,0,z],parts:[],hp:final?4800:3200,max:final?4800:3200,scale:final?2.6:2.2,angle:0,age:0,phase:0,dead:false,timer:3,pattern:0,warning:0,attackName:'접근 중',windup:null};
part(e,'장갑',[0,1.2,0],[.94,1.05,.60],1e9);
part(e,'가슴 코어',[0,1.55,.36],[.44,.48,.18],final?800:550);
for(const [side,x]of [['왼',-.8],['오른',.8]]){part(e,side+'어깨',[x,2.05,0],[.55,.55,.58],final?400:300);part(e,side+'팔',[x*1.1,1.19,0],[.42,1.1,.43],final?450:320);part(e,side+'다리',[x*.48,.43,0],[.40,.83,.48],final?500:350);}
enemies.push(e);return e;}
function cancelBrokenPattern(e){if(!activeParts(e,'가슴 코어').length){stopRobotSounds(e,'laser');for(let i=lasers.length-1;i>=0;i--)if(lasers[i].owner===e)lasers.splice(i,1);if(e.windup===2){e.windup=null;e.warning=0;e.timer=.6;e.attackName='코어 파괴 · 레이저 불능';}}}
const PATTERNS=['회전 휩쓸기','유도탄 난사','광역 레이저','탄환 3연사','칼날 부채꼴'];
function patternAvailable(e,p){return p===0||p===1&&activeParts(e,'어깨').length||p===2&&activeParts(e,'가슴 코어').length||p===3&&activeParts(e,'팔').length||p===4&&activeParts(e,'다리').length;}
function updateBoss(e,dt){e.age+=dt;const dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],distance=Math.hypot(dx,dz);if(!sweeps.some(a=>a.owner===e))e.angle=Math.atan2(dx,dz);const legs=activeParts(e,'다리').length;const speed=(e.final?3.7:3)*(legs===2?1:legs===1?.45:.08);if(distance>6&&e.windup===null&&!lasers.some(a=>a.owner===e))move(e.p,dx/(distance||1)*speed*dt,dz/(distance||1)*speed*dt,.65*e.scale);
if(e.windup!==null){e.warning-=dt;if(e.warning<=0){const p=e.windup;e.windup=null;if(patternAvailable(e,p))executeBossPattern(e,p);e.timer=e.final?2.0:2.8;}}else{e.timer-=dt;if(e.timer<=0&&!lasers.some(a=>a.owner===e)&&!sweeps.some(a=>a.owner===e)){let p=e.pattern%5;for(let i=0;i<5&&!patternAvailable(e,p);i++)p=(p+1)%5;e.pattern=p+1;e.windup=p;e.warning=p===2?1.5:1.15;e.attackName=PATTERNS[p];announce(e.type.name+' · '+PATTERNS[p],1.3);alertAttack(e);}}
$('boss').classList.remove('hidden');$('bossname').textContent=e.type.name+' · '+e.attackName;$('bosshp').style.width=(e.hp/e.max*100)+'%';$('bossparts').textContent=e.parts.filter(p=>p.name!=='장갑').map(p=>p.name+(p.hp>0?' '+Math.ceil(p.hp):' ×')).join(' / ');}
function queueBoss(owner,delay,fn){scheduled.push({owner,delay,fn});}
function bossProjectile(e,origin,direction,speed,damage,kind='bolt'){bolts.push({p:[...origin],v:norm(direction).map(v=>v*speed),s:kind==='blade'?[.7,.11,.14]:kind==='missile'?[.23,.23,.65]:[.16,.16,.22],c:kind==='blade'?C.blue:kind==='missile'?C.amber:C.red,g:1.5,life:kind==='missile'?6:4,kind,age:0,damage,source:[...e.p]});}
function executeBossPattern(e,p){if(!patternAvailable(e,p))return;robotSound(e,['sweep','missiles','laser','burst','blades'][p]);
if(p===0){sweeps.push({owner:e,life:2.2,hitTimer:0});sound(110,.4,.15,true,e.p);}
if(p===1){for(const shoulder of activeParts(e,'어깨'))for(let i=0;i<4;i++)queueBoss(e,i*.16+(shoulder.local[0]>0?.08:0),()=>{if(shoulder.hp<=0)return;const o=partBox(e,shoulder).p;o[1]+=.7;bossProjectile(e,o,[Math.sin(e.angle)*.5,1,Math.cos(e.angle)*.5],22,24,'missile');sound(500,.15,.12,true,o);});}
if(p===2)lasers.push({owner:e,life:3,age:0,angle:e.angle-.5,tick:0});
if(p===3){const n=activeParts(e,'팔').length===2?3:activeParts(e,'팔').length;for(let i=0;i<n;i++)queueBoss(e,i*.2,()=>{const arms=activeParts(e,'팔');if(!arms.length||i>=(arms.length===2?3:arms.length))return;const o=partBox(e,arms[i%arms.length]).p;bossProjectile(e,o,pos.map((v,j)=>v-o[j]),28,18);sound(600,.12,.17,true,o);});}
if(p===4){for(const leg of activeParts(e,'다리'))for(let i=-2;i<=2;i++){const o=partBox(e,leg).p;o[1]=.95;const a=e.angle+i*.18;bossProjectile(e,o,[Math.sin(a),0,Math.cos(a)],29,16,'blade');}sound(1000,.22,.1,true,e.p);}}
function beamData(l){const e=l.owner,core=e.parts.find(p=>p.name==='가슴 코어');const origin=partBox(e,core).p;const a=l.angle+l.age*.35,dir=norm([Math.sin(a),-.065,Math.cos(a)]),hit=trace(origin,dir,false,42);return {origin,dir,length:hit.t};}
function lineOfSight(a,b){const d=b.map((v,j)=>v-a[j]),distance=Math.hypot(...d);return !trace(a,norm(d),false,Math.max(0,distance-.03)).obj;}
function explode(b,point){sparks(point,C.amber,20);const d=Math.hypot(pos[0]-point[0],pos[1]-point[1],pos[2]-point[2]);if(d<3.2&&lineOfSight(point,pos))damagePlayer(b.damage*(1-d/4.5),b.source);sound(70,.35,.13,true,point);}
function updateBossAttacks(dt){$('boss').classList.toggle('hidden',!enemies.some(e=>e.boss&&!e.dead));for(let i=scheduled.length-1;i>=0;i--){const a=scheduled[i];a.delay-=dt;if(a.owner.dead){scheduled.splice(i,1);continue;}if(a.delay<=0){a.fn();scheduled.splice(i,1);}}
for(let i=sweeps.length-1;i>=0;i--){const a=sweeps[i],e=a.owner;if(e.dead){sweeps.splice(i,1);continue;}a.life-=dt;a.hitTimer-=dt;e.angle+=dt*7;const radius=3+activeParts(e,'팔').length*3,dist=Math.hypot(pos[0]-e.p[0],pos[2]-e.p[2]);if(dist<radius&&a.hitTimer<=0&&lineOfSight([e.p[0],1.2,e.p[2]],pos)){damagePlayer(25,e.p);a.hitTimer=.65;}if(a.life<=0)sweeps.splice(i,1);}
for(let i=lasers.length-1;i>=0;i--){const l=lasers[i];if(l.owner.dead||!activeParts(l.owner,'가슴 코어').length){lasers.splice(i,1);continue;}l.life-=dt;l.age+=dt;l.tick-=dt;const {origin,dir,length}=beamData(l),delta=pos.map((v,j)=>v-origin[j]),along=dot(delta,dir),off=Math.hypot(...delta.map((v,j)=>v-dir[j]*along));if(along>0&&along<length&&off<1.45&&l.tick<=0&&lineOfSight(origin,pos)){damagePlayer(7,l.owner.p);l.tick=.18;}if(l.tick<=0){sound(135,.16,.04,false,l.owner.p);l.tick=.18;}if(l.life<=0)lasers.splice(i,1);}}
function drawBoss(e,time){const S=e.scale;for(const p of e.parts)if(p.hp>0){const b=partBox(e,p);draw({...b,c:p.name==='장갑'?[.13,.15,.18]:e.type.c});if(p.name==='가슴 코어')robotDetail(b,[0,0,.12*S],[.32*S,.35*S,.06*S],C.red,'cylinder',1.6);if(p.name.includes('어깨'))for(let i=0;i<4;i++)robotDetail(b,[(i%2-.5)*.2*S,(Math.floor(i/2)-.5)*.2*S,.31*S],[.12*S,.12*S,.07*S],C.dark,'cylinder');if(p.name.includes('다리'))robotDetail(b,[0,-.12*S,.26*S],[.28*S,.14*S,.035*S],C.blue);}
const head=box([e.p[0],2.62*S,e.p[2]],[.4*S,.65*S,.4*S],e.type.c,e.angle);draw(head);robotDetail(head,[0,0,.22*S],[.17*S,.17*S,.05*S],C.red,'cylinder',2.2);if(e.windup!==null)drawRing(e.p,e.windup===0?3+activeParts(e,'팔').length*3:2.8,[1,.17,.05],time);}
function drawRing(p,r,c,time){for(let i=0;i<40;i++){const a=i/40*Math.PI*2;draw(box([p[0]+Math.sin(a)*r,.055,p[2]+Math.cos(a)*r],[.28,.055,.28],c,a,.7+Math.sin(time*.015)*.25));}}
function drawBossAttacks(time){for(const a of sweeps)if(!a.owner.dead){const e=a.owner,r=3+activeParts(e,'팔').length*3;drawRing(e.p,r,C.amber,time);for(let i=0;i<8;i++){const a=e.angle+i*.16;draw(box([e.p[0]+Math.sin(a)*r*.7,1.2,e.p[2]+Math.cos(a)*r*.7],[.24,.20,r*.55],C.amber,a,1));}}for(const l of lasers){const {origin,dir,length}=beamData(l);for(let t=0;t<length;t+=.8)draw(box(origin.map((v,j)=>v+dir[j]*t),[1.7,1.3,.8],[1,.025,.065],l.angle+l.age*.35,1.6));}}
function formatTime(ms){const total=Math.floor(ms/1000);return Math.floor(total/60)+':'+String(total%60).padStart(2,'0')+'.'+Math.floor(ms%1000/100);}
async function rankApi(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers},signal:AbortSignal.timeout(10000)});let data;try{data=await response.json();}catch{throw Error('랭킹 서버가 필요합니다.');}if(!response.ok)throw Error(data.error||'기록을 처리하지 못했습니다.');return data;}
function checkpointRank(){rankCheckpoints.push({stage:wave,...stageStats,kills:[...stageStats.kills],synced:false});const id=rankRun,epoch=runEpoch,entries=rankCheckpoints;rankSync=rankSync.catch(()=>{}).then(()=>syncRank(id,epoch,entries));rankSync.catch(()=>{});}
async function syncRank(id=rankRun,epoch=runEpoch,entries=rankCheckpoints){if(epoch!==runEpoch)return;for(const entry of entries){if(entry.synced)continue;const {synced,...payload}=entry;await rankApi('/api/runs/'+id+'/stage',{method:'POST',body:JSON.stringify(payload)});if(epoch!==runEpoch)return;entry.synced=true;}}
async function prepareRankResult(){const epoch=runEpoch,id=rankRun,entries=rankCheckpoints;$('rankform').classList.remove('hidden');$('submitrank').disabled=true;$('submitstatus').textContent='클리어 기록 확인 중…';try{await rankSync.catch(()=>{});await syncRank(id,epoch,entries);if(epoch!==runEpoch)return;const r=await rankApi('/api/runs/'+id);if(epoch!==runEpoch)return;rankResult=r;$('stats').textContent=r.score.toLocaleString()+'점 · '+formatTime(r.elapsedMs)+' · 10 / 10 클리어';$('submitstatus').textContent='이름을 입력해 랭킹에 남기세요.';$('submitrank').disabled=false;}catch(e){if(epoch===runEpoch)$('submitstatus').textContent='기록 동기화 실패: '+e.message+' 서버 연결을 확인하세요.';}}
async function showLeaderboard(){if(state==='play')pause();$('leaderboard').classList.remove('hidden');$('boardstatus').textContent='기록 불러오는 중…';$('boardrows').replaceChildren();try{const r=await rankApi('/api/leaderboard');$('boardstatus').textContent=r.rows.length?'점수 높은 순 · 동점은 빠른 클리어 순':'아직 등록된 기록이 없습니다.';r.rows.forEach((row,i)=>{const tr=document.createElement('tr');for(const text of [String(i+1),row.name,row.score.toLocaleString(),formatTime(row.elapsedMs)]){const td=document.createElement('td');td.textContent=text;tr.appendChild(td);}$('boardrows').appendChild(tr);});}catch(e){$('boardstatus').textContent='랭킹을 불러오지 못했습니다. '+e.message;}}
$('retrysync').onclick=prepareRankResult;
$('rankform').onsubmit=async event=>{event.preventDefault();if(!rankResult)return;const name=$('playername').value.trim();if(!name||[...name].length>16){$('submitstatus').textContent='이름을 1~16자로 입력하세요.';return;}$('submitrank').disabled=true;try{await rankApi('/api/leaderboard',{method:'POST',body:JSON.stringify({id:rankRun,name})});$('submitstatus').textContent='등록 완료';await showLeaderboard();}catch(e){$('submitstatus').textContent=e.message;$('submitrank').disabled=false;}};
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.mode;difficulty=mode==='ranked'?2:chosenDifficulty;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-d]').forEach(b=>b.disabled=mode==='ranked');$('modedesc').textContent=mode==='ranked'?'10 스테이지 · 5/10 보스 · 고정 극한 난이도 · 클리어 기록 등록':'5 스테이지 · 난이도 선택';$('rankstatus').textContent='';});$('openboard').onclick=showLeaderboard;$('closeboard').onclick=()=>$('leaderboard').classList.add('hidden');$('refreshboard').onclick=showLeaderboard;

let last=performance.now();function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;update(dt);render(t);requestAnimationFrame(frame);}toMenu();requestAnimationFrame(frame);
})();
