'use strict';
(()=>{
const $=id=>document.getElementById(id), canvas=$('game');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl){$('error').classList.remove('hidden');return;}
const vs=`attribute vec3 aPos;attribute vec3 aNormal;uniform mat4 uVP;uniform vec3 uPos;uniform vec3 uSize;uniform float uAngle;uniform float uTilt;varying vec3 vNormal;varying vec3 vWorld;void main(){float c=cos(uAngle),s=sin(uAngle);mat3 r=mat3(c,0.,-s,0.,1.,0.,s,0.,c);float ct=cos(uTilt),st=sin(uTilt);mat3 rx=mat3(1.,0.,0.,0.,ct,st,0.,-st,ct);r=r*rx;vWorld=r*(aPos*uSize)+uPos;vNormal=r*aNormal;gl_Position=uVP*vec4(vWorld,1.);}`;
const fs=`precision mediump float;uniform vec3 uColor;uniform vec3 uEye;uniform float uGlow;uniform float uFog;uniform float uAlpha;varying vec3 vNormal;varying vec3 vWorld;void main(){float light=.35+max(dot(normalize(vNormal),normalize(vec3(-.5,.9,.3))),0.)*.75;vec3 col=uColor*(light+uGlow);float fog=1.-exp(-distance(vWorld,uEye)*uFog);gl_FragColor=vec4(mix(col,vec3(.045,.085,.09),fog),uAlpha);}`;
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Renderer link');gl.useProgram(program);
const U={};for(const n of ['VP','Pos','Size','Angle','Tilt','Color','Eye','Glow','Fog','Alpha'])U[n]=gl.getUniformLocation(program,'u'+n);
const verts=[];const faces=[[[1,0,0],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5],[.5,-.5,.5]],[[-1,0,0],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,-.5],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5]],[[0,-1,0],[-.5,-.5,.5],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5]],[[0,0,1],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5],[-.5,-.5,.5]],[[0,0,-1],[-.5,-.5,-.5],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5]]];for(const f of faces)for(const i of [1,2,3,1,3,4])verts.push(...f[i],...f[0]);for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6;const x=Math.cos(a)*.5,y=Math.sin(a)*.5,X=Math.cos(b)*.5,Y=Math.sin(b)*.5;for(const v of [[x,y,-.5],[X,Y,-.5],[X,Y,.5],[x,y,-.5],[X,Y,.5],[x,y,.5]])verts.push(...v,Math.cos((a+b)/2),Math.sin((a+b)/2),0);for(const z of [-.5,.5])for(const v of [[0,0,z],[x,y,z],[X,Y,z]])verts.push(...v,0,0,Math.sign(z));}const extraMeshes={};
function addMesh(name,points,triangles){const offset=verts.length/6;for(const ids of triangles){const [a,b,c]=ids.map(i=>points[i]),u=b.map((v,i)=>v-a[i]),v=c.map((x,i)=>x-a[i]),n=norm([u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]]);for(const p of [a,b,c])verts.push(...p,...n);}extraMeshes[name]={offset,count:verts.length/6-offset};}
addMesh('triangle',[[-.5,-.5,-.5],[.5,-.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[-.5,.5,.5]],[[0,2,1],[3,4,5],[0,1,4],[0,4,3],[1,2,5],[1,5,4],[2,0,3],[2,3,5]]);
const spherePoints=[],sphereTriangles=[];for(let i=0;i<=10;i++)for(let j=0;j<=16;j++){const a=i*Math.PI/10,b=j*Math.PI/8;spherePoints.push([Math.sin(a)*Math.cos(b)*.5,Math.cos(a)*.5,Math.sin(a)*Math.sin(b)*.5]);}for(let i=0;i<10;i++)for(let j=0;j<16;j++){const k=i*17+j;sphereTriangles.push([k,k+17,k+1],[k+1,k+17,k+18]);}addMesh('sphere',spherePoints,sphereTriangles);
const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);for(const [n,offset]of [['aPos',0],['aNormal',12]]){let a=gl.getAttribLocation(program,n);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,24,offset);}gl.enable(gl.DEPTH_TEST);
const C={floor:[.17,.22,.21],wall:[.19,.25,.25],dark:[.065,.105,.105],metal:[.28,.34,.32],lime:[.65,.95,.37],amber:[1,.45,.13],red:[.9,.18,.10],blue:[.24,.7,.8]};
const world=[], obstacles=[], gates=[], pickups=[], debris=[], bolts=[], particles=[], enemies=[];let gun=[];
const box=(p,s,c,a=0,g=0)=>({p:[...p],s:[...s],c,a,g});
function add(p,s,c,a=0,g=0,solid=false){const b=box(p,s,c,a,g);b.blocksShots=solid||s[1]>.25;world.push(b);if(solid)obstacles.push(b);return b;}
function draw(b){if(b.open)return;const alpha=b.alpha??1,translucent=alpha<1;gl.uniform3fv(U.Pos,b.p);gl.uniform3fv(U.Size,b.s);gl.uniform3fv(U.Color,b.c);gl.uniform1f(U.Angle,b.a||0);gl.uniform1f(U.Tilt,b.tilt||0);gl.uniform1f(U.Glow,b.g||0);gl.uniform1f(U.Alpha,alpha);if(translucent){gl.enable?.(gl.BLEND);gl.blendFunc?.(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask?.(false);}const mesh=extraMeshes[b.kind==='energy'?'sphere':b.kind];gl.drawArrays(gl.TRIANGLES,mesh?mesh.offset:b.kind==='cylinder'?36:0,mesh?mesh.count:b.kind==='cylinder'?144:36);if(translucent){gl.depthMask?.(true);gl.disable?.(gl.BLEND);}}
function multiply(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function view(eye,yaw,pitch){let sy=Math.sin(yaw),cy=Math.cos(yaw),sp=Math.sin(pitch),cp=Math.cos(pitch);let right=[cy,0,-sy],up=[sy*sp,cp,cy*sp],back=[sy*cp,-sp,cy*cp];return new Float32Array([right[0],up[0],back[0],0,right[1],up[1],back[1],0,right[2],up[2],back[2],0,-dot(right,eye),-dot(up,eye),-dot(back,eye),1]);}
function projection(fov){let f=1/Math.tan(fov/2),n=.025,far=160;return new Float32Array([f/(canvas.width/canvas.height),0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}function norm(v){let l=Math.hypot(...v)||1;return v.map(x=>x/l);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
// Five connected foundry halls. Each cleared gate opens toward the next hall.
function container(x,z,w,d,h,c){add([x,h/2,z],[w,h,d],c,0,0,true);for(let k=-w/2+.25;k<w/2;k+=.55)add([x+k,h/2,z+d/2+.025],[.09,h-.12,.08],c.map(v=>v*1.15));add([x,h+.05,z],[w+.12,.1,d+.1],C.metal);}
for(let sector=0;sector<10;sector++){
 const z=-sector*60;
 add([0,-.25,z],[44,.5,60],C.floor);
 for(const x of [-22,22])add([x,4,z],[1,8,60],C.wall,0,0,true);
 for(let k=-28;k<=28;k+=4){add([0,.009,z+k],[43,.012,.023],[.25,.32,.29]);add([k*.7,.006,z],[.023,.012,60],[.25,.32,.29]);}
 for(const x of [-18,18])for(const dz of [-22,-5,15]){add([x,4,z+dz],[.75,8,.75],C.dark,0,0,true);add([x,5,z+dz+.4],[.12,2,.08],C.lime,0,.8);}
 for(let rx=-20;rx<=20;rx+=4)for(let rz=-28;rz<=28;rz+=4){const nearVent=[-8,8].some(vx=>[-12,-22].some(vz=>Math.abs(rx-vx)<4&&Math.abs(rz-vz)<4)),bossHole=(sector===4||sector===9)&&Math.abs(rx)<6&&Math.abs(rz+20)<6;if(!nearVent&&!bossHole)add([rx,(sector===4||sector===9)?22.4:11.8,z+rz],[4,.25,4],C.dark,0,0,true);}
 for(const x of [-13,13])add([x,4,z-30],[18,8,.8],C.wall,0,0,true);
 if(sector<9){let gate=add([0,3,z-30],[8,6,.6],[.25,.32,.30],0,0,true);gate.sector=sector;gates.push(gate);}
 else add([0,4,z-30],[8,8,.8],C.wall,0,0,true);
 for(const x of [-4.2,4.2])add([x,3,z-29.5],[.16,6,.1],C.amber,0,1);
 for(let dz=20;dz>-28;dz-=6){add([-.48,.015,z+dz],[.12,.025,1.1],C.lime,-.55,.3);add([.48,.015,z+dz],[.12,.025,1.1],C.lime,.55,.3);}
}
add([0,4,30],[44,8,1],C.wall,0,0,true);
// HK416-inspired placeholder: receiver, stock, rail, handguard, barrel, magazine and sights.
function gb(p,s,c=C.dark,a=0){gun.push(box(p,s,c,a));}
gb([.24,-.24,-.42],[.115,.13,.36],[.13,.15,.145]);gb([.24,-.28,-.24],[.14,.14,.15],[.11,.125,.12]);gb([.24,-.18,-.59],[.125,.12,.30],[.20,.23,.20]);gb([.24,-.174,-.86],[.033,.035,.27],[.09,.1,.09]);gb([.24,-.174,-1.015],[.052,.054,.075],C.dark);gb([.24,-.36,-.45],[.085,.23,.115],[.15,.16,.145],-.06);gb([.24,-.37,-.23],[.067,.16,.085],C.dark);gb([.24,-.27,-.08],[.09,.065,.23],C.dark);gb([.24,-.285,.01],[.135,.17,.17],[.12,.14,.12]);gb([.24,-.13,-.44],[.052,.024,.52],[.13,.15,.13]);for(let i=0;i<20;i++)gb([.24,-.11,-.20-i*.026],[.084,.018,.011],[.20,.23,.20]);for(let i=0;i<7;i++){gb([.307,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);gb([.174,-.18,-.47-i*.036],[.007,.034,.020],[.035,.044,.039]);}for(const z of [-.33,-.71]){gb([.24,-.087,z],[.03,.065,.027],C.dark);gb([.216,-.056,z],[.015,.045,.025],C.dark);gb([.264,-.056,z],[.015,.045,.025],C.dark);}gb([.24,-.29,-.65],[.06,.12,.065],C.dark);gb([.295,-.237,-.35],[.012,.026,.073],[.38,.41,.36]);
// Gloved hands.
gb([.235,-.41,-.23],[.11,.13,.13],[.24,.28,.22]);gb([.08,-.44,-.05],[.18,.17,.38],[.17,.22,.17],-.22);gb([.21,-.35,-.63],[.14,.12,.13],[.24,.28,.22]);gb([.0,-.49,-.45],[.14,.14,.34],[.17,.22,.17],-.5);
const types=[{name:'정찰형',hp:70,scale:.78,speed:7.4,melee:true,c:[.05,.80,.95],accent:[1,.76,.10],arm:24,leg:25,head:32,damage:12,rate:1.1},{name:'전투형',hp:150,scale:1.1,speed:2.2,c:[1,.38,.055],accent:[.12,.75,.98],arm:44,leg:44,head:56,damage:12,rate:1.65},{name:'중장갑형',hp:400,scale:1.7,speed:.95,c:[.67,.20,.95],accent:[1,.78,.10],arm:90,leg:95,head:110,damage:18,rate:1.3},
{name:'도마뱀형',hp:240,scale:1.15,speed:3.8,quad:true,kind:'lizard',c:[.34,.86,.12],accent:[1,.68,.05],arm:50,leg:48,head:100,damage:7,rate:3.8},
{name:'포격보행형',hp:320,scale:1.5,speed:2.9,quad:true,kind:'walker',c:[.15,.35,1],accent:[.65,.85,1],arm:60,leg:65,head:100,damage:18,rate:2.5},
{name:'슈퍼 정찰형',hp:130,scale:.92,speed:18,quad:true,kind:'super',melee:true,c:[1,.025,.055],accent:[1,.58,.1],arm:40,leg:28,head:55,damage:16,rate:.65}];
let state='menu',difficulty=1,wave=0,hp=100,ammo=30,reload=0,kills=0,broken=0,shots=0,hits=0,elapsed=0,yaw=0,pitch=0,pos=[0,1.7,19],jumpV=0,fire=false,aim=false,cooldown=0,recoil=0,hitTimer=0,damageTimer=0,noticeTimer=0,intermission=0,feedTimer=0,feet=0,sensitivity=1,lockedFallback=false,sectorCleared=false,threatTimer=0;let threatSource=null;let chosenDifficulty=1;let rankCheckpoints=[],rankRemote=null,rankCloudResult=null,rankSync=Promise.resolve(),rankConnectionError='',boardScope='cloud';let mode='standard',sprinting=false,sprintBlend=0,sprintTouch=false,stepTimer=0,score=0,rankRun=null,rankResult=null,rankStart=0,runEpoch=0,stageStats={kills:[0,0,0,0,0,0],parts:0,bossParts:0,boss:false};const scheduled=[],lasers=[],sweeps=[];const bossChallengeStage=()=>mode==='boss5'?5:mode==='boss10'?10:0;const totalStages=()=>mode==='ranked'||mode==='boss10'?10:5;const bulletSpeed=()=>mode==='ranked'?26:[11,15,19][difficulty];const SPRINT_SPEED=32;
let combatTime=0,invulnerableUntil=-1,shield=20,shieldTimer=0,healthDropsThisWave=0;const spawnQueue=[],vents=[];const SHIELD_DELAY=6,shieldCapacity=()=>20;
const keys=new Set(),touch='ontouchstart'in window;let joystick=[0,0],lookPointer=null,lastLook=[0,0],audioCtx;
function sound(f,d=.08,volume=.05,noise=false,source=null){if(!$('sound').checked)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const g=audioCtx.createGain();const distance=source?Math.hypot(source[0]-pos[0],source[2]-pos[2]):0;g.gain.setValueAtTime(volume*(Number($('soundlevel').value)/100)*(source?clamp(14/(distance+7),.2,1):1),audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);if(source&&audioCtx.createStereoPanner){const pan=audioCtx.createStereoPanner();const dx=source[0]-pos[0],dz=source[2]-pos[2];pan.pan.value=clamp((Math.cos(yaw)*dx-Math.sin(yaw)*dz)/(distance||1),-1,1);g.connect(pan);pan.connect(audioCtx.destination);}else g.connect(audioCtx.destination);let o;if(noise){let b=audioCtx.createBuffer(1,audioCtx.sampleRate*d,audioCtx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1);o=audioCtx.createBufferSource();o.buffer=b;let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=f;o.connect(filter);filter.connect(g);}else{o=audioCtx.createOscillator();o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.5,audioCtx.currentTime+d);o.connect(g);}o.start();o.stop(audioCtx.currentTime+d);}catch{}}
const robotBuffers=new Map(),robotVoices=[];let audioLoad=null,robotBus=null;
function prepareRobotAudio(){if(!audioCtx)return Promise.resolve();if(audioLoad)return audioLoad;const files=[];for(const kind of ['scout','soldier','heavy','lizard','walker','super','boss'])for(const event of ['move','alert','attack','death',...(kind==='boss'?['sweep','missiles','laser','burst','blades']:[])])files.push(kind+'-'+event);audioLoad=Promise.all(files.map(async key=>{try{const r=await fetch('audio/'+key+'.wav');if(!r.ok)throw Error('Audio unavailable');robotBuffers.set(key,await audioCtx.decodeAudioData(await r.arrayBuffer()));}catch{}}));return audioLoad;}
function robotSound(e,event){if(mode==='ranked'&&event==='alert')return;if(!$('sound').checked)return;const kind=e.boss?'boss':['scout','soldier','heavy','lizard','walker','super'][e.typeIndex],key=kind+'-'+event;if(!audioCtx){sound(60,.01,0);prepareRobotAudio();}const buffer=robotBuffers.get(key);if(!buffer){sound(e.boss?48:e.typeIndex===2?62:e.typeIndex===1?120:210,event==='death'?.4:.16,.075,event!=='alert',e.p);return;}const distance=Math.hypot(e.p[0]-pos[0],e.p[2]-pos[2]);if(distance>65||robotVoices.length>=(event==='move'?10:24))return;
if(!robotBus){robotBus=audioCtx.createDynamicsCompressor();robotBus.threshold.value=-18;robotBus.knee.value=16;robotBus.ratio.value=4;robotBus.attack.value=.005;robotBus.release.value=.2;robotBus.connect(audioCtx.destination);}const src=audioCtx.createBufferSource(),gain=audioCtx.createGain(),pan=audioCtx.createStereoPanner(),filter=audioCtx.createBiquadFilter();src.buffer=buffer;e.voicePitch??=.94+Math.random()*.12;src.playbackRate.value=e.voicePitch*(event==='move'?1+Math.random()*.08:1);filter.type='lowpass';const blocked=!lineOfSight(pos,[e.p[0],1.2,e.p[2]]);filter.frequency.value=blocked?900:7000;src.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(robotBus);const voice={src,gain,pan,e,event,blocked};robotVoices.push(voice);src.onended=()=>{const i=robotVoices.indexOf(voice);if(i>=0)robotVoices.splice(i,1);src.disconnect();filter.disconnect();gain.disconnect();pan.disconnect();};setVoicePosition(voice);src.start();}
function setVoicePosition(v){const dx=v.e.p[0]-pos[0],dz=v.e.p[2]-pos[2],distance=Math.hypot(dx,dz);v.pan.pan.value=clamp((Math.cos(yaw)*dx-Math.sin(yaw)*dz)/(distance||1),-1,1);const level=Number($('soundlevel').value)/100;v.gain.gain.value=level*(v.event==='move'?.33:.60)*(v.e.boss?1.2:1)*clamp(14/(distance+5),.05,1)*(v.blocked?.4:1);}
function stopRobotSounds(e=null,event=null){for(const v of [...robotVoices])if((!e||v.e===e)&&(!event||v.event===event)){try{v.src.stop();}catch{}}}
function updateRobotAudio(dt){for(const v of robotVoices)setVoicePosition(v);for(const e of enemies){if(e.dead)continue;const moving=e.audioPos&&Math.hypot(e.p[0]-e.audioPos[0],e.p[2]-e.audioPos[1])>.006;e.audioPos=[e.p[0],e.p[2]];e.stepClock=(e.stepClock??Math.random()*.4)-dt;if(moving&&e.stepClock<=0){robotSound(e,'move');e.stepClock=e.boss?.85:e.typeIndex===2?.70:e.typeIndex===1?.43:.23;}}}
$('sound').onchange=()=>{if(!$('sound').checked)stopRobotSounds();};

function part(e,name,p,s,h,c){const b=box(p,s,c||e.type.c);b.name=name;b.hp=h;b.max=h;b.e=e;b.local=p;e.parts.push(b);}
function spawn(type,x,z){if(typeof type==='object'){const e=spawn(type.base,x,z);configureVariant(e,type.variant);return e;}if(types[type].quad)return spawnQuad(type,x,z);const t=types[type],m=[.72,1,1.45][difficulty]*(1+(wave-1)*.12),e={type:t,p:[x,0,z],parts:[],hp:t.hp*m,max:t.hp*m,scale:t.scale,timer:1.5+Math.random()*2,phase:Math.random()*6,dead:false,stagger:0,angle:0,age:0,warning:0};part(e,'코어',[0,1.27,0],[.68,.7,.43],999);part(e,'머리',[0,2.02,0],[.36,.68,.38],t.head*m);part(e,'왼팔',[-.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'오른팔',[.53,1.23,0],[.38,.83,.36],t.arm*m);part(e,'왼다리',[-.21,.44,0],[.27,.83,.31],t.leg*m);part(e,'오른다리',[.21,.44,0],[.27,.83,.31],t.leg*m);e.typeIndex=type;if(type===2){part(e,'전면 방패',[0,1.15,.62],[1.15,1.95,.16],300*m,[.25,.2,.4]);e.parts.at(-1).shield=true;}enemies.push(e);return e;}
function partBox(e,p){
 const legs=activeParts(e,'다리').length,total=e.type.quad?4:2;let y=e.boss?0:legs===0?-.45:legs<total?-.10:0;
 const isLeg=p.name.includes('다리'),phase=e.gait??0;
 let step=isLeg&&legs>0?Math.sin(phase+(p.local[0]<0?0:Math.PI)+(p.local[2]<0?Math.PI:0))*.12:0;
 let local=[...p.local];const thrust=e.attackAnim>0?Math.sin(Math.PI*(1-e.attackAnim/.36))*.8:0;
 if(p.name.includes('팔')&&e.type.melee){local[2]+=thrust;local[1]+=.1*thrust;}
 if(isLeg&&e.type.quad)local[2]+=Math.cos(phase+(p.local[0]<0?0:Math.PI)+(p.local[2]<0?Math.PI:0))*.13;
 const c=Math.cos(e.angle),sn=Math.sin(e.angle);return {...p,a:e.angle,p:[e.p[0]+(c*local[0]+sn*local[2])*e.scale,e.p[1]+(local[1]+y+step)*e.scale,e.p[2]+(-sn*local[0]+c*local[2])*e.scale],s:p.s.map(x=>x*e.scale)};
}
function announce(s,time=2.8){$('notice').textContent=s;noticeTimer=time;}
function log(s){$('feed').textContent=s;feedTimer=2.5;}
const WEAPONS=[{name:'HK416 · AUTO',capacity:30,reload:2.05,delay:.105,damage:30},{name:'PISTOL · SEMI',capacity:12,reload:1.35,delay:.25,damage:48},{name:'RPG · EXPLOSIVE',capacity:5,reload:0,delay:.9,damage:650},{name:'BREACH · SHOTGUN',capacity:8,reload:2.35,delay:.65,damage:28,pellets:9}];
let weapon=0,magazines=[30,12,0,8],rpgAmmo=0,grenades=0,punchTimer=0,meleeCooldown=0,grenadeCooldown=0;const playerOrdnance=[];
const rifle=gun,pistol=[],rpg=[],shotgun=[];function weaponBox(arr,p,s,c=C.dark,kind='box'){arr.push({...box(p,s,c),kind});}
weaponBox(pistol,[.24,-.23,-.46],[.11,.11,.34],[.35,.37,.39]);weaponBox(pistol,[.24,-.32,-.32],[.085,.19,.11],[.10,.11,.12]);weaponBox(pistol,[.24,-.20,-.65],[.06,.06,.06],C.dark);weaponBox(pistol,[.24,-.165,-.55],[.018,.035,.025],C.lime);weaponBox(pistol,[.24,-.36,-.27],[.13,.14,.15],[.24,.28,.22]);
weaponBox(rpg,[.30,-.28,-.55],[.24,.24,.95],[.28,.40,.16],'cylinder');weaponBox(rpg,[.30,-.28,-1.06],[.27,.27,.09],[.67,.64,.23],'cylinder');weaponBox(rpg,[.30,-.28,-1.11],[.19,.19,.02],C.dark,'cylinder');weaponBox(rpg,[.30,-.28,-.08],[.35,.35,.15],[.18,.22,.11],'cylinder');weaponBox(rpg,[.30,-.43,-.33],[.08,.19,.10],C.dark);weaponBox(rpg,[.30,-.09,-.52],[.04,.20,.04],C.dark);weaponBox(rpg,[.30,-.47,-.27],[.13,.14,.15],[.24,.28,.22]);
weaponBox(shotgun,[.25,-.24,-.48],[.15,.16,.42],[.18,.22,.20]);weaponBox(shotgun,[.25,-.20,-.86],[.075,.075,.62],C.dark,'cylinder');weaponBox(shotgun,[.25,-.20,-1.18],[.11,.11,.08],C.metal,'cylinder');weaponBox(shotgun,[.25,-.36,-.40],[.09,.24,.13],[.24,.28,.22]);weaponBox(shotgun,[.25,-.29,-.13],[.12,.12,.34],[.16,.19,.17]);weaponBox(shotgun,[.25,-.11,-.52],[.045,.04,.55],C.amber);weaponBox(shotgun,[.25,-.42,-.27],[.14,.14,.16],[.24,.28,.22]);const weaponModels=[rifle,pistol,rpg,shotgun];
function switchWeapon(n){if(state!=='play'||n===weapon)return;if(weapon!==2)magazines[weapon]=ammo;weapon=n;ammo=n===2?rpgAmmo:magazines[n];reload=0;fire=false;cooldown=.25;recoil=0;updateHud();sound(600,.07,.03,true);}
function destroyPart(e,p){if(p.name==='장갑'||p.name==='코어'||p.destroyed)return;if(p.hp>0)return;p.destroyed=true;detach(e,p);broken++;if(p.noScore){if(e.boss)cancelBrokenPattern(e);log(p.name+' 파괴');return;}if(e.boss){stageStats.bossParts++;score+=500;cancelBrokenPattern(e);}else{stageStats.parts++;score+=100;}log(p.name+' 파괴');if(p.name==='머리'&&!e.boss)e.hp=0;}
function applyDamage(p,damage){const e=p.e;if(e.dead||p.destroyed||e.dropDelay>0||e.p[1]>0&&e.dropping)return;if(e.aerial>0){damage*=.2;sparks(partBox(e,p).p,C.blue,4);}if(!p.shield)e.hp-=damage;p.hp-=damage;destroyPart(e,p);if(e.hp<=0)kill(e);}
function playerExplosion(point,damage,radius){blastMarks.push({p:[...point],radius,life:.6});sparks(point,C.amber,30);sound(65,.4,.18,true,point);for(const e of enemies){if(e.dead||e.dropDelay>0||e.dropping)continue;const surfaces=e.parts.filter(p=>p.hp>0&&!p.shield).map(p=>{const b=partBox(e,p);return b.p.map((v,j)=>Math.max(v-b.s[j]/2,Math.min(v+b.s[j]/2,point[j])));}).sort((a,b)=>Math.hypot(...a.map((v,j)=>v-point[j]))-Math.hypot(...b.map((v,j)=>v-point[j])));const target=surfaces.find(p=>lineOfSight(point,p));if(!target)continue;const distance=Math.hypot(...target.map((v,j)=>v-point[j]));if(distance>radius||!lineOfSight(point,target))continue;const amount=damage*(1-.65*distance/radius),delta=target.map((v,j)=>v-point[j]),ray=norm(delta);let shield=null,nearest=Infinity;for(const p of e.parts)if(p.shield&&p.hp>0&&shieldFaces(e,p,ray)){const t=rayBox(point,ray,partBox(e,p));if(t!==null&&t<nearest){nearest=t;shield=p;}}if(shield){applyDamage(shield,amount);continue;}const dealt=amount*(e.aerial>0?.2:1);e.hp-=dealt;for(const p of e.parts)if(p.hp>0&&!p.shield){const bp=partBox(e,p).p;if(Math.hypot(...bp.map((v,j)=>v-point[j]))<radius){p.hp-=dealt*.65;destroyPart(e,p);}}if(e.hp<=0)kill(e);}const selfDist=Math.hypot(...pos.map((v,j)=>v-point[j]));if(selfDist<radius*.55&&lineOfSight(point,pos))damagePlayer(Math.min(55,damage*.12)*(1-selfDist/radius),point);updateHud();}
function throwGrenade(){if(state!=='play'||grenadeCooldown>0)return;if(grenades<=0){log('수류탄이 없습니다 · 청록 보급품을 획득하세요');return;}grenades--;grenadeCooldown=.65;playerOrdnance.push(makeGrenade());updateHud();sound(600,.09,.03,true);}
function punch(){if(state!=='play'||meleeCooldown>0)return;meleeCooldown=.65;punchTimer=.35;const d=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)];const h=trace(pos,d,true,2.4);sound(180,.15,.07,true);if(h.obj?.e){applyDamage(h.obj,65);hitTimer=.15;sparks(pos.map((v,j)=>v+d[j]*h.t),C.amber,8);sound(70,.15,.08);updateHud();}}
function updateOrdnance(dt){punchTimer=Math.max(0,punchTimer-dt);meleeCooldown=Math.max(0,meleeCooldown-dt);grenadeCooldown=Math.max(0,grenadeCooldown-dt);for(let i=playerOrdnance.length-1;i>=0;i--){const b=playerOrdnance[i];let remaining=dt,exploded=false;while(remaining>0&&!exploded){const step=Math.min(remaining,1/60);exploded=stepOrdnance(b,step);remaining-=step;}if(exploded){playerExplosion(b.p,b.damage,b.radius);playerOrdnance.splice(i,1);}}}
function ammoDropChance(kind,d=difficulty){return kind==='rpg'?[.24,.14,.07][d]:[.30,.20,.10][d];}
function dropAmmo(e){for(const kind of ['rpg','grenade'])if(Math.random()<ammoDropChance(kind))pickups.push({kind,p:[e.p[0]+(kind==='rpg'?.65:-.65),.45,e.p[2]],amount:1});}

function waveStart(){wave++;sectorCleared=false;healthDropsThisWave=0;reinforcements.length=0;shockwaves.length=0;if(wave>1){const gate=gates[wave-2];gate.open=false;gate.sealed=true;gate.c=[.48,.08,.035];pos[2]=Math.min(pos[2],gate.p[2]-1.1);}stageStats={kills:[0,0,0,0,0,0],parts:0,bossParts:0,boss:false};const challenge=bossChallengeStage(),bossStage=challenge===wave||mode==='ranked'&&wave%5===0,roster=challenge?[]:waveRoster(wave,mode),z=-(wave-1)*60;for(let i=0;i<roster.length;i++){const entry={type:roster[i],p:randomVentPoint(),delay:.25+i*(.3+Math.random()*.3)};if(wave>=5&&i>=Math.ceil(roster.length*.6))reinforcements.push(entry);else spawnQueue.push(entry);}if(bossStage)spawnQueue.push({boss:true,final:wave===10,p:[0,0,z-20],delay:1.2});announce(bossStage?'BOSS 도전 · '+(wave===10?'OMEGA':'WARDEN'):'구역 '+wave+' · 천장 투입구 가동',3.5);sound(420,.22,.04);updateHud();}
function dropChance(health,d=difficulty){const need=clamp((100-health)/99,0,1),peak=[.99,.50,.30][d],base=healthDropsThisWave?0:.14;return base+(peak-base)*need;}
function dropHealth(e){if(Math.random()<dropChance(hp)){pickups.push({p:[e.p[0],.45,e.p[2]],heal:[50,30,20][difficulty]});healthDropsThisWave++;}}
function collectHealth(){for(let i=pickups.length-1;i>=0;i--){const item=pickups[i],dist=Math.hypot(pos[0]-item.p[0],pos[2]-item.p[2]);const can=item.kind==='rpg'?rpgAmmo<5:item.kind==='grenade'?grenades<4:hp<100;if(can&&dist<1.25){if(!lineOfSight(pos,item.p))continue;if(item.kind==='rpg'){rpgAmmo=Math.min(5,rpgAmmo+1);if(weapon===2)ammo=rpgAmmo;log('RPG 탄약 +1');}else if(item.kind==='grenade'){grenades=Math.min(4,grenades+1);log('수류탄 +1');}else{const amount=Math.min(item.heal,100-hp);hp+=amount;log('회복 키트 +'+Math.round(amount)+' HP');}pickups.splice(i,1);sound(720,.25,.07);updateHud();}}}
function alertAttack(e){if(mode==='ranked')return;threatSource=[...e.p];threatTimer=1.1;robotSound(e,'alert');}
function fireEnemy(e,arms){const origin=e.type.quad?partBox(e,e.parts.find(p=>p.name==='머리')||e.parts[0]).p:[e.p[0],e.scale*1.37,e.p[2]],delta=pos.map((p,i)=>p-origin[i]),dist=Math.hypot(...delta);if(trace(origin,norm(delta),false,dist).obj)return;alertAttack(e);if(e.type.kind!=='lizard')robotSound(e,'attack');
 if(e.type.kind==='lizard'){if(activeParts(e,'머리').length)fireLizardLaser(e);}
 else if(e.type.kind==='walker'){if(activeParts(e,'발사 코어').length){const o=partBox(e,activeParts(e,'발사 코어')[0]).p;bossProjectile(e,o,[Math.sin(e.angle)*.72,.38,Math.cos(e.angle)*.72],mode==='ranked'?27:21,e.type.damage,'missile');const missile=bolts.at(-1);missile.arcTime=.22;missile.turnRate=5.8;missile.targetLift=.35;}}
 else if(arms&&!e.type.melee&&dist<25){const direction=norm(delta);bolts.push({p:origin,v:direction.map(v=>v*bulletSpeed()),s:[.15,.15,.15],c:C.red,g:2,life:4,source:[...e.p],damage:e.type.damage*([.65,1,1.3][difficulty])*(arms===1?.65:1)});sound(650,.16,.18,true,e.p);}
 else if(dist<2.6){e.attackAnim=.36;sound(160,.18,.13,true,e.p);damagePlayer(arms?e.type.damage*(arms===1?.65:1):4,e.p);}}
function advanceSector(){if(state!=='play'||spawnQueue.length||reinforcements.length||enemies.some(e=>!e.dead))return;if(!sectorCleared){sectorCleared=true;score+=1000;if(mode==='ranked')checkpointRank();bolts.length=lasers.length=sweeps.length=scheduled.length=playerOrdnance.length=0;magazines=[30,12,0,8];ammo=weapon===2?rpgAmmo:magazines[weapon];reload=0;if(wave===totalStages()){announce('모든 구역 확보',2);intermission=2;}else{gates[wave-1].open=true;announce('구역 확보 · 녹색 통로로 전진',4);}updateHud();}if(wave===totalStages()){intermission-=lastDt;if(intermission<=0)finish(true);}else if(pos[2]<-30-(wave-1)*60-1)waveStart();}
let lastDt=0;
function updateHud(){$('hp').innerHTML=Math.max(0,Math.ceil(hp))+' <em>/ 100</em>';$('hpbar').style.width=hp+'%';$('hpbar').style.background=hp<30?'#f07e55':'#b9f97b';$('ammo').innerHTML=ammo+' <em>/ '+(weapon===2?'5':'∞')+'</em>';$('weaponlabel').textContent=WEAPONS[weapon].name;$('inventory').textContent='1 소총 · 2 권총 · 3 RPG '+rpgAmmo+'/5 · 4 샷건 · G 수류탄 '+grenades+'/4 · F 주먹';$('gunstatus').textContent=reload>0?'재장전 중…':weapon===2?'탄약 보급품을 주워 사용':weapon===3?'12 GA · 9 PELLETS':weapon===1?'9 MM · SEMI':'5.56 × 45 MM';$('wave').textContent='WAVE '+String(wave).padStart(2,'0');$('remaining').textContent=sectorCleared?'구역 확보':'적 '+(enemies.filter(e=>!e.dead).length+spawnQueue.length+reinforcements.length)+'기 남음';const sectorMode=bossChallengeStage()?'BOSS CHALLENGE':mode==='ranked'?'RANKED':'FOUNDRY';$('sectorlabel').textContent='SECTOR '+String(wave).padStart(2,'0')+' / '+String(totalStages()).padStart(2,'0')+' · '+sectorMode;$('healinfo').textContent='실드 '+Math.ceil(shield)+' / '+shieldCapacity()+' · 6초 무피격 시 충전 · 회복 드롭 '+Math.round(dropChance(hp)*100)+'% · 키트 +'+[50,30,20][difficulty]+' HP';}
async function start(){if(state==='starting')return;stopRobotSounds();sound(60,.01,0);prepareRobotAudio();rankResult=null;rankRemote=null;rankCloudResult=null;rankSync=Promise.resolve();rankConnectionError='';rankCheckpoints=[];resetCombatExtras();combatTime=shieldTimer=healthDropsThisWave=0;shield=20;invulnerableUntil=-1;spawnQueue.length=0;randomizeArena();$('damage').style.opacity='0';if(mode==='ranked'){rankRun=globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);difficulty=2;state='starting';lock();$('start').disabled=true;$('start').textContent='랭킹 연결 중…';try{if(!window.IronCloud)throw Error('랭킹 모듈을 불러오지 못했습니다.');const r=await window.IronCloud.start(rankRun);rankRemote=r.id;}catch(e){rankConnectionError=e.message;boardScope='local';}$('start').disabled=false;$('start').textContent='작전 시작 ↗';rankStart=performance.now();}else rankRun=null;runEpoch++;score=0;weapon=0;magazines=[30,12,0,8];rpgAmmo=grenades=0;punchTimer=meleeCooldown=grenadeCooldown=0;playerOrdnance.length=0;sprintBlend=0;sprinting=false;sprintTouch=false;scheduled.length=lasers.length=sweeps.length=0;fire=aim=false;keys.clear();enemies.length=debris.length=bolts.length=particles.length=pickups.length=0;for(const g of gates){g.open=false;g.sealed=false;g.c=[.25,.32,.30];}sectorCleared=false;threatTimer=0;threatSource=null;const challenge=bossChallengeStage();wave=challenge?challenge-1:0;hp=100;ammo=30;reload=0;kills=broken=shots=hits=elapsed=0;pos=[0,1.7,challenge?-60*(challenge-1)+19:19];yaw=pitch=jumpV=0;intermission=cooldown=0;state='play';$('rankform').classList.add('hidden');$('submitstatus').textContent='';for(const id of ['menu','pause','end'])$(id).classList.add('hidden');$('hud').classList.remove('hidden');if(touch)$('touch').classList.remove('hidden');waveStart();lock();if(mode==='ranked'&&!rankRemote)announce('오프라인 랭킹 · 이번 기록은 이 기기에 저장됩니다',5);$('rankstatus').textContent=rankConnectionError;sound(350,.2,.03);if(document.hidden)pause();}
function lock(){if(touch||document.pointerLockElement===canvas)return;try{const p=canvas.requestPointerLock();if(p&&p.catch)p.catch(()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});}catch{lockedFallback=true;}}
function pause(){stopRobotSounds();if(state!=='play')return;state='pause';sprinting=false;sprintTouch=false;fire=aim=false;keys.clear();joystick=[0,0];$('pause').classList.remove('hidden');$('touch').classList.add('hidden');document.exitPointerLock?.();}
function resume(){state='play';$('pause').classList.add('hidden');if(touch)$('touch').classList.remove('hidden');lock();}
function toMenu(){resetCombatExtras();stopRobotSounds();spawnQueue.length=0;$('damage').style.opacity='0';runEpoch++;scheduled.length=lasers.length=sweeps.length=playerOrdnance.length=0;state='menu';fire=false;keys.clear();document.exitPointerLock?.();for(const id of ['pause','end','hud','touch'])$(id).classList.add('hidden');$('menu').classList.remove('hidden');enemies.length=bolts.length=debris.length=particles.length=pickups.length=0;for(const g of gates){g.open=false;g.sealed=false;g.c=[.25,.32,.30];}wave=1;spawn(0,0,-1);spawn(1,5,-5);spawn(2,11,-10);}
function finish(win){if(state!=='play')return;state='end';stopRobotSounds();sprinting=false;sprintTouch=false;if(mode==='ranked')elapsed=rankResult?rankResult.elapsedMs/1000:(performance.now()-rankStart)/1000;fire=false;document.exitPointerLock?.();$('end').classList.remove('hidden');$('touch').classList.add('hidden');$('resultlabel').textContent=win?'SECTOR SECURED':'OPERATOR DOWN';$('resulttitle').textContent=win?'구역 확보 완료.':'작전 종료.';$('stats').innerHTML=`${wave} / ${totalStages()} 스테이지 · ${score.toLocaleString()}점 · ${kills}기 제압 · ${broken}개 부위 파괴<br>명중률 ${shots?Math.round(hits/shots*100):0}% · ${Math.floor(elapsed/60)}분 ${Math.floor(elapsed%60)}초`;sound(win?660:100,.5,.06);if(mode==='ranked'){if(!win){checkpointRank('dead');}prepareRankResult();}}
function beginReload(){if(state!=='play'||weapon===2||reload>0||ammo===WEAPONS[weapon].capacity)return;reload=WEAPONS[weapon].reload;fire=false;updateHud();sound(850,.12,.035,true);}
function rayBox(o,d,b){if(b.open)return null;if(b.a){const c=Math.cos(b.a),s=Math.sin(b.a),x=o[0]-b.p[0],z=o[2]-b.p[2];o=[c*x-s*z+b.p[0],o[1],s*x+c*z+b.p[2]];d=[c*d[0]-s*d[2],d[1],s*d[0]+c*d[2]];}let tmin=0,tmax=500;for(let i=0;i<3;i++){let lo=b.p[i]-b.s[i]/2,hi=b.p[i]+b.s[i]/2;if(Math.abs(d[i])<1e-7){if(o[i]<lo||o[i]>hi)return null;}else{let a=(lo-o[i])/d[i],v=(hi-o[i])/d[i];if(a>v)[a,v]=[v,a];tmin=Math.max(tmin,a);tmax=Math.min(tmax,v);if(tmin>tmax)return null;}}return tmin;}
function trace(o,d,includeEnemies=true,max=100){let closest=max,obj=null;for(const b of world){if(!b.blocksShots||b.open)continue;const t=rayBox(o,d,b);if(t!==null&&t<closest){closest=t;obj=b;}}if(includeEnemies)for(const e of enemies)if(!e.dead)for(const p of e.parts)if(p.hp>0&&!(e.dropDelay>0)&&(!p.shield||shieldFaces(e,p,d))){const t=rayBox(o,d,partBox(e,p));if(t!==null&&t<closest){closest=t;obj=p;}}return {t:closest,obj};}
function sparks(p,color,n=7){for(let i=0;i<n;i++)particles.push({p:[...p],s:[.045,.045,.045],c:color,g:1,v:[(Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5],life:.25+Math.random()*.3});}
function detach(e,p){const b=partBox(e,p);debris.push({...b,p:[...b.p],v:[(Math.random()-.5)*4,2.8,(Math.random()-.5)*4],life:8,a:Math.random()*6});p.hp=0;}
function kill(e){if(e.dead)return;e.dead=true;stopRobotSounds(e);robotSound(e,'death');kills++;if(e.boss){stageStats.boss=true;score+=wave===10?40000:20000;}else{stageStats.kills[e.typeIndex]++;score+=e.type.hp*10;}for(const p of e.parts)if(p.hp>0)detach(e,p);sparks([e.p[0],e.scale,e.p[2]],C.amber,15);dropHealth(e);dropAmmo(e);log(e.type.name+' 제압 +'+(e.boss?(wave===10?40000:20000):e.type.hp*10));updateHud();}
function shoot(){if(state!=='play'||sprinting||sprintBlend>.15||cooldown>0||reload>0)return;if(ammo===0){if(weapon===2){log('RPG 탄약이 없습니다 · 주황 보급품을 획득하세요');fire=false;}else beginReload();return;}ammo--;if(weapon===2)rpgAmmo=ammo;else magazines[weapon]=ammo;shots++;cooldown=WEAPONS[weapon].delay;recoil=weapon===3?.18:weapon===1?.1:.07;if(weapon===2){playerOrdnance.push(makeRocket());sound(140,.3,.17,true);fire=false;updateHud();return;}if(weapon===3){fireShotgun();return;}if(weapon===1)fire=false;let spread=aim?.0018:.009;const dir=norm([-Math.sin(yaw)*Math.cos(pitch)+(Math.random()-.5)*spread,Math.sin(pitch)+(Math.random()-.5)*spread,-Math.cos(yaw)*Math.cos(pitch)]);let hit=trace(pos,dir),impact=pos.map((v,i)=>v+dir[i]*hit.t);const muzzle=[pos[0]+Math.cos(yaw)*.22-Math.sin(yaw)*.6,pos[1]-.15,pos[2]-Math.sin(yaw)*.22-Math.cos(yaw)*.6];const muzzleDelta=muzzle.map((v,i)=>v-pos[i]);const nearWall=trace(pos,norm(muzzleDelta),false,Math.hypot(...muzzleDelta));if(nearWall.obj){hit=nearWall;impact=pos.map((v,i)=>v+norm(muzzleDelta)[i]*hit.t);}else{const toImpact=impact.map((v,i)=>v-muzzle[i]),gunHit=trace(muzzle,norm(toImpact),true,Math.hypot(...toImpact)+.02);if(gunHit.obj){hit=gunHit;impact=muzzle.map((v,i)=>v+norm(toImpact)[i]*hit.t);}}sparks(impact,hit.obj?.e?C.amber:C.metal,hit.obj?6:0);if(hit.obj?.e){hits++;hitTimer=.12;const p=hit.obj,damage=WEAPONS[weapon].damage*(p.name==='머리'?1.3:1);applyDamage(p,damage);sound(920,.06,.028);}pitch=clamp(pitch+.003,-1.35,1.35);sound(1800,.10,.12,true);updateHud();}

function shotgunDamage(distance,melee=false){const multiplier=distance<=3?2.5:distance<=8?2.5-(distance-3)*.3:distance<=16?1-(distance-8)*.0875:.3;return WEAPONS[3].damage*multiplier*(melee?1.6:1);}
function fireShotgun(){
 const forward=norm([-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)]),right=[Math.cos(yaw),0,-Math.sin(yaw)],up=[Math.sin(yaw)*Math.sin(pitch),Math.cos(pitch),Math.cos(yaw)*Math.sin(pitch)];
 const muzzle=pos.map((v,j)=>v+forward[j]*.6+right[j]*.22-up[j]*.15),toMuzzle=muzzle.map((v,j)=>v-pos[j]),blocked=trace(pos,norm(toMuzzle),false,Math.hypot(...toMuzzle));
 let landed=false;
 for(let i=0;i<WEAPONS[3].pellets;i++){
  const fan=(i-4)/4*(aim?.08:.13),rise=i===4?0:Math.sin(i*2.4)*(aim?.012:.025),dir=norm(forward.map((v,j)=>v+right[j]*fan+up[j]*rise));
  const cameraHit=trace(pos,dir,true,24),target=pos.map((v,j)=>v+dir[j]*cameraHit.t),delta=target.map((v,j)=>v-muzzle[j]),ray=norm(delta),hit=blocked.obj?blocked:trace(muzzle,ray,true,Math.hypot(...delta)+.001);
  const origin=blocked.obj?pos:muzzle,direction=blocked.obj?norm(toMuzzle):ray,impact=origin.map((v,j)=>v+direction[j]*hit.t);
  if(!blocked.obj&&hit.t>.02)particles.push({...box(origin.map((v,j)=>v+direction[j]*hit.t*.5),[.018,.018,hit.t],[1,.72,.24],Math.atan2(direction[0],direction[2]),1.7),tilt:-Math.asin(clamp(direction[1],-1,1)),v:[0,0,0],life:.16});
  sparks(impact,hit.obj?.e?C.amber:C.metal,hit.obj?3:0);
  if(hit.obj?.e){landed=true;const distance=Math.hypot(...impact.map((v,j)=>v-pos[j]));applyDamage(hit.obj,shotgunDamage(distance,hit.obj.e.type.melee)*(hit.obj.name==='머리'?1.2:1));}
 }
 if(landed){hits++;hitTimer=.16;sound(760,.07,.045);}pitch=clamp(pitch+.018,-1.35,1.35);sound(115,.28,.19,true);fire=false;updateHud();
}
function canMove(x,z,r=.38){if(Math.abs(x)>21.4-r||z>29.4-r||z<(-60*(totalStages()-1)-29.4+r))return false;for(const b of obstacles){if(b.open||b.s[1]<.4||b.p[1]-b.s[1]/2>3)continue;if(Math.abs(x-b.p[0])<b.s[0]/2+r&&Math.abs(z-b.p[2])<b.s[2]/2+r)return false;}return true;}
function move(p,dx,dz,r){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.18));for(let i=0;i<steps;i++){if(canMove(p[0]+dx/steps,p[2],r))p[0]+=dx/steps;if(canMove(p[0],p[2]+dz/steps,r))p[2]+=dz/steps;}}
function damagePlayer(amount,source=null){if(state!=='play'||combatTime<invulnerableUntil||sectorCleared&&wave===totalStages())return;invulnerableUntil=combatTime+.001;shieldTimer=0;if(source&&mode!=='ranked'){threatSource=[...source];threatTimer=1.4;}const absorbed=Math.min(shield,amount);shield-=absorbed;amount-=absorbed;if(absorbed>0){sound(880,.10,.04);log(amount>0?'실드 파괴 · '+Math.ceil(amount)+' 피해':'실드가 공격을 흡수했습니다');}if(amount>0){hp=Math.max(0,hp-amount);damageTimer=.28;$('damage').style.opacity='1';sound(70,.16,.065);if(hp<=0)finish(false);}updateHud();}
function updateShield(dt){shieldTimer+=dt;const capacity=shieldCapacity();if(shieldTimer<SHIELD_DELAY||hp<=0||shield>=capacity)return;shield=capacity;log('방어 실드 충전 · '+capacity);sound(820,.24,.035);updateHud();}
function update(dt){if(state!=='play')return;lastDt=dt;combatTime+=dt;updateReinforcements();updateSpawnQueue(dt);updateCombatExtras(dt);elapsed=mode==='ranked'?(rankResult?rankResult.elapsedMs/1000:(performance.now()-rankStart)/1000):elapsed+dt;collectHealth();updateShield(dt);threatTimer=Math.max(0,threatTimer-dt);if(mode!=='ranked'&&threatTimer>0&&threatSource){const dx=threatSource[0]-pos[0],dz=threatSource[2]-pos[2],right=Math.cos(yaw)*dx-Math.sin(yaw)*dz,forward=-Math.sin(yaw)*dx-Math.cos(yaw)*dz;const bearing=Math.atan2(right,forward);$('threat').style.opacity='1';$('threatarrow').style.transform='rotate('+bearing+'rad)';$('threattext').textContent=(forward<0?'후방':Math.abs(right)>Math.abs(forward)?(right>0?'오른쪽':'왼쪽'):'전방')+' 공격 · '+Math.round(Math.hypot(dx,dz))+'m';}else $('threat').style.opacity='0';if(sectorCleared&&wave<totalStages()){const distance=Math.max(0,Math.round(pos[2]-(-31-(wave-1)*60)));$('objective').textContent='↓ 다음 구역 · '+distance+'m';}else $('objective').textContent='전방 적을 모두 제압하세요';feet+=dt*5;cooldown=Math.max(0,cooldown-dt);recoil=Math.max(0,recoil-dt*.5);hitTimer=Math.max(0,hitTimer-dt);damageTimer=Math.max(0,damageTimer-dt);noticeTimer-=dt;feedTimer-=dt;if(noticeTimer<=0)$('notice').textContent='';if(feedTimer<=0)$('feed').textContent='';$('hit').style.opacity=hitTimer>0?1:0;$('damage').style.opacity=clamp(damageTimer/.28,0,1);let fw=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joystick[1],rt=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joystick[0],l=Math.max(1,Math.hypot(fw,rt));sprinting=(keys.has('ShiftLeft')||keys.has('ShiftRight')||sprintTouch)&&Math.hypot(fw,rt)>.1;if(sprinting)aim=false;sprintBlend+=(Number(sprinting)-sprintBlend)*Math.min(1,dt*10);const speed=sprinting?SPRINT_SPEED:5.8*(aim?.57:1);stepTimer-=dt;if(sprinting&&stepTimer<=0){sound(85,.10,.035,true);stepTimer=.17;}$('sprintstatus').textContent=sprinting?'SPRINT · 32 m/s':'SHIFT · 질주';$('runscore').textContent=score.toLocaleString()+' PT · '+formatTime(elapsed*1000);move(pos,(-Math.sin(yaw)*fw+Math.cos(yaw)*rt)*speed*dt/l,(-Math.cos(yaw)*fw-Math.sin(yaw)*rt)*speed*dt/l,.35);if(pos[1]>1.7||jumpV>0){jumpV-=15*dt;pos[1]+=jumpV*dt;if(pos[1]<1.7){pos[1]=1.7;jumpV=0;}}if(reload>0){reload-=dt;if(reload<=0){reload=0;ammo=WEAPONS[weapon].capacity;if(weapon!==2)magazines[weapon]=ammo;sound(500,.07,.025,true);updateHud();}}updateOrdnance(dt);if(fire)shoot();
for(const e of enemies){if(state!=='play')break;if(e.dead)continue;e.attackAnim=Math.max(0,(e.attackAnim||0)-dt);if(e.dropping){e.p[1]=Math.max(0,e.p[1]-28*dt);if(e.p[1]===0){e.dropping=false;sparks(e.p,C.amber,8);robotSound(e,'move');}continue;}if(e.boss){updateBoss(e,dt);continue;}updateEnemy(e,dt);}
updateBossAttacks(dt);for(let i=bolts.length-1;i>=0;i--){const b=bolts[i];if(b.kind==='missile'){b.age=(b.age||0)+dt;const arcTime=b.arcTime??.65,target=b.age<arcTime?[pos[0],b.targetLift===undefined?6:pos[1]+b.targetLift,pos[2]]:pos;const desired=norm(target.map((v,j)=>v-b.p[j]));const old=norm(b.v),turn=Math.min(1,dt*(b.turnRate??2.4));b.v=norm(old.map((v,j)=>v*(1-turn)+desired[j]*turn)).map(v=>v*(b.speed||22));}const prev=[...b.p],speed=Math.hypot(...b.v),d=b.v.map(v=>v/speed),travel=speed*dt;const wall=projectileWall(prev,d,travel+.001,b.radius||0);const r=b.radius||0,body=box([pos[0],pos[1]-.45,pos[2]],[.7+r*2,1.25+r*2,.7+r*2],C.dark),playerT=rayBox(prev,d,body);if(playerT!==null&&playerT<=travel&&(!wall.obj||playerT<wall.t)){if(b.kind==='missile')explode(b,prev.map((v,j)=>v+d[j]*playerT));else damagePlayer(b.damage,b.source);bolts.splice(i,1);continue;}if(wall.obj){const impact=prev.map((v,j)=>v+d[j]*wall.t);if(b.kind==='missile')explode(b,impact);sparks(impact,C.amber,4);bolts.splice(i,1);continue;}b.p=b.p.map((v,j)=>v+b.v[j]*dt);b.life-=dt;if(b.life<=0){if(b.kind==='missile')explode(b,b.p);bolts.splice(i,1);}}
for(const arr of [particles,debris])for(let i=arr.length-1;i>=0;i--){const b=arr[i];b.life-=dt;b.v[1]-=9*dt;for(let j=0;j<3;j++)b.p[j]+=b.v[j]*dt;if(b.p[1]<b.s[1]/2){b.p[1]=b.s[1]/2;b.v[1]=Math.abs(b.v[1])*.18;b.v[0]*=.88;b.v[2]*=.88;}if(arr===debris)b.a+=dt*b.v[0];if(b.life<=0)arr.splice(i,1);}
updateRobotAudio(dt);advanceSector();
const d=[-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)],t=trace(pos,d);if(t.obj?.e){const e=t.obj.e,p=t.obj;$('target').textContent=e.type.name+' · '+p.name+' '+(p.name==='코어'||p.name==='장갑'?Math.ceil(e.hp):Math.ceil(p.hp))+' HP';}else $('target').textContent='';
}
// Armor plates and joints follow the destructible part, so every detail detaches with it.
function robotDetail(b,offset,size,color,kind='box',glow=0){const c=Math.cos(b.a),s=Math.sin(b.a),p=[b.p[0]+c*offset[0]+s*offset[2],b.p[1]+offset[1],b.p[2]-s*offset[0]+c*offset[2]];draw({...box(p,size,color,b.a,glow),kind});}
function drawRobot(e,time){if(e.variant){drawVariant(e,time);return;}if(e.type.quad){drawQuadruped(e,time);return;}if(e.boss){drawBoss(e,time);return;}const S=e.scale,accent=e.type.accent,white=[.86,.91,.85],joint=[.09,.12,.15];for(const part of e.parts)if(part.hp>0){let b=partBox(e,part);const damaged=part.hp<part.max*.5&&part.name!=='코어';const color=damaged?e.type.c.map(x=>x*.65):e.type.c;const detail=(off,size,c,kind='box',g=0)=>robotDetail(b,off.map(x=>x*S),size.map(x=>x*S),c,kind,g);
 if(part.shield){draw({...b,c:[.27,.16,.43]});detail([0,0,.11],[1.03,1.78,.08],accent);detail([0,0,.17],[.75,1.42,.05],joint);detail([0,.73,.20],[.80,.06,.04],C.blue,'box',1.4);detail([-.38,.87,.18],[.76*part.hp/part.max,.045,.04],C.lime,'box',1.5);
 }else if(part.name==='머리'){draw({...b,c:color});detail([0,.25,0],[.29,.12,.32],accent);detail([0,-.01,.205],[.28,.39,.065],joint);detail([0,0,.247],[.23,.23,.035],[.38,.025,.035],'cylinder');detail([0,0,.273],[.15,.15,.035],[1,.005,.018],'cylinder',2.2);detail([0,0,.296],[.055,.09,.02],[1,.12,.16],'cylinder',1.5);detail([0,-.25,.2],[.24,.08,.06],white);
 }else if(part.name==='코어'){draw({...b,c:joint});detail([-.23,.13,.02],[.23,.40,.44],color);detail([.23,.13,.02],[.23,.40,.44],color);detail([0,0,.245],[.44,.44,.11],accent,'cylinder');detail([0,0,.31],[.31,.31,.035],joint,'cylinder');detail([0,0,.34],[.13,.13,.04],C.amber,'cylinder',.6);detail([0,-.25,.05],[.61,.15,.43],color);detail([0,.34,0],[.15,.12,.17],joint);
 }else if(part.name.includes('팔')){draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.55)),c:joint});detail([0,.26,0],[.37,.29,.36],color);detail([0,.29,.20],[.25,.14,.07],accent);detail([0,-.02,.02],[.25,.23,.33],white,'cylinder');detail([0,-.27,0],[.33,.25,.34],color);detail([0,-.28,.21],[.14,.14,.12],joint,'cylinder');if(e.type.melee)detail([0,-.28,.49],[.07,.08,.48],C.blue,'box',1.3);if(mode!=='ranked'&&e.warning>0)detail([0,-.28,.30],[.15,.15,.04],C.red,'cylinder',2.5);
 }else {draw({...b,s:b.s.map((v,i)=>v*(i===1?1:.6)),c:joint});detail([0,.20,0],[.26,.27,.30],color);detail([0,-.025,.08],[.25,.22,.22],accent,'cylinder');detail([0,-.23,0],[.27,.28,.30],color);detail([0,-.34,.04],[.27,.12,.31],white);}}
 const top=2.57*S+e.p[1];draw(box([e.p[0],top,e.p[2]],[.85*S,.05,.035],C.dark));draw(box([e.p[0]-(1-e.hp/e.max)*.425*S,top,e.p[2]+.025],[.85*S*clamp(e.hp/e.max,0,1),.055,.035],e.type.c,0,.8));}
function render(time){let eye=pos,y=yaw,p=pitch;if(state==='menu'){eye=[17,6.1,22];y=.43+Math.sin(time*.00008)*.10;p=-.13;}
const fov=state==='play'&&aim?.70:1.18+sprintBlend*.22;gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.045,.085,.09,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,multiply(projection(fov),view(eye,y,p)));gl.uniform3fv(U.Eye,eye);gl.uniform1f(U.Fog,.020);for(const b of world)if(Math.abs(b.p[2]-eye[2])<85)draw(b);
drawVents(time);for(const e of enemies)if(!e.dead&&!(e.dropDelay>0)){if(state==='menu')e.angle=Math.atan2(eye[0]-e.p[0],eye[2]-e.p[2]);drawRobot(e,time);}for(const item of pickups){const h=.55+Math.sin(time*.003)*.12,c=item.kind==='rpg'?C.amber:item.kind==='grenade'?C.blue:C.lime;draw(box([item.p[0],h,item.p[2]],[.65,.42,.50],c.map(v=>v*.55),time*.001));if(item.kind){draw({...box([item.p[0],h+.35,item.p[2]],[item.kind==='rpg'?.15:.24,.15,item.kind==='rpg'?.75:.25],c,0,1),kind:'cylinder'});}else{draw(box([item.p[0],h+.26,item.p[2]],[.13,.10,.44],c,0,1.2));draw(box([item.p[0],h+.26,item.p[2]],[.44,.10,.13],c,0,1.2));}draw(box([item.p[0],.03,item.p[2]],[.9,.035,.9],c.map(v=>v*.5),0,.3));}
if(sectorCleared&&wave<totalStages()){const z=-30-(wave-1)*60;for(const x of [-3.9,3.9])draw(box([x,2,z],[.12,4,.12],C.lime,0,1.5));}
drawBossAttacks(time);drawCombatExtras(time);for(const arr of [debris,bolts,particles,playerOrdnance])for(const b of arr)draw(b);
if(state!=='menu'){gl.clear(gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(U.VP,false,projection(1.0));gl.uniform3fv(U.Eye,[0,0,0]);gl.uniform1f(U.Fog,0);const moving=state==='play'&&(keys.has('KeyW')||keys.has('KeyA')||keys.has('KeyS')||keys.has('KeyD')||Math.hypot(...joystick)>.1);let bob=moving?Math.sin(time*.013)*.008:Math.sin(time*.002)*.002;let reloadDrop=reload>0?Math.sin((WEAPONS[weapon].reload-reload)/Math.max(.01,WEAPONS[weapon].reload)*Math.PI)*.35:0;for(const b of weaponModels[weapon]){const t=-.58*sprintBlend,gy=b.p[1]+(aim?-.10:0),gz=b.p[2]+recoil;draw({...b,tilt:t,p:[b.p[0]-(aim?.24:0)+Math.sin(time*.024)*.045*sprintBlend,gy*Math.cos(t)-gz*Math.sin(t)+bob-reloadDrop-.12*sprintBlend+Math.sin(time*.032)*.04*sprintBlend,gy*Math.sin(t)+gz*Math.cos(t)+.12*sprintBlend]});}drawRedDotSight(aim&&!sprinting);if(punchTimer>0){draw(box([-.20,-.12,-.40-Math.sin(punchTimer/.35*Math.PI)*.35],[.20,.20,.24],[.25,.3,.22]));}if(recoil>.046&&!sprinting){draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.085],[.085,.085,.19],C.amber,time*.1,2));draw(box([.24-(aim?.24:0),-.174+(aim?.065:0),-1.1],[.14,.025,.14],C.lime,0,3));}}
}
function resize(){let d=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(innerWidth*d);canvas.height=Math.round(innerHeight*d);}window.addEventListener('resize',resize);resize();
$('start').onclick=start;$('retry').onclick=start;$('resume').onclick=resume;$('quit').onclick=toMenu;$('back').onclick=toMenu;$('sensitivity').oninput=e=>sensitivity=Number(e.target.value);document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{chosenDifficulty=difficulty=Number(b.dataset.d);document.querySelectorAll('[data-d]').forEach(x=>x.classList.toggle('active',x===b));});
window.addEventListener('keydown',e=>{if(e.target?.tagName==='INPUT')return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&state==='play'){pause();return;}if(state!=='play')return;keys.add(e.code);if(e.code==='KeyR')beginReload();if(!e.repeat&&e.code==='KeyF')punch();if(!e.repeat&&e.code==='KeyG')throwGrenade();if(['Digit1','Digit2','Digit3','Digit4'].includes(e.code))switchWeapon(Number(e.code.slice(-1))-1);if(e.code==='Space'&&pos[1]<=1.71)jumpV=6;});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{if(state==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='play')pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='play'&&!lockedFallback&&!touch)pause();});document.addEventListener('pointerlockerror',()=>{lockedFallback=true;announce('화면을 드래그해 조준하세요',4);});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('mousedown',e=>{if(state!=='play'||e.target!==canvas)return;if(!touch&&document.pointerLockElement!==canvas)lock();if(e.button===0)fire=true;if(e.button===2)aim=true;});window.addEventListener('mouseup',e=>{if(e.button===0)fire=false;if(e.button===2)aim=false;});window.addEventListener('mousemove',e=>{if(state==='play'&&(document.pointerLockElement===canvas||lockedFallback&&e.buttons)){yaw-=e.movementX*.002*sensitivity*(aim?.6:1);pitch=clamp(pitch-e.movementY*.002*sensitivity*(aim?.6:1),-1.35,1.35);}});
canvas.style.touchAction='none';canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&state==='play'){lookPointer=e.pointerId;lastLook=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);}});canvas.addEventListener('pointermove',e=>{if(e.pointerId===lookPointer){yaw-=(e.clientX-lastLook[0])*.005;pitch=clamp(pitch-(e.clientY-lastLook[1])*.005,-1.35,1.35);lastLook=[e.clientX,e.clientY];}});for(const ev of ['pointerup','pointercancel'])canvas.addEventListener(ev,e=>{if(e.pointerId===lookPointer)lookPointer=null;});
const stick=$('stick');function stickMove(e){const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,y=(e.clientY-r.top-r.height/2)/38,l=Math.max(1,Math.hypot(x,y));joystick=[x/l,y/l];stick.firstElementChild.style.transform=`translate(${joystick[0]*28}px,${joystick[1]*28}px)`;}let stickId=null;stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);stickMove(e);};stick.onpointermove=e=>{if(e.pointerId===stickId)stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{stickId=null;joystick=[0,0];stick.firstElementChild.style.transform='';};$('touchfire').onpointerdown=e=>{e.preventDefault();fire=true;$('touchfire').setPointerCapture(e.pointerId);};$('touchfire').onpointerup=$('touchfire').onpointercancel=()=>fire=false;$('touchreload').onclick=beginReload;$('touchpause').onclick=pause;$('touchswap').onclick=()=>switchWeapon((weapon+1)%4);$('touchgrenade').onclick=throwGrenade;$('touchpunch').onclick=punch;$('touchsprint').onpointerdown=e=>{e.preventDefault();sprintTouch=true;$('touchsprint').setPointerCapture(e.pointerId);};$('touchsprint').onpointerup=$('touchsprint').onpointercancel=()=>sprintTouch=false;
function activeParts(e,fragment){return e.parts.filter(p=>p.hp>0&&p.name.includes(fragment));}
function spawnBoss(x,z,final){const e={boss:true,final,type:{name:final?'OMEGA':'WARDEN',c:final?[.8,.14,.36]:[.96,.57,.1],accent:[.1,.75,.95],hp:final?8500:4200},p:[x,0,z],parts:[],hp:final?8500:4200,max:final?8500:4200,scale:final?3.1:2.5,angle:0,age:0,phase:0,dead:false,timer:3,pattern:0,warning:0,attackName:'접근 중',windup:null};
part(e,'장갑',[0,1.2,0],[.94,1.05,.60],1e9);part(e,'머리',[0,2.62,0],[.4,.65,.4],final?650:420);e.parts.at(-1).noScore=true;
part(e,'가슴 코어',[0,1.55,.36],[.44,.48,.18],final?800:550);
for(const [side,x]of [['왼',-.8],['오른',.8]]){part(e,side+'어깨',[x*(final?1.35:1),2.05,0],[final?1.3:.55,.55,.58],final?550:330);part(e,side+'팔',[x*1.1,1.19,0],[.42,1.1,.43],final?450:320);part(e,side+'다리',[x*.48,.43,0],[.40,.83,.48],final?500:350);}
if(final){part(e,'왼날개',[-1.9,2.1,-.65],[2.1,1.8,.2],650);part(e,'오른날개',[1.9,2.1,-.65],[2.1,1.8,.2],650);part(e,'왼체인소',[-1.15,1.0,.55],[.22,.42,1.75],480);part(e,'오른체인소',[1.15,1.0,.55],[.22,.42,1.75],480);part(e,'드론 제어기',[0,2.45,-.40],[.5,.35,.35],600);part(e,'드론 방패',[0,2,1],[1.05,.9,.15],1000,C.blue);e.parts.at(-1).shield=true;e.parts.at(-1).drone=true;}enemies.push(e);return e;}
function cancelBrokenPattern(e){if(e.final){if(!activeParts(e,'드론 제어기').length){const p=e.parts.find(p=>p.drone);if(p&&p.hp>0){p.hp=0;destroyPart(e,p);}}if(activeParts(e,'날개').length<2)e.aerial=0;}if(!activeParts(e,'가슴 코어').length){stopRobotSounds(e,'laser');for(let i=lasers.length-1;i>=0;i--)if(lasers[i].owner===e)lasers.splice(i,1);if(e.windup===2){e.windup=null;e.warning=0;e.timer=.6;e.attackName='코어 파괴 · 레이저 불능';}}}
const PATTERNS=['돌진 휩쓸기','유도탄 난사','광역 레이저','탄환 연사','칼날 부채꼴','공중 미사일 포화'];
function patternAvailable(e,p){return p===0||p===1&&activeParts(e,'어깨').length||p===2&&activeParts(e,'가슴 코어').length||p===3&&activeParts(e,'팔').length||p===4&&activeParts(e,'다리').length||p===5&&e.final&&activeParts(e,'날개').length===2&&activeParts(e,'어깨').length;}
function updateBoss(e,dt){e.age+=dt;updateBossBasic(e,dt);updateDroneShield(e,dt);const dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],distance=Math.hypot(dx,dz),legs=activeParts(e,'다리').length;
 if(e.aerial>0){e.aerial=Math.max(0,e.aerial-dt);e.p[1]=Math.min(10,e.p[1]+dt*16);e.airShot=(e.airShot||0)-dt;if(e.airShot<=0){airBarrage(e);e.airShot=.55;}e.angle=Math.atan2(dx,dz);if(e.aerial>1)move(e.p,-dz/(distance||1)*dt*5,dx/(distance||1)*dt*5,.7*e.scale);if(e.aerial<=1&&!e.landingWarning){e.landingWarning=true;e.landingHold=Math.max(.7,e.aerial);e.landingPoint=[...e.p];}updateBossHud(e);return;}
 if(e.p[1]>0){if(!e.landingWarning){e.landingWarning=true;e.landingHold=.75;e.landingPoint=[...e.p];}if(e.landingHold>0){e.landingHold-=dt;updateBossHud(e);return;}e.p[1]=Math.max(0,e.p[1]-dt*16);if(e.p[1]===0){emitShockwave(e.p,12,24,16,e);e.landingWarning=false;}updateBossHud(e);return;}
 if(!sweeps.some(a=>a.owner===e))e.angle=Math.atan2(dx,dz);
 if(e.charge>0){e.charge-=dt;chase(e,(e.final?29:25)*(legs===2?1:legs===1?.6:.2),dt,Math.max(2,sweepRadius(e)*.48));if(distance<sweepRadius(e)*.55||e.charge<=0){e.charge=0;e.sweepDelay=e.final?.52:.65;e.attackName='휩쓸기 준비';}updateBossHud(e);return;}
 if(e.sweepDelay>0){e.sweepDelay-=dt;if(e.sweepDelay<=0){e.sweepDelay=0;sweeps.push({owner:e,life:e.final?2.5:2.2,hitTimer:0});robotSound(e,'sweep');}updateBossHud(e);return;}
 e.sawTick=(e.sawTick||0)-dt;const saws=activeParts(e,'체인소').length;if(saws&&distance<4+saws*.6&&e.sawTick<=0&&lineOfSight([e.p[0],1.2,e.p[2]],pos)){damagePlayer(12+saws*3,e.p);e.sawTick=.16;robotSound(e,'blades');}
 if(distance>5&&e.windup===null&&!lasers.some(a=>a.owner===e)&&!sweeps.some(a=>a.owner===e))chase(e,(e.final?7:5)*(legs===2?1:legs===1?.45:.08),dt,5);
 if(e.windup!==null){e.warning-=dt;if(e.warning<=0){const p=e.windup;e.windup=null;if(patternAvailable(e,p))executeBossPattern(e,p);e.timer=e.final?1.15:2.0;}}
 else{e.timer-=dt;if(e.timer<=0&&!lasers.some(a=>a.owner===e)&&!sweeps.some(a=>a.owner===e)){const count=e.final?6:5;const options=Array.from({length:count},(_,i)=>i).filter(i=>patternAvailable(e,i)&&i!==e.lastPattern);const p=options.length?options[Math.floor(Math.random()*options.length)]:0;e.lastPattern=p;e.windup=p;e.warning=e.final?.45:.75;e.attackName=PATTERNS[p];if(mode!=='ranked'){announce(e.type.name+' · '+PATTERNS[p],1.3);alertAttack(e);}}}updateBossHud(e);}
function updateBossHud(e){$('boss').classList.remove('hidden');$('bossname').textContent=e.type.name+(e.aerial>0?' · 공중 방어막 · 피해 80% 감소':mode==='ranked'?'':' · '+e.attackName);$('bosshp').style.width=(e.hp/e.max*100)+'%';$('bossparts').textContent=e.parts.filter(p=>p.name!=='장갑').map(p=>p.name+(p.hp>0?' '+Math.ceil(p.hp):' ×')).join(' / ');}
function queueBoss(owner,delay,fn){scheduled.push({owner,delay,fn});}
function bossProjectile(e,origin,direction,speed,damage,kind='bolt'){bolts.push({p:[...origin],v:norm(direction).map(v=>v*speed),s:kind==='blade'?[.7,.11,.14]:kind==='missile'?[.23,.23,.65]:[.16,.16,.22],c:kind==='blade'?C.blue:kind==='missile'?C.amber:C.red,g:1.5,life:kind==='missile'?6:4,kind,age:0,speed,damage,source:[...e.p]});}
function executeBossPattern(e,p){if(!patternAvailable(e,p))return;if(p!==0)robotSound(e,['sweep','missiles','laser','burst','blades','missiles'][p]);
if(p===0){e.charge=1.5;return;}
if(p===1){for(const shoulder of activeParts(e,'어깨'))for(let i=0;i<(e.final?6:4);i++)queueBoss(e,i*(e.final?.10:.16)+(shoulder.local[0]>0?.08:0),()=>{if(shoulder.hp<=0)return;const o=partBox(e,shoulder).p;o[1]+=.7;bossProjectile(e,o,[Math.sin(e.angle)*.5,1,Math.cos(e.angle)*.5],e.final?27:22,e.final?28:24,'missile');sound(500,.15,.12,true,o);});}
if(p===2)lasers.push({owner:e,life:3,age:0,angle:e.angle-.5,tick:0});
if(p===3){const base=activeParts(e,'팔').length===2?3:activeParts(e,'팔').length,n=base*(e.final?2:1);for(let i=0;i<n;i++)queueBoss(e,i*(e.final?.12:.2),()=>{const arms=activeParts(e,'팔');if(!arms.length||i>=(arms.length===2?3:arms.length)*(e.final?2:1))return;const o=partBox(e,arms[i%arms.length]).p;bossProjectile(e,o,pos.map((v,j)=>v-o[j]),e.final?30:28,e.final?22:18);sound(600,.12,.17,true,o);});}
if(p===4){for(const leg of activeParts(e,'다리'))for(let i=-(e.final?3:2);i<=(e.final?3:2);i++){const o=partBox(e,leg).p;o[1]=.95;const a=e.angle+i*.18;bossProjectile(e,o,[Math.sin(a),0,Math.cos(a)],29,16,'blade');}sound(1000,.22,.1,true,e.p);}if(p===5){e.aerial=10;e.airShot=0;e.landingWarning=false;e.landingHold=0;stopRobotSounds(e);robotSound(e,'missiles');}}
function fireLizardLaser(e){if(e.laserGuide||lasers.some(l=>l.owner===e&&l.mouth))return;const head=e.parts.find(p=>p.name==='머리'&&p.hp>0);if(!head)return;const origin=partBox(e,head).p;e.laserGuide={life:.9,dir:norm(pos.map((v,j)=>v-origin[j]))};sound(720,.24,.055,false,e.p);}
function updateLizardGuide(e,dt){const guide=e.laserGuide;if(!guide)return false;const head=e.parts.find(p=>p.name==='머리'&&p.hp>0);if(!head){e.laserGuide=null;return true;}const origin=partBox(e,head).p;if(guide.life>.25)guide.dir=norm(pos.map((v,j)=>v-origin[j]));guide.life-=dt;if(guide.life<=0){lasers.push({owner:e,life:.9,age:0,tick:0,mouth:true,dir:[...guide.dir]});e.laserGuide=null;robotSound(e,'attack');sound(135,.2,.09,false,e.p);}return true;}
function lizardGuideData(e){const head=e.parts.find(p=>p.name==='머리'&&p.hp>0),dir=e.laserGuide?.dir;if(!head||!dir)return null;const origin=partBox(e,head).p,hit=trace(origin,dir,false,32);return {origin,dir,length:hit.t};}
function beamData(l){const e=l.owner,core=e.parts.find(p=>p.name===(l.mouth?'머리':'가슴 코어'));const origin=partBox(e,core).p;if(l.mouth){const dir=l.dir||norm([Math.sin(l.angle),l.elevation||0,Math.cos(l.angle)]),hit=trace(origin,dir,false,32);return {origin,dir,length:hit.t};}const a=l.angle+l.age*.35,dir=norm([Math.sin(a),-.065,Math.cos(a)]),hit=trace(origin,dir,false,42);return {origin,dir,length:hit.t};}
function lineOfSight(a,b){const d=b.map((v,j)=>v-a[j]),distance=Math.hypot(...d);return !trace(a,norm(d),false,Math.max(0,distance-.03)).obj;}
function explode(b,point){sparks(point,C.amber,20);const d=Math.hypot(pos[0]-point[0],pos[1]-point[1],pos[2]-point[2]);if(d<3.2&&lineOfSight(point,pos))damagePlayer(b.damage*(1-d/4.5),b.source);sound(70,.35,.13,true,point);}
function updateBossAttacks(dt){$('boss').classList.toggle('hidden',!enemies.some(e=>e.boss&&!e.dead));for(let i=scheduled.length-1;i>=0;i--){const a=scheduled[i];a.delay-=dt;if(a.owner.dead){scheduled.splice(i,1);continue;}if(a.delay<=0){a.fn();scheduled.splice(i,1);}}
for(let i=sweeps.length-1;i>=0;i--){const a=sweeps[i],e=a.owner;if(e.dead){sweeps.splice(i,1);continue;}a.life-=dt;a.hitTimer-=dt;e.angle+=dt*7;const radius=sweepRadius(e),dist=Math.hypot(pos[0]-e.p[0],pos[2]-e.p[2]);if(dist<radius&&a.hitTimer<=0&&lineOfSight([e.p[0],1.2,e.p[2]],pos)){damagePlayer(e.final?35:25,e.p);a.hitTimer=e.final?.4:.65;}if(a.life<=0)sweeps.splice(i,1);}
for(let i=lasers.length-1;i>=0;i--){const l=lasers[i];if(l.owner.dead||!activeParts(l.owner,l.mouth?'머리':'가슴 코어').length){lasers.splice(i,1);continue;}l.life-=dt;l.age+=dt;l.tick-=dt;const {origin,dir,length}=beamData(l),delta=pos.map((v,j)=>v-origin[j]),along=dot(delta,dir),off=Math.hypot(...delta.map((v,j)=>v-dir[j]*along));if(along>0&&along<length&&off<(l.mouth?.5:1.45)&&l.tick<=0&&lineOfSight(origin,pos)){damagePlayer(7,l.owner.p);l.tick=.18;}if(l.tick<=0){sound(135,.16,.04,false,l.owner.p);l.tick=.18;}if(l.life<=0)lasers.splice(i,1);}}
function drawBoss(e,time){const S=e.scale;for(const p of e.parts)if(p.hp>0){const b=partBox(e,p);if(p.name.includes('날개')){drawWing(e,p,b,time);continue;}draw({...b,c:p.shield?C.blue:p.name==='장갑'?[1,.58,.14]:e.type.c,g:p.name==='장갑'?.45:0});drawBossPartDetail(e,p,b,time);if(p.name==='머리')robotDetail(b,[0,0,.22*S],[.23*S,.23*S,.05*S],C.red,'cylinder',2.2);if(p.name==='가슴 코어')robotDetail(b,[0,0,.12*S],[.32*S,.35*S,.06*S],C.red,'cylinder',1.6);if(p.name.includes('어깨'))for(let i=0;i<(e.final?8:4);i++)robotDetail(b,[(i%(e.final?4:2)-(e.final?1.5:.5))*.25*S,(Math.floor(i/(e.final?4:2))-.5)*.22*S,.31*S],[.17*S,.17*S,.05*S],C.dark,'cylinder');if(p.name.includes('다리'))robotDetail(b,[0,-.12*S,.26*S],[.28*S,.14*S,.035*S],C.blue);}
 if(e.aerial>0)drawAerialShield(e,time);if(e.landingWarning&&!e.dead)drawGroundRing(e.landingPoint,12,C.amber,1+Math.sin(time*.02)*.4);
 if(mode!=='ranked'&&(e.windup!==null||e.sweepDelay>0))drawRing(e.p,e.windup===0||e.sweepDelay>0?sweepRadius(e):2.8,e.sweepDelay>0?C.blue:[1,.17,.05],time);
}
function drawRing(p,r,c,time){for(let i=0;i<40;i++){const a=i/40*Math.PI*2;draw(box([p[0]+Math.sin(a)*r,.055,p[2]+Math.cos(a)*r],[.28,.055,.28],c,a,.7+Math.sin(time*.015)*.25));}}
function drawAerialShield(e,time){const S=e.scale,r=2.05*S,y=e.p[1]+1.35*S,pulse=.18+Math.sin(time*.008)*.035;for(let i=0;i<14;i++){const a=i/14*Math.PI*2+time*.00025,shield=box([e.p[0]+Math.sin(a)*r,y,e.p[2]+Math.cos(a)*r],[.10*S,3.4*S,1.05*S],C.blue,a,1.8);shield.alpha=pulse;draw(shield);}for(const height of [-.4,3.1])for(let i=0;i<14;i++){const a=i/14*Math.PI*2-time*.00018,shield=box([e.p[0]+Math.sin(a)*r,y+height*S,e.p[2]+Math.cos(a)*r],[.42*S,.08*S,.42*S],C.blue,a,2.2);shield.alpha=.28;draw(shield);}}
function drawBossAttacks(time){for(const e of enemies)if(e.laserGuide&&!e.dead){const head=activeParts(e,'머리')[0];if(head){const b=partBox(e,head),off=(head.s[2]/2+.09)*e.scale,point=[b.p[0]+Math.sin(e.angle)*off,b.p[1]-.08*e.scale,b.p[2]+Math.cos(e.angle)*off],size=.10+.05*Math.max(0,Math.sin(time*.035));draw({...box(point,[size,size,size],[1,.9,.02],0,1.4),kind:'sphere'});}}for(const a of sweeps)if(!a.owner.dead){const e=a.owner,r=sweepRadius(e);if(mode!=='ranked')drawRing(e.p,r,C.amber,time);for(let i=0;i<8;i++){const a=e.angle+i*.16;draw(box([e.p[0]+Math.sin(a)*r*.7,1.2,e.p[2]+Math.cos(a)*r*.7],[.24,.20,r*.55],C.amber,a,1));}}for(const l of lasers){const {origin,dir,length}=beamData(l);for(let t=0;t<length;t+=.8)draw(box(origin.map((v,j)=>v+dir[j]*t),l.mouth?[.38,.38,.8]:[1.7,1.3,.8],l.mouth?[.4,1,.08]:[1,.025,.065],l.angle+l.age*.35,1.6));}}
function formatTime(ms){const total=Math.floor(ms/1000);return Math.floor(total/60)+':'+String(total%60).padStart(2,'0')+'.'+Math.floor(ms%1000/100);}
// Browser-only records. No account, API, or database is required.
const RANK_KEY='iron-sector.ranking.v4', RECORD_LIMIT=100;
function compareRecords(a,b){return b.score-a.score||a.elapsedMs-b.elapsedMs||a.createdAt-b.createdAt||a.id.localeCompare(b.id);}
function validateRecords(data){
 if(!data||data.game!=='iron-sector'||data.version!==4||!Array.isArray(data.records)||data.records.length>RECORD_LIMIT)throw Error('지원하지 않거나 손상된 기록 파일입니다.');
 const ids=new Set();return data.records.map(r=>{
 if(!r||typeof r.id!=='string'||!/^[a-zA-Z0-9_-]{1,80}$/.test(r.id)||ids.has(r.id)||typeof r.name!=='string'||!r.name.trim()||[...r.name].length>16||/[\u0000-\u001f\u007f]/.test(r.name)||!Number.isSafeInteger(r.score)||r.score<0||r.score>10000000||!Number.isSafeInteger(r.elapsedMs)||r.elapsedMs<1||r.elapsedMs>604800000||!Number.isSafeInteger(r.createdAt)||r.createdAt<0)throw Error('유효하지 않은 기록입니다. 기존 기록은 변경하지 않았습니다.');
 ids.add(r.id);if(r.outcome!==undefined&&!['clear','dead'].includes(r.outcome)||r.stage!==undefined&&(!Number.isInteger(r.stage)||r.stage<1||r.stage>10))throw Error('유효하지 않은 결과입니다.');return {id:r.id,name:r.name.trim(),score:r.score,elapsedMs:r.elapsedMs,createdAt:r.createdAt,outcome:r.outcome||'clear',stage:r.stage||10};}).sort(compareRecords);
}
function readRecords(){try{const raw=localStorage.getItem(RANK_KEY);return raw===null?[]:validateRecords(JSON.parse(raw));}catch(e){throw Error('기록을 읽지 못했습니다. 브라우저 저장 허용 여부와 기존 데이터를 확인하세요.');}}
function recordDocument(records){return {game:'iron-sector',version:4,records};}
function writeRecords(records){const checked=validateRecords(recordDocument(records));try{localStorage.setItem(RANK_KEY,JSON.stringify(recordDocument(checked)));}catch{throw Error('저장 공간이 부족하거나 브라우저가 저장을 차단했습니다. 저장을 허용하고 다시 등록하거나 이번 기록을 백업하세요.');}return checked;}
function mergeRecords(current,incoming){const map=new Map(current.map(r=>[r.id,r]));for(const r of incoming)if(!map.has(r.id))map.set(r.id,r);return [...map.values()].sort(compareRecords).slice(0,RECORD_LIMIT);}
function checkpointRank(outcome='clear'){if(outcome==='dead'&&wave===rankCheckpoints.length){rankCheckpoints.afterClearDeath=true;rankResult=Object.freeze({id:rankRun,score,elapsedMs:Math.max(1,Math.round(performance.now()-rankStart)),createdAt:Date.now(),stage:wave,outcome});return;}if(wave!==rankCheckpoints.length+1)return;const entry={stage:wave,kills:[...stageStats.kills],parts:stageStats.parts,bossParts:stageStats.bossParts,boss:stageStats.boss,outcome};rankCheckpoints.push({...entry,synced:false});if(wave===10||outcome==='dead')rankResult=Object.freeze({id:rankRun,score,elapsedMs:Math.max(1,Math.round(performance.now()-rankStart)),createdAt:Date.now(),stage:wave,outcome});if(rankRemote){const id=rankRemote,entries=rankCheckpoints,epoch=runEpoch;rankSync=rankSync.catch(()=>{}).then(()=>syncCloudRank(id,entries,epoch));rankSync.catch(()=>{});}}
async function syncCloudRank(id=rankRemote,entries=rankCheckpoints,epoch=runEpoch){if(!id)return;for(const entry of entries){if(entry.synced)continue;const {synced,...payload}=entry,result=await window.IronCloud.checkpoint(id,payload);entry.synced=true;if(epoch===runEpoch&&result.outcome!=='playing')rankCloudResult=result;}if(entries.afterClearDeath){const result=await window.IronCloud.finish(id);if(epoch===runEpoch)rankCloudResult=result;}}
function prepareRankResult(){if(!rankResult)return;$('rankform').classList.remove('hidden');$('submitrank').disabled=false;$('stats').textContent=rankResult.score.toLocaleString()+'점 · '+formatTime(rankResult.elapsedMs)+' · '+rankResult.stage+' / 10 '+(rankResult.outcome==='dead'?'전사':'클리어');$('submitstatus').textContent=rankRemote?'이름을 입력하면 온라인 랭킹에 등록합니다.':'오프라인 기록입니다. 이름을 입력해 이 기기에 저장하세요.';}
function namedResult(){const name=$('playername').value.trim();if(!name||[...name].length>16||/[\u0000-\u001f\u007f]/.test(name))throw Error('이름을 1~16자로 입력하세요.');if(!rankResult)throw Error('종료된 작전 기록이 필요합니다.');return {...rankResult,name};}
function renderBoardRows(rows){$('boardrows').replaceChildren();for(const [i,row]of rows.entries()){const tr=document.createElement('tr');for(const value of [String(i+1),row.name,row.score.toLocaleString(),formatTime(row.elapsedMs),row.stage+'/10 · '+(row.outcome==='dead'?'전사':'클리어')]){const td=document.createElement('td');td.textContent=value;tr.appendChild(td);}$('boardrows').appendChild(tr);}}
async function showLeaderboard(){if(state==='play')pause();$('leaderboard').classList.remove('hidden');$('boardrows').replaceChildren();const scope=boardScope;$('boardstatus').textContent='기록을 불러오는 중…';$('boardscope').value=scope;try{const rows=scope==='cloud'?(await window.IronCloud.board()).rows:readRecords();if(scope!==boardScope)return;renderBoardRows(rows);$('boardstatus').textContent=(scope==='cloud'?'온라인 공동 랭킹':'이 기기의 기록')+' · 점수 우선 / 동점은 짧은 시간 우선'+(rows.length?'':' · 등록된 기록이 없습니다.');}catch(e){if(scope===boardScope)$('boardstatus').textContent='불러오기 실패: '+e.message;}}
function downloadRecords(records){const blob=new Blob([JSON.stringify(recordDocument(records),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='iron-sector-ranking-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importRecords(text){const incoming=validateRecords(JSON.parse(text));return writeRecords(mergeRecords(readRecords(),incoming));}
$('rankform').onsubmit=async event=>{event.preventDefault();if($('submitrank').disabled)return;const epoch=runEpoch,id=rankRemote,entries=rankCheckpoints;try{const row=namedResult();$('submitrank').disabled=true;let localError='';try{writeRecords(mergeRecords(readRecords(),[row]));}catch(e){localError=e.message;}if(id){$('submitstatus').textContent='온라인 기록을 확인하고 등록하는 중…';await rankSync.catch(()=>{});await syncCloudRank(id,entries,epoch);const saved=await window.IronCloud.submit(id,row.name);if(epoch!==runEpoch)return;boardScope='cloud';$('submitstatus').textContent='온라인 등록 완료 · '+saved.score.toLocaleString()+'점';}else{if(localError)throw Error(localError);boardScope='local';$('submitstatus').textContent='이 기기에 저장했습니다. 온라인 기록에는 포함되지 않습니다.';}showLeaderboard();}catch(e){if(epoch===runEpoch){$('submitstatus').textContent=e.message+(id?' 온라인 등록을 다시 시도할 수 있습니다.':'');$('submitrank').disabled=false;}}};
$('boardscope').onchange=e=>{boardScope=e.target.value;showLeaderboard();};
$('backupresult').onclick=()=>{try{downloadRecords([namedResult()]);$('submitstatus').textContent='이번 기록을 파일로 백업했습니다.';}catch(e){$('submitstatus').textContent=e.message;}};
$('exportrecords').onclick=()=>{try{downloadRecords(readRecords());}catch(e){$('boardstatus').textContent=e.message;}};
$('importrecords').onclick=()=>$('recordfile').click();
$('recordfile').onchange=async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>262144)throw Error('기록 파일은 256KB 이하여야 합니다.');importRecords(await file.text());boardScope='local';showLeaderboard();$('boardstatus').textContent='불러오기 완료 · 중복을 제외하고 상위 100개를 저장했습니다.';}catch(e){$('boardstatus').textContent='불러오기 실패: '+e.message;}finally{event.target.value='';}};
window.addEventListener('storage',e=>{if(boardScope==='local'&&e.key===RANK_KEY&&!$('leaderboard').classList.contains('hidden'))showLeaderboard();});
function installBossChallengeButtons(){const original=document.querySelector?.('.modechoice');if(!original||document.querySelector?.('[data-boss-challenge]'))return;const row=document.createElement('div');row.className='modechoice';row.dataset.bossChallenge='true';row.style.marginTop='8px';for(const [value,label]of [['boss5','5 보스 도전'],['boss10','10 보스 도전']]){const button=document.createElement('button');button.type='button';button.dataset.mode=value;button.textContent=label;row.appendChild(button);}original.insertAdjacentElement('afterend',row);}
installBossChallengeButtons();
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{if(state==='starting')return;mode=button.dataset.mode;const challenge=bossChallengeStage();difficulty=mode==='standard'?chosenDifficulty:2;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('[data-d]').forEach(b=>b.disabled=mode!=='standard');$('modedesc').textContent=mode==='ranked'?'10 스테이지 · 5/10 보스 · 극한 고정 · 공격 경고 없음 · 클리어/전사 기록':challenge?(challenge===5?'WARDEN 단독 도전 · 5스테이지 장비/체력':'OMEGA 단독 도전 · 10스테이지 장비/체력'):'5 스테이지 · 난이도 선택';$('rankstatus').textContent='';});$('openboard').onclick=showLeaderboard;$('closeboard').onclick=()=>$('leaderboard').classList.add('hidden');$('refreshboard').onclick=showLeaderboard;

function waveRoster(stage,gameMode){const bossStage=gameMode==='ranked'&&stage%5===0,count=gameMode==='ranked'?(bossStage?4:4+stage):3+stage*2,unlocked=stage===1?[0,1]:stage===2?[0,1,3]:stage===3?[0,1,2,3,4]:[0,1,2,3,4,5],roster=Array.from({length:count},(_,i)=>unlocked[(i+stage-1)%unlocked.length]);for(let i=roster.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[roster[i],roster[j]]=[roster[j],roster[i]];}return roster.map(base=>{const variant=stage>=3&&base===2?'hammer':stage>=2&&base===0?'booster':stage>=2&&base===1?'head':stage>=3&&base===4?'bug':null;return variant&&Math.random()<.6?{base,variant}:base;});}
function randomizeArena(){for(const arr of [world,obstacles])for(let i=arr.length-1;i>=0;i--)if(arr[i].randomCover)arr.splice(i,1);vents.length=0;for(let sector=0;sector<10;sector++){const z=-sector*60;for(const x of [-8,8])for(const dz of [-12,-22])vents.push({x,z:z+dz,sector});if(sector===4||sector===9)vents.push({x:0,z:z-20,sector,boss:true});const begin=world.length;for(const side of [-1,1])for(const row of [0,1,2]){let x=side*(6.5+Math.random()*8);const depth=z+16-row*13+(Math.random()-.5)*4;if(vents.some(v=>v.sector===sector&&Math.abs(v.x-x)<4.5&&Math.abs(v.z-depth)<4.5))x=side*16;container(x,depth,3+Math.random()*1.5,2.2,2.2+Math.random()*.8,[.22+Math.random()*.1,.28,.26]);if(row===1){add([x,3.7,depth+2],[5,.35,6],C.dark,0,0,true);for(const dx of [-2.2,2.2])add([x+dx,1.85,depth+4.5],[.28,3.7,.28],C.metal,0,0,true);}}for(let i=begin;i<world.length;i++)world[i].randomCover=true;}}
function drawVents(time){for(const v of vents){if(Math.abs(v.z-pos[2])>80&&state!=='menu')continue;const y=(v.sector===4||v.sector===9)?22:11.4;draw(box([v.x,y+.1,v.z],[3.8,.25,3.8],C.dark));for(const x of [-1.7,1.7])draw(box([v.x+x,y-.12,v.z],[.18,.25,3.5],C.amber,0,.8));for(const z of [-1.7,1.7])draw(box([v.x,y-.12,v.z+z],[3.5,.25,.18],C.amber,0,.8));draw(box([v.x,y+.26,v.z],[2.8,.12,2.8],[.005,.008,.009]));}if(state==='menu')return;for(const e of enemies)if(e.dropping){for(const x of [-.5,.5])draw(box([e.p[0]+x,e.p[1]+e.scale*2.5,e.p[2]],[.09,1.4,.09],C.blue,0,2));}}
function updateSpawnQueue(dt){for(let i=spawnQueue.length-1;i>=0;i--){const a=spawnQueue[i];a.delay-=dt;if(a.delay>0)continue;const e=a.boss?spawnBoss(a.p[0],a.p[2],a.final):spawn(a.type,a.p[0],a.p[2]);e.p[1]=(wave===5||wave===10)?22-e.scale*2.5:12;e.dropping=true;spawnQueue.splice(i,1);updateHud();}}
function spawnQuad(type,x,z){const t=types[type],m=[.72,1,1.45][difficulty]*(1+(wave-1)*.12),e={type:t,typeIndex:type,p:[x,0,z],parts:[],hp:t.hp*m,max:t.hp*m,scale:t.scale,timer:1.5,phase:Math.random()*6,gait:0,dead:false,angle:0,age:0,warning:0};const walker=t.kind==='walker';part(e,'코어',[0,walker?1.25:.7,0],walker?[.9,.65,.95]:[.65,.5,1.5],999);part(e,'머리',[0,walker?1.7:.82,walker?.24:1.0],walker?[.38,.52,.4]:[.42,.5,.62],t.head*m);for(const x of [-1,1])for(const z of [-1,1])part(e,(x<0?'왼':'오른')+(z>0?'앞':'뒷')+'다리',[x*(walker?.9:.57),.38,z*(walker?.65:.58)],[walker?.28:.20,.7,.26],t.leg*m);if(walker)part(e,'발사 코어',[0,1.78,0],[.55,.5,.55],150*m);if(t.kind==='super'){part(e,'왼등팔',[-.43,1.30,.1],[.18,.62,.23],t.arm*m);part(e,'오른등팔',[.43,1.30,.1],[.18,.62,.23],t.arm*m);}enemies.push(e);return e;}
function chase(e,speed,dt,reach){const dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],distance=Math.hypot(dx,dz);if(distance<=reach)return;const nx=dx/(distance||1),nz=dz/(distance||1),ox=e.p[0],oz=e.p[2],radius=(e.type.quad?.6:.45)*e.scale;move(e.p,nx*speed*dt,nz*speed*dt,radius);if(Math.hypot(e.p[0]-ox,e.p[2]-oz)<speed*dt*.3){const side=Math.sin(e.phase||1)>0?1:-1;move(e.p,-nz*speed*dt*side,nx*speed*dt*side,radius);}e.gait=(e.gait||0)+Math.hypot(e.p[0]-ox,e.p[2]-oz)*(e.type.quad?5:4);}
function updateEnemy(e,dt){if(updateVariant(e,dt))return;e.age+=dt;if(e.type.kind==='lizard'&&updateLizardGuide(e,dt))return;const dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],dist=Math.hypot(dx,dz),legs=activeParts(e,'다리').length,arms=activeParts(e,'팔').length,total=e.type.quad?4:2;const targetAngle=Math.atan2(dx,dz),turn=Math.atan2(Math.sin(targetAngle-e.angle),Math.cos(targetAngle-e.angle));e.angle=e.typeIndex===2?e.angle+clamp(turn,-dt*.9,dt*.9):targetAngle;const origin=partBox(e,e.parts.find(p=>p.name==='머리')).p,blocked=!lineOfSight(origin,pos),sp=e.type.speed*([.75,1,1.18][difficulty])*(legs===total?1:legs?Math.max(.25,legs/total*.7):.10);if(!lasers.some(l=>l.owner===e))chase(e,sp,dt,blocked?0:e.type.melee?1.15:e.type.quad?14:arms?8:1.3);for(const other of enemies){if(other===e||other.dead||other.dropping)continue;const sx=e.p[0]-other.p[0],sz=e.p[2]-other.p[2],sl=Math.hypot(sx,sz),minimum=.45*(e.scale+other.scale);if(sl>0&&sl<minimum)move(e.p,sx/sl*dt,sz/sl*dt,.45*e.scale);}e.timer-=dt;if(e.warning>0){e.warning-=dt;if(e.warning<=0)fireEnemy(e,arms);}else if(e.age>.6&&e.timer<=0&&!blocked&&(e.typeIndex!==2||Math.abs(turn)<.45)&&dist<(e.type.melee?2.25:25)){e.timer=(e.type.rate*([1.3,1,.8][difficulty])+(e.type.melee?.15:.5))*(.75+Math.random()*.5);e.warning=mode==='ranked'?.08:e.type.melee?.16:.55;alertAttack(e);}}
function drawQuadruped(e,time){const S=e.scale,walker=e.type.kind==='walker',superScout=e.type.kind==='super';for(const p of e.parts)if(p.hp>0){const b=partBox(e,p);draw({...b,c:p.name==='코어'?C.dark:e.type.c});if(p.name.includes('다리')){const side=Math.sign(p.local[0]),knee=[side*.2*S,.24*S,0];robotDetail(b,knee,[.35*S,.26*S,.38*S],e.type.c,'cylinder');robotDetail(b,[side*.15*S,.4*S,-Math.sign(p.local[2])*.1*S],[.55*S,.13*S,.26*S],e.type.accent);robotDetail(b,[0,-.3*S,.09*S],[.30*S,.13*S,.42*S],C.dark);}
 if(p.name==='머리'){robotDetail(b,[0,.06*S,.33*S],[.12*S,.29*S,.04*S],C.red,'box',2.5);if(!walker){robotDetail(b,[0,-.17*S,.35*S],[.48*S,.11*S,.34*S],e.type.c);robotDetail(b,[0,-.09*S,.40*S],[.25*S,.09*S,.09*S],C.dark);}}
 if(p.name==='코어'){robotDetail(b,[0,.30*S,0],[.62*S,.14*S,walker?.65*S:1.30*S],e.type.c);if(!walker){for(let i=0;i<4;i++)robotDetail(b,[0,.08*S,-(.85+i*.25)*S],[(.25-i*.04)*S,.15*S,.32*S],e.type.c);for(let i=0;i<3;i++)robotDetail(b,[0,.43*S,(i*.35-.4)*S],[.10*S,.30*S,.24*S],e.type.accent);}else{robotDetail(b,[0,.35*S,0],[.66*S,.66*S,.66*S],C.blue,'cylinder',1);}}
 if(p.name==='발사 코어')robotDetail(b,[0,.30*S,0],[.32*S,.08*S,.32*S],C.dark,'cylinder');
 if(p.name.includes('등팔')){robotDetail(b,[0,.12*S,.25*S],[.12*S,.14*S,.50*S],e.type.c);robotDetail(b,[0,.08*S,.54*S],[.045*S,.10*S,.38*S],C.amber,'box',1.2);}}
 const top=e.p[1]+(walker?2.25:superScout?1.95:1.65)*S;draw(box([e.p[0],top,e.p[2]],[1.15*S,.045,.03],C.dark));draw(box([e.p[0]-(1-e.hp/e.max)*.575*S,top,e.p[2]+.02],[1.15*S*clamp(e.hp/e.max,0,1),.05,.03],e.type.c,0,1));}
function shieldFaces(e,p,d){return p.drone?true:d[0]*Math.sin(e.angle)+d[2]*Math.cos(e.angle)<-.05;}
function sweepRadius(e){return 3+activeParts(e,'팔').length*3+activeParts(e,'체인소').length*1.5;}
function updateDroneShield(e,dt){if(!e.final||!activeParts(e,'드론 제어기').length)return;const drone=e.parts.find(p=>p.drone&&p.hp>0);if(!drone)return;const candidates=e.parts.filter(p=>p.hp>0&&!p.shield&&p.name!=='장갑'&&p.name!=='드론 제어기');candidates.sort((a,b)=>a.hp/a.max-b.hp/b.max);const target=candidates[0];if(!target)return;e.protectedPart=target.name;const desired=[target.local[0],target.local[1],target.local[2]+.65];for(let j=0;j<3;j++)drone.local[j]+=clamp(desired[j]-drone.local[j],-dt*16,dt*16);}
function airBarrage(e){if(!activeParts(e,'어깨').length)return;for(const shoulder of activeParts(e,'어깨'))for(let i=0;i<3;i++){const origin=partBox(e,shoulder).p,spread=(i-1)*.2;bossProjectile(e,origin,[Math.sin(e.angle+spread)*.4,-.35,Math.cos(e.angle+spread)*.4],27,24,'missile');}robotSound(e,'missiles');}
function drawBossPartDetail(e,p,b,time){const S=e.scale;if(p.name.includes('날개')){for(let i=0;i<3;i++)robotDetail(b,[Math.sign(p.local[0])*i*.16*S,-i*.2*S,-.15*S],[.22*S,1.1*S,.12*S],e.type.accent);robotDetail(b,[0,-.55*S,-.18*S],[.3*S,(e.aerial>0?1.1:.2)*S,.3*S],C.blue,'cylinder',2);}
 if(p.name.includes('체인소')){for(let i=0;i<10;i++){const z=(-.75+i*.16+(time*.002%1)*.1)*S;for(const x of [-.16,.16])robotDetail(b,[x*S,0,z],[.1*S,.12*S,.09*S],C.amber,'box',.8);}robotDetail(b,[0,.24*S,0],[.14*S,.08*S,1.6*S],C.dark);}
 if(p.drone){for(const x of [-.6,.6])robotDetail(b,[x*S,0,0],[.22*S,.22*S,.25*S],C.dark,'cylinder');robotDetail(b,[0,0,.12*S],[.88*S,.75*S,.04*S],[.15,.8,1],'box',1);}
 if(p.name==='장갑'){robotDetail(b,[0,.2*S,.38*S],[.7*S,.35*S,.16*S],[1,.78,.2],'box',.65);for(const x of [-.35,.35])robotDetail(b,[x*S,.5*S,.32*S],[.14*S,.25*S,.12*S],e.type.accent);}}

// Combat extensions stay local; new archetypes retain their original score category.
const reinforcements=[],shockwaves=[],blastMarks=[];
let ordnancePreview=null,previewClock=0;
function resetCombatExtras(){reinforcements.length=shockwaves.length=blastMarks.length=0;ordnancePreview=null;previewClock=0;}
function randomVentPoint(){const choices=vents.filter(v=>v.sector===wave-1&&!v.boss),far=choices.filter(v=>Math.hypot(v.x-pos[0],v.z-pos[2])>9),v=(far.length?far:choices)[Math.floor(Math.random()*(far.length||choices.length))];return v?[v.x+(Math.random()-.5)*1.2,0,v.z+(Math.random()-.5)*1.2]:[0,0,-60*(wave-1)-20];}
function updateReinforcements(){if(!reinforcements.length||spawnQueue.length||enemies.filter(e=>!e.dead&&!e.boss).length>2)return;const batch=reinforcements.splice(0,3);batch.forEach((a,i)=>spawnQueue.push({...a,p:randomVentPoint(),delay:.65+i*.45}));updateHud();}
function configureVariant(e,kind){e.variant=kind;e.type={...e.type};e.timer=1+Math.random()*2;e.specialTimer=2+Math.random()*2;
 if(kind==='hammer'){e.type.name='해머 중장갑형';e.type.c=[.95,.53,.08];e.type.melee=true;e.type.speed=1.6;const p=e.parts.find(p=>p.shield);p.name='망치';p.shield=false;p.local=[.85,1.1,.7];p.s=[.8,.45,.6];}
 if(kind==='booster'){e.type.name='부스터 정찰형';e.type.c=[.1,.85,.45];part(e,'부스터',[0,1.38,-.4],[.62,.6,.3],80,[.2,.55,.9]);e.parts.at(-1).noScore=true;}
 if(kind==='head'){e.type.name='부유 모노아이';e.type.c=[.8,.8,.95];e.type.speed=2.4;e.scale=1.35;const p=e.parts.find(p=>p.name==='머리');e.parts=[p];p.local=[0,.5,0];p.s=[.6,.85,.6];p.hp=p.max=e.max;e.hover=true;}
 if(kind==='bug'){e.type.name='촉수 포격충';e.type.c=[.65,.16,.65];e.type.speed=.35;for(const p of e.parts)if(p.name.includes('다리')){p.name=p.name.replace('다리','촉수');p.s=[.24,.24,.9];p.local[1]=.5;}e.parts.find(p=>p.name==='발사 코어').name='탄막 기관';}
}
function energyBall(e,origin,target,speed=8,damage=8,radius=.65){if(!lineOfSight(origin,target))return;bossProjectile(e,origin,target.map((v,j)=>v-origin[j]),speed,damage,'energy');const b=bolts.at(-1);Object.assign(b,{kind:'energy',s:[radius*2,radius*2,radius*2],radius,c:[.95,.24,.65],life:6,g:1.1});robotSound(e,'attack');}
function updateBossBasic(e,dt){e.basicTimer=(e.basicTimer??(3+Math.random()*2))-dt;if(e.aerial>0||e.landingWarning||e.charge>0||e.sweepDelay>0||e.basicTimer>0)return;const head=activeParts(e,'머리')[0];if(head){const b=partBox(e,head),o=[b.p[0]+Math.sin(e.angle)*.28*e.scale,b.p[1],b.p[2]+Math.cos(e.angle)*.28*e.scale];energyBall(e,o,pos,8,8,.85);}e.basicTimer=3.5+Math.random()*2;}
function emitShockwave(p,radius,damage,speed,owner){shockwaves.push({p:[p[0],.15,p[2]],radius,damage,speed,owner,r:0,hit:false});sound(55,.35,.13,true,p);sparks(p,C.amber,16);}
function projectileWall(origin,d,max,radius=0){if(!radius)return trace(origin,d,false,max);let t=max,obj=null;for(const b of world){if(!b.blocksShots||b.open)continue;const hit=rayBox(origin,d,{...b,s:b.s.map(v=>v+radius*2)});if(hit!==null&&hit<t){t=hit;obj=b;}}return {t,obj};}
function updateCombatExtras(dt){for(let i=shockwaves.length-1;i>=0;i--){const w=shockwaves[i],before=w.r;w.r+=w.speed*dt;const d=Math.hypot(pos[0]-w.p[0],pos[2]-w.p[2]);if(!w.hit&&d>=before-.65&&d<=Math.min(w.radius,w.r)+.65&&pos[1]<2.65&&lineOfSight([w.p[0],.6,w.p[2]],pos)){damagePlayer(w.damage,w.p);w.hit=true;}if(w.r>=w.radius)shockwaves.splice(i,1);}for(let i=blastMarks.length-1;i>=0;i--)if((blastMarks[i].life-=dt)<=0)blastMarks.splice(i,1);previewClock-=dt;}
function updateVariant(e,dt){if(!e.variant)return false;e.age+=dt;e.timer-=dt;e.specialTimer-=dt;const dx=pos[0]-e.p[0],dz=pos[2]-e.p[2],distance=Math.hypot(dx,dz);e.angle=Math.atan2(dx,dz);
 if(e.variant==='booster'){
  if(e.kick){const k=e.kick;k.time+=dt;const prev=[...e.p];if(!activeParts(e,'부스터').length){e.kick=null;e.p[1]=Math.max(0,e.p[1]-dt*12);e.specialTimer=6;return true;}const u=clamp(k.time/k.duration,0,1);move(e.p,k.dir[0]*k.speed*dt,k.dir[2]*k.speed*dt,.4*e.scale);e.p[1]=Math.sin(u*Math.PI)*3;const delta=e.p.map((v,j)=>v-prev[j]),len=Math.hypot(...delta),contact=rayBox(prev,norm(delta),box([pos[0],pos[1]-.6,pos[2]],[1.4,2.2,1.4],C.dark));if(!k.hit&&contact!==null&&contact<=len&&lineOfSight(prev,pos)){damagePlayer(18,e.p);k.hit=true;robotSound(e,'attack');}if(u>=1){e.p[1]=0;e.kick=null;e.specialTimer=3.5+Math.random()*3;}return true;}
  e.p[1]=Math.max(0,e.p[1]-dt*12);if(distance>7&&distance<28&&e.specialTimer<=0&&activeParts(e,'부스터').length&&activeParts(e,'다리').length&&lineOfSight([e.p[0],1.5,e.p[2]],pos)){e.kick={time:0,duration:.85,speed:Math.min(26,Math.max(8,(distance-1)/.85)),dir:norm([dx,0,dz]),hit:false};robotSound(e,'move');return true;}chase(e,e.type.speed*(activeParts(e,'다리').length/2||.1),dt,1.1);if(distance<2.25&&e.timer<=0&&lineOfSight([e.p[0],1.2,e.p[2]],pos)){fireEnemy(e,activeParts(e,'팔').length);e.timer=.75+Math.random()*.65;}return true;
 }
 if(e.variant==='hammer'){if(e.slam>0){e.slam-=dt;if(e.slam<=0&&activeParts(e,'망치').length){emitShockwave(e.p,7,22,12,e);e.attackAnim=.36;}return true;}chase(e,e.type.speed*(activeParts(e,'다리').length/2||.1),dt,2);if(distance<6&&e.timer<=0){if(activeParts(e,'망치').length&&Math.random()<.8){e.slam=.8;robotSound(e,'attack');}else if(distance<2.5)fireEnemy(e,activeParts(e,'팔').length);e.timer=2.2+Math.random()*1.5;}return true;}
 if(e.variant==='head'){e.p[1]=1.5+Math.sin(e.age*1.7)*.4;chase(e,2.4,dt,12);if(e.timer<=0){const head=activeParts(e,'머리')[0];if(head)energyBall(e,partBox(e,head).p,pos,7,7,.55);e.timer=2.5+Math.random()*2;}return true;}
 if(e.variant==='bug'){const origin=[e.p[0],1,e.p[2]],tentacles=activeParts(e,'촉수');if(distance>25)chase(e,.35,dt,25);if(e.tentacleWindup>0){e.tentacleWindup-=dt;if(e.tentacleWindup<=0&&tentacles.length){e.attackAnim=.36;if(distance<5.5&&lineOfSight(origin,pos))damagePlayer(10+tentacles.length*2,e.p);}return true;}if(e.timer<=0){if(distance<5.5&&tentacles.length&&Math.random()<.8){e.tentacleWindup=.5;robotSound(e,'attack');}else if(activeParts(e,'탄막 기관').length&&lineOfSight(origin,pos)){const n=Math.random()<.5?5:7;for(let i=0;i<n;i++){const a=e.angle+(i-(n-1)/2)*.15;bossProjectile(e,origin,[Math.sin(a),(pos[1]-origin[1])/(distance||1),Math.cos(a)],9,5);}robotSound(e,'attack');}e.timer=1.5+Math.random();}return true;}
 return false;
}
function drawVariant(e,time){const S=e.scale;for(const p of e.parts)if(p.hp>0){let b=partBox(e,p);if(p.name==='망치'){b={...b,p:[...b.p]};b.p[1]+=(e.slam>0?1.3:Math.sin((e.attackAnim||0)*9)*.4)*S;draw({...b,c:C.amber});robotDetail(b,[0,-.65*S,0],[.1*S,1.4*S,.1*S],C.metal);robotDetail(b,[0,0,.32*S],[.62*S,.25*S,.04*S],C.blue,'box',1);continue;}if(p.name==='부스터'){draw({...b,c:C.metal});for(const x of [-.2,.2]){robotDetail(b,[x*S,-.05*S,-.2*S],[.2*S,.4*S,.25*S],C.blue,'cylinder',.7);if(e.kick)robotDetail(b,[x*S,-.2*S,-.65*S],[.15*S,.2*S,.75*S],C.amber,'cylinder',2);}continue;}if(p.name.includes('촉수')){for(let i=0;i<5;i++){const side=Math.sign(p.local[0]),reach=e.attackAnim>0?i*.3:0;robotDetail(b,[side*i*.16*S,Math.sin(e.age*3+i)*.1*S,(i*.22+reach)*S],[.16*S,.16*S,.3*S],i===4?C.amber:e.type.c);}continue;}if(e.kick&&p.name.includes('다리'))b={...b,tilt:-1.1,s:[b.s[0],b.s[1]*1.25,b.s[2]]};draw({...b,c:p.name==='코어'?e.type.accent:e.type.c});if(p.name==='머리')robotDetail(b,[0,0,(p.s[2]/2+.03)*S],[.2*S,.25*S,.06*S],C.red,'cylinder',2);if(p.name==='탄막 기관')robotDetail(b,[0,.26*S,0],[.25*S,.12*S,.25*S],C.amber,'sphere',1.5);}
 if(mode!=='ranked'&&e.slam>0)drawGroundRing(e.p,7,C.amber,1);const top=e.p[1]+(e.variant==='head'?1.2:2.6)*S;draw(box([e.p[0],top,e.p[2]],[1*S,.045,.04],C.dark));draw(box([e.p[0]-(1-e.hp/e.max)*.5*S,top,e.p[2]+.03],[Math.max(.01,e.hp/e.max)*S,.045,.04],e.type.c,0,1));}
function drawWing(e,p,b,time){const S=e.scale,side=Math.sign(p.local[0]);for(let i=0;i<3;i++){const off=[side*(i-.5)*.6*S,(.35-i*.28+Math.sin(time*.002)*.035)*S,0],c=Math.cos(b.a),sn=Math.sin(b.a);draw({...box([b.p[0]+c*off[0],b.p[1]+off[1],b.p[2]-sn*off[0]],[side*1.15*S,1.35*S,.14*S],i%2?e.type.accent:e.type.c,b.a,.15),kind:'triangle'});}robotDetail(b,[0,-.45*S,0],[.18*S,.6*S,.25*S],C.blue,'cylinder',e.aerial>0?2:.5);}
function drawGroundRing(p,r,c,glow=.8){for(let i=0;i<56;i++){const a=i*Math.PI*2/56;draw(box([p[0]+Math.sin(a)*r,.07,p[2]+Math.cos(a)*r],[.16,.035,.35],c,a,glow));}}
function drawRedDotSight(ads){const x=ads?0:.24,y=ads?0:-.045,z=-.57,w=ads?.08:.047,h=ads?.064:.04,t=.008;for(const sign of [-1,1]){draw(box([x+sign*w,y,z],[t,h*2,t],C.metal));draw(box([x,y+sign*h,z],[w*2,t,t],C.metal));}draw(box([x,y-h-.015,z],[w,.025,.05],C.dark));draw({...box([x,y,z-.008],[.006,.006,.006],[1,.025,.025],0,2),kind:'sphere'});if($('cross'))$('cross').style.opacity=ads?'0':'1';}
function drawCombatExtras(time){for(const w of shockwaves)drawGroundRing(w.p,w.r,C.amber,1.7);for(const mark of blastMarks){drawGroundRing(mark.p,mark.radius,C.amber,mark.life*2);draw({...box(mark.p,[.35,.35,.35],C.amber,0,1),kind:'sphere'});}if(state!=='play')return;
 if(previewClock<=0){ordnancePreview=weapon===2&&ammo>0?predictOrdnance(makeRocket()):aim&&grenades>0?predictOrdnance(makeGrenade()):null;previewClock=.12;}if(ordnancePreview){drawOrdnancePreview(ordnancePreview,weapon===2?C.amber:C.blue);}for(const b of playerOrdnance){if(!b.preview||combatTime-(b.previewAt||0)>.15){b.preview=predictOrdnance(b);b.previewAt=combatTime;}drawOrdnancePreview(b.preview,b.kind==='rocket'?C.amber:C.blue);}}
function drawOrdnancePreview(p,c){drawGroundRing(p.p,p.radius,c,.8);draw({...box(p.p,[.18,.18,.18],c,0,1.3),kind:'sphere'});for(let i=0;i<p.path.length;i+=4)draw(box(p.path[i],[.045,.045,.045],c,0,.8));}
function makeGrenade(){const dir=norm([-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch)+.35,-Math.cos(yaw)*Math.cos(pitch)]);return {kind:'grenade',p:pos.map((v,j)=>v+dir[j]*.25),v:dir.map((v,j)=>v*13+(j===1?3:0)),s:[.2,.25,.2],c:C.blue,life:1.8,damage:300,radius:5.5};}
function makeRocket(){const dir=norm([-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)]);return {kind:'rocket',p:[...pos],v:dir.map(v=>v*42),s:[.16,.16,.6],c:C.amber,life:4,damage:650,radius:6};}
function stepOrdnance(b,dt){b.life-=dt;if(b.kind==='grenade')b.v[1]-=12*dt;const speed=Math.hypot(...b.v),dir=norm(b.v),hit=trace(b.p,dir,b.kind==='rocket',speed*dt+.01);if(hit.obj){b.p=b.p.map((v,j)=>v+dir[j]*Math.max(0,hit.t-.09));if(b.kind==='rocket')return true;if(hit.obj.p[1]+hit.obj.s[1]/2<.1){b.v[1]=Math.abs(b.v[1])*.4;b.v[0]*=.65;b.v[2]*=.65;}else{b.v[0]*=-.45;b.v[2]*=-.45;}}else b.p=b.p.map((v,j)=>v+b.v[j]*dt);return b.life<=0;}
function predictOrdnance(original){const b={...original,p:[...original.p],v:[...original.v]},path=[[...b.p]];for(let i=0;i<240;i++){const end=stepOrdnance(b,1/60);path.push([...b.p]);if(end)break;}return {p:b.p,radius:b.radius,path};}

let last=performance.now();function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;update(dt);render(t);requestAnimationFrame(frame);}toMenu();requestAnimationFrame(frame);
})();
