'use strict';
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {initializeApp}=require('firebase-admin/app');
const {getFirestore,Timestamp}=require('firebase-admin/firestore');
const {createHash}=require('node:crypto');
const V=require('./validation');
initializeApp();const db=getFirestore();
const options={region:'asia-northeast3',maxInstances:2,minInstances:0,timeoutSeconds:30,memory:'256MiB',enforceAppCheck:true,
 cors:['https://minjaninja94.github.io','https://pvefps.web.app','https://pvefps.firebaseapp.com']};
function protectedCall(handler){return onCall(options,async request=>{if(!request.auth)throw new HttpsError('unauthenticated','로그인이 필요합니다.');try{return await handler(request.auth.uid,request.data||{});}catch(e){if(e instanceof HttpsError)throw e;if(/^invalid-|^incomplete-/.test(e.message))throw new HttpsError('invalid-argument','기록 형식이 올바르지 않습니다.');throw new HttpsError('internal','기록을 처리할 수 없습니다.');}});}
function ownRun(snapshot,uid){if(!snapshot.exists||snapshot.data().uid!==uid)throw new HttpsError('permission-denied','본인의 기록만 사용할 수 있습니다.');const r=snapshot.data();if(Date.now()-r.startedAt>86400000)throw new HttpsError('failed-precondition','기록 유효 시간이 지났습니다.');return r;}
exports.startRankedRun=protectedCall(async(uid,data)=>{if(data.version!==5)throw new HttpsError('failed-precondition','게임을 새로고침하세요.');const nonce=V.identifier(data.nonce),id=createHash('sha256').update(uid+':'+nonce).digest('hex'),ref=db.collection('rankRunsV5').doc(id),limit=db.collection('rankLimitsV5').doc(uid),now=Date.now();return db.runTransaction(async tx=>{const existing=await tx.get(ref);if(existing.exists){const r=ownRun(existing,uid);if(r.ended)throw new HttpsError('failed-precondition','종료된 작전입니다.');return {id};}const snap=await tx.get(limit),old=snap.data()||{},sameHour=now-(old.window||0)<3600000;if(now-(old.lastStart||0)<10000||sameHour&&(old.count||0)>=30)throw new HttpsError('resource-exhausted','시작 제한');tx.set(limit,{window:sameHour?old.window:now,count:sameHour?(old.count||0)+1:1,lastStart:now});tx.create(ref,{uid,startedAt:now,lastStage:0,score:0,ended:false,submitted:false,expiresAt:Timestamp.fromMillis(now+86400000)});return {id};});});
exports.checkpointRankedRun=protectedCall(async(uid,data)=>{const id=V.identifier(data.id),entry=V.validateEntry(data),ref=db.collection('rankRunsV5').doc(id),checkpoint=ref.collection('stages').doc(String(entry.stage)),fingerprint=JSON.stringify(entry);return db.runTransaction(async tx=>{const snap=await tx.get(ref),r=ownRun(snap,uid),previous=await tx.get(checkpoint);if(previous.exists){if(previous.data().fingerprint!==fingerprint)throw new HttpsError('already-exists','이미 확정된 단계입니다.');return previous.data().result;}if(r.ended||entry.stage!==r.lastStage+1)throw new HttpsError('failed-precondition','단계 순서가 맞지 않습니다.');const now=Date.now(),score=r.score+V.stageScore(entry),ended=entry.outcome==='dead'||entry.stage===10,result={id,score,elapsedMs:Math.max(1,now-r.startedAt),stage:entry.stage,outcome:entry.outcome==='dead'?'dead':ended?'clear':'playing',createdAt:now};tx.create(checkpoint,{fingerprint,result,expiresAt:Timestamp.fromMillis(now+86400000)});tx.update(ref,{score,lastStage:entry.stage,ended,result});return result;});});
// Death in an already-cleared corridor: no duplicate stage points.
exports.finishRankedRun=protectedCall(async(uid,data)=>{const id=V.identifier(data.id),ref=db.collection('rankRunsV5').doc(id);return db.runTransaction(async tx=>{const r=ownRun(await tx.get(ref),uid);if(r.ended)return r.result;if(r.lastStage<1)throw new HttpsError('failed-precondition','단계 보고가 필요합니다.');const now=Date.now(),result={id,score:r.score,elapsedMs:Math.max(1,now-r.startedAt),stage:r.lastStage,outcome:'dead',createdAt:now};tx.update(ref,{ended:true,result});return result;});});
exports.submitRankedResult=protectedCall(async(uid,data)=>{const id=V.identifier(data.id),name=V.playerName(data.name),ref=db.collection('rankRunsV5').doc(id),board=db.collection('rankBoardV5').doc(id);return db.runTransaction(async tx=>{const r=ownRun(await tx.get(ref),uid);if(!r.ended)throw new HttpsError('failed-precondition','종료되지 않은 작전입니다.');const existing=await tx.get(board);if(existing.exists)return V.publicRecord(existing.data());const row={...r.result,name};tx.create(board,row);tx.update(ref,{submitted:true});return V.publicRecord(row);});});
exports.getRankedBoard=protectedCall(async()=>{const snap=await db.collection('rankBoardV5').orderBy('score','desc').orderBy('elapsedMs','asc').limit(100).get();return {rows:snap.docs.map(doc=>V.publicRecord(doc.data()))};});
