const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=fs.existsSync(path.join(__dirname,'../dist/game.js'))?path.join(__dirname,'../dist'):path.join(__dirname,'..');
function boot(uid='a',host=true){
 const els=new Map(),handlers={},packets=[];
 const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,uniform3fv:(u,v)=>assert.ok(v.every(Number.isFinite),'finite vector'),uniformMatrix4fv:(u,t,v)=>assert.ok([...v].every(Number.isFinite),'finite matrix')},{get:(o,k)=>o[k]||(()=>({}))});
 const el=id=>{if(!els.has(id)){const classes=new Set(['hidden']);els.set(id,{value:'65',textContent:'',innerHTML:'',tagName:'DIV',style:{},children:[],classList:{add:v=>classes.add(v),remove:v=>classes.delete(v),contains:v=>classes.has(v),toggle:(v,force)=>{if(force===undefined)force=!classes.has(v);force?classes.add(v):classes.delete(v);}},addEventListener(){},getContext:()=>gl,requestPointerLock(){},setPointerCapture(){},firstElementChild:{style:{}},replaceChildren(...v){this.children=v;},appendChild(v){this.children.push(v);},append(...v){this.children.push(...v);}});}return els.get(id);};
 let timer=0;const net={uid,host,peers:new Map(),room:{host:'a'},on:(key,fn)=>{(handlers[key]||=[]).push(fn);},broadcast:(p)=>packets.push(JSON.parse(JSON.stringify(p))),send:(id,p)=>{packets.push(JSON.parse(JSON.stringify(p)));return true;},leave:async()=>{},fail:e=>{throw e;}};
 const math=Object.create(Math);let seed=8;math.random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
 const ctx={console,Math:math,Date,Float32Array,Uint32Array,Map,Set,performance:{now:()=>timer},crypto:{randomUUID:()=>String(++seed),getRandomValues:a=>(a[0]=123,a)},sessionStorage:{getItem(){return null;},setItem(){}},localStorage:{getItem(){return null;},setItem(){}},requestAnimationFrame(){},fetch:async()=>({ok:false}),devicePixelRatio:1,innerWidth:1440,innerHeight:900,window:{IronMultiplayer:net,addEventListener(){}},document:{getElementById:el,querySelectorAll:()=>[],createElement:()=>({...el('elem'+(++seed)),children:[]}),addEventListener(){},exitPointerLock(){}}};ctx.globalThis=ctx;
 vm.createContext(ctx);for(const file of ['multiplayer-policy.js','multiplayer-combat.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);
 const source=fs.readFileSync(path.join(root,'game.js'),'utf8').replace(/\}\)\(\);\s*$/,`globalThis.t={multiplayer,start,toMenu,render,update,enemies,world,obstacles,gates,spawnQueue,reinforcements,shockwaves,bolts,lasers,sweeps,pickups,playerOrdnance,spawn,spawnBoss,partBox,applyDamage,fireEnemy,damagePlayer,emitShockwave,updateHud,keys,WEAPONS,setPos:p=>pos=p,setAim:(y,p)=>{yaw=y;pitch=p;},get:()=>({pos,hp,shield,wave,mode,state,score}),setWave:n=>wave=n};})();`);
 vm.runInContext(source,ctx);return {t:ctx.t,net,packets,ctx,P:ctx.window.IronLobbyPolicy,els,advance:d=>timer+=d};
}
const room=(mode,n=2)=>({mode,difficulty:1,host:'a',members:Object.fromEntries(Array.from({length:n},(_,i)=>[String.fromCharCode(97+i),{name:'Player '+i,team:i%2+1}])),session:{id:'test',seed:123,count:n,starts:0}});
(async()=>{
 const x=boot(),P=x.P,now=100000;await x.t.start();x.t.damagePlayer(10);assert.equal(x.t.get().hp,100);assert.equal(x.t.get().shield,10);x.t.update(.02);x.t.damagePlayer(30);assert.equal(x.t.get().hp,80);assert.equal(x.t.get().shield,0);x.t.toMenu();let r=P.create('a','A','coop',1,'test',now);
 assert.throws(()=>P.change(r,'a','ready',true,now));r=P.change(r,'b','join',{name:'B'},now);r=P.change(r,'b','connected',true,now);r=P.change(r,'a','ready',true,now);r=P.change(r,'b','ready',true,now);r=P.change(r,'b','propose','vote1',now);
 assert.throws(()=>P.change(r,'a','start',123,now));r=P.change(r,'a','vote',true,now);const playing=P.change(r,'a','start',123,now);assert.equal(playing.status,'playing');assert.equal(playing.session.count,2);assert.throws(()=>P.change(playing,'c','join',{name:'C'},now));
 let full=P.create('a','A','coop',1,'test',now);for(const id of ['b','c','d'])full=P.change(full,id,'join',{name:id},now);assert.throws(()=>P.change(full,'e','join',{name:'E'},now));const rejected=P.change(r,'a','vote',false,now);assert.throws(()=>P.change(rejected,'a','start',0,now));assert.throws(()=>P.change(r,'a','start',0,now+21000));const left=P.change(r,'b','leave',null,now);assert.equal(left.proposal,null);
 const a=boot(),b=boot('b',false);await a.t.multiplayer.begin(room('coop',4));await b.t.multiplayer.begin(room('coop',4));a.net.room=room('coop',4);b.net.room=room('coop',4);const am=a.t.multiplayer,bm=b.t.multiplayer;am.wait=bm.wait=0;
 assert.deepEqual(JSON.parse(JSON.stringify(a.t.world.filter(o=>o.randomCover))),JSON.parse(JSON.stringify(b.t.world.filter(o=>o.randomCover))),'seeded barricades agree');
 for(let i=0;i<90;i++)a.t.update(1/60);assert.ok(a.t.enemies.length>0);const enemy=a.t.enemies[0];assert.equal(enemy.max,enemy.type.hp*4,'4-player body health');assert.equal(enemy.parts[1].max,enemy.type.head*4,'4-player part health');
 const snapshot=a.packets.filter(p=>p.type==='snapshot').at(-1);bm.receive('a',snapshot);assert.equal(b.t.enemies.length,snapshot.enemies.length);b.t.render(1000);a.t.render(1000);assert.equal(b.t.get().mode,'coop');
 const bp=bm.players.get('b');b.t.keys.add('KeyW');for(let i=0;i<6;i++)b.t.update(1/60);assert.ok(bp.p[2]<19,'client prediction before host response');for(const p of b.packets.filter(p=>p.type==='input'))am.receive('b',p);for(let i=0;i<8;i++)a.t.update(1/60);assert.ok(am.players.get('b').ack>=6,'host acknowledges guest input');bm.receive('a',a.packets.filter(p=>p.type==='snapshot').at(-1));assert.ok(Number.isFinite(bp.p[2]));
 a.t.enemies.length=a.t.spawnQueue.length=a.t.reinforcements.length=0;const boss=a.t.spawnBoss(0,0,true);am.simulate();assert.equal(boss.max,8500*4);assert.equal(boss.parts.find(p=>p.name==='가슴 코어').max,800*4);
 const first=am.players.get('a'),second=am.players.get('b');first.p=[0,1.7,6];second.p=[0,1.7,3];first.shield=second.shield=0;first.invuln=second.invuln=0;a.t.world.length=a.t.obstacles.length=0;a.t.emitShockwave([0,0,0],7,22,12,boss);for(let i=0;i<40;i++)am.simulate();assert.ok(second.hp<100,'AoE damages guest');
 const pvp=boot(),pm=pvp.t.multiplayer;await pm.begin(room('pvp',8));pvp.net.room=room('pvp',8);pm.wait=0;assert.equal(pvp.t.spawnQueue.length,0);assert.equal(pm.players.size,8);assert.ok(pvp.t.world.length>20);pvp.t.render(1000);
 for(const p of pm.players.values()){p.invuln=0;p.p=[18,1.7,20];}const shooter=pm.players.get('a'),victim=pm.players.get('b');shooter.p=[0,1.7,10];shooter.yaw=0;victim.p=[0,1.7,0];shooter.cooldown=0;victim.shield=0;pvp.t.world.length=pvp.t.obstacles.length=0;
 pvp.t.world.push({p:[0,2,5],s:[4,4,1],blocksShots:true});pm.action(shooter,'shoot');assert.equal(victim.hp,100,'wall blocks PvP hits');pvp.t.world.length=0;shooter.cooldown=0;pm.action(shooter,'shoot');assert.ok(victim.hp<100,'PvP damage is authoritative');const ally=pm.players.get('c');ally.p=[0,1.7,5];ally.shield=0;shooter.cooldown=0;pm.action(shooter,'shoot');assert.equal(ally.hp,100,'no friendly fire');
 const hp=shooter.hp;shooter.shield=0;shooter.shieldTimer=5.99;pm.simulate();assert.equal(shooter.shield,20);assert.equal(shooter.hp,hp,'shield does not heal HP');
 shooter.rpg=1;shooter.weapon=2;shooter.cooldown=0;pm.action(shooter,'shoot');assert.equal(shooter.rpg,0);assert.equal(pvp.t.playerOrdnance.length,1);pm.action(shooter,'grenade');assert.equal(pvp.t.playerOrdnance.length,1,'grenades require pickup');
 pm.teams=[29,0];victim.hp=1;victim.invuln=0;shooter.weapon=0;shooter.cooldown=0;pm.action(shooter,'shoot');assert.equal(pm.teams[0],30);assert.ok(pm.done);assert.equal(pvp.t.get().state,'end');pm.end();pvp.t.toMenu();assert.equal(pvp.t.get().mode,'standard');await pvp.t.start();assert.equal(pvp.t.get().state,'play');
 console.log('PASS: lobby capacity/readiness/unanimity, seeded co-op maps, HP scaling, real game snapshot replication, prediction/ack, guest AoE, PvP wall hits/friendly fire, shield, ammo limits, 30-kill victory, renderer finite');
})().catch(e=>{console.error(e);process.exitCode=1;});
