const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=fs.existsSync(path.join(__dirname,'../dist/game.js'))?path.join(__dirname,'../dist'):path.join(__dirname,'..');
const docs=new Map(),watchers=new Set(),pcs=new Map();let serial=0,lock=Promise.resolve();
const clone=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
const snapshot=ref=>({exists:()=>docs.has(ref.path),data:()=>clone(docs.get(ref.path))});
function notify(){for(const w of watchers)queueMicrotask(()=>{if(watchers.has(w))w.fn(w.ref.query?{docs:[...docs].filter(([p])=>p.startsWith('mpRooms/')&&p.split('/').length===2).map(([p,v])=>({id:p.split('/')[1],data:()=>clone(v)}))}:snapshot(w.ref));});}
const sdk={doc:(db,...p)=>({path:p.join('/')}),collection:(db,...p)=>({path:p.join('/')}),where:()=>null,orderBy:()=>null,limit:()=>null,query:r=>({...r,query:true}),
 onSnapshot:(ref,fn)=>{const w={ref,fn};watchers.add(w);queueMicrotask(()=>fn(ref.query?{docs:[]}:snapshot(ref)));return()=>watchers.delete(w);},
 setDoc:async(ref,data)=>{docs.set(ref.path,clone(data));notify();},updateDoc:async(ref,data)=>{docs.set(ref.path,{...docs.get(ref.path),...clone(data)});notify();},deleteDoc:async ref=>{docs.delete(ref.path);notify();},
 runTransaction:(db,fn)=>{const next=lock.then(async()=>{const writes=[];await fn({get:async ref=>snapshot(ref),set:(ref,data)=>writes.push([ref.path,clone(data)])});for(const [p,v]of writes)docs.set(p,v);notify();});lock=next.catch(()=>{});return next;}};
class Channel{constructor(label){this.label=label;this.readyState='connecting';this.bufferedAmount=0;}send(text){queueMicrotask(()=>this.other?.onmessage?.({data:text}));}close(){this.readyState='closed';queueMicrotask(()=>this.onclose?.());}}
class RTC{constructor(){this.id='pc'+(++serial);pcs.set(this.id,this);this.iceGatheringState='complete';this.channels=[];}createDataChannel(label){const c=new Channel(label);this.channels.push(c);return c;}async createOffer(){return{type:'offer',sdp:this.id};}async createAnswer(){return{type:'answer',sdp:this.id};}async setLocalDescription(d){this.localDescription=d;}async setRemoteDescription(d){this.remoteDescription=d;if(d.type==='answer'){const other=pcs.get(d.sdp);for(const a of this.channels){const b=new Channel(a.label);a.other=b;b.other=a;other.ondatachannel({channel:b});a.readyState=b.readyState='open';queueMicrotask(()=>{a.onopen?.();b.onopen?.();});}}}close(){this.connectionState='closed';for(const c of this.channels)c.close();}addEventListener(){}removeEventListener(){}}
function boot(uid){const errors=[],events=[];const ctx={console,Date,Map,Set,Promise,Uint32Array,RTCPeerConnection:RTC,crypto:{randomUUID:()=>String(++serial).padStart(10,'0'),getRandomValues:a=>(a[0]=123,a)},setInterval:()=>0,clearInterval(){},setTimeout,clearTimeout,window:{RTCPeerConnection:RTC,IronFirebase:{identity:async()=>({db:{},fs:sdk,uid}),message:e=>e.message}}};vm.createContext(ctx);for(const file of ['multiplayer-policy.js','multiplayer.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx);const net=ctx.window.IronMultiplayer;net.on('error',e=>errors.push(e));net.on('packet',e=>events.push(e));return{net,errors,events};}
const flush=async()=>{for(let i=0;i<40;i++)await new Promise(resolve=>setImmediate(resolve));};
(async()=>{
 const a=boot('alice'),b=boot('bob');await a.net.connect('Alice');await b.net.connect('Bob');await a.net.create('pvp',1,'Room');await flush();const id=a.net.id;await b.net.join(id);await flush();assert.equal(a.net.peers.size,1);assert.equal(b.net.peers.size,1);assert.ok(a.net.peers.get('bob').linked);assert.equal(a.net.room.members.bob.connected,true);
 await a.net.mutate('ready',true);await b.net.mutate('ready',true);await flush();await b.net.mutate('propose','yes');await a.net.mutate('vote',true);await flush();await a.net.tick();await flush();assert.equal(a.net.room.status,'playing');assert.equal(b.net.room.session.count,2);
 const large={type:'snapshot',tick:7,body:'가나다💥'.repeat(10000)};assert.ok(a.net.send('bob',large,true));await flush();assert.deepEqual(b.events.at(-1).data,large,'fragmented packets reassemble exactly');
 a.net.send('bob',{type:'ping',at:Date.now()});await flush();assert.ok(a.net.peers.get('bob').rtt!==null);
 assert.deepEqual(a.errors,[]);assert.deepEqual(b.errors,[]);await a.net.leave();await flush();assert.equal(b.net.room,null);assert.ok(!docs.has('mpRooms/'+id));assert.ok(!docs.has('mpRooms/'+id+'/signals/bob'));
 console.log('PASS: two-client Firestore transactions + SDP/channel handshake, unanimous start replication, large unordered snapshot fragmentation, ping, host departure and signal cleanup (in-process transports)');
})().catch(e=>{console.error(e);process.exitCode=1;});
