import * as THREE from './vendor/three.module.js';
import {DB} from './data/database.js';
import {loadSpriteLibrary,playerSpriteRow,monsterSpriteRow,act1MonsterProfile,act1BossProfile,createSpriteActor,animateSpriteActor} from './sprite-system.js';
import {assignWeaponIdentity,basicAttackProfile,defaultWeaponIndex,nextClassWeaponIndex,syncEquippedWeapon} from './weapon-system.js';
let spriteLibrary=null;try{spriteLibrary=await loadSpriteLibrary(THREE);}catch(error){console.warn('GOABLO sprite fallback enabled',error);}
document.documentElement.dataset.spriteStatus=spriteLibrary?'ready':'fallback';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],distance=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
let moveGoal=null,attackTarget=null,hoverTarget=null;
const SAVE='goablo-save-v1';let selected=0,started=false,paused=false,town=true,act=1,floor=0,kills=0,cleared=false,clock=0,spawnSerial=0;
let p,hero,previewHero,enemies=[],allies=[],shots=[],effects=[],zones=[],drops=[],corpses=[],floaters=[],timers=[],keys={},mouse={x:0,y:0,down:false},aim=new THREE.Vector3(0,0,-5),target=null;
let settings={vfx:1,sound:true,shake:true,difficulty:1},shake=0,hitstop=0,toastTime=0,msgTime=0,autosave=0,uiTime=0,boss=null,combo=0,lastFusion='',lastCast=0,weaponCycle=0;
const scene=new THREE.Scene();scene.background=new THREE.Color('#172325');scene.fog=new THREE.FogExp2('#172325',.024);
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});}catch(e){$('startBtn').disabled=true;$('classDescription').textContent='WebGL을 사용할 수 없습니다. 브라우저 하드웨어 가속을 켜주세요.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,160);camera.position.set(21,24,25);camera.lookAt(0,0,0);
const ambient=new THREE.HemisphereLight('#b6d6d5','#192325',1.8);scene.add(ambient);const sun=new THREE.DirectionalLight('#d3c29d',2.8);sun.position.set(-12,24,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35});sun.shadow.bias=-.0006;scene.add(sun,sun.target);
const world=new THREE.Group();scene.add(world);const ray=new THREE.Raycaster(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
const matCache=new Map();function mat(c,em=false){let key=c+em;if(!matCache.has(key))matCache.set(key,new THREE.MeshStandardMaterial({color:c,roughness:.82,metalness:.18,...(em?{emissive:c,emissiveIntensity:1.6}:{})}));return matCache.get(key);}
function mesh(g,c,x=0,y=0,z=0,parent=world,em=false){const m=new THREE.Mesh(g,mat(c,em));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
const box=(w,h,d,c,x,y,z,parent=world)=>mesh(new THREE.BoxGeometry(w,h,d),c,x,y,z,parent);
function person(color,kind='human',scale=1,spriteSpec=null){if(spriteSpec&&spriteLibrary){const actor=createSpriteActor(THREE,spriteLibrary,{...spriteSpec,scale,kind});if(actor)return actor;}let g=new THREE.Group();g.userData.kind=kind;
 const torso=mesh(new THREE.CylinderGeometry(.37,.45,.85,6),color,0,.95,0,g);const head=mesh(new THREE.IcosahedronGeometry(.25,1),'#bfb9a4',0,1.62,0,g);g.userData.head=head;
 if(kind==='skeleton'){torso.scale.set(.65,1,.7);head.material=mat('#d6d0b3');for(let i=0;i<3;i++)box(.62,.06,.22,'#d6d0b3',0,.7+i*.18,-.08,g);}
 if(kind==='mage'||kind==='church'){mesh(new THREE.ConeGeometry(.57,1.3,7),color,0,.68,0,g);mesh(new THREE.ConeGeometry(.32,.6,6),color,0,1.99,0,g);}
 if(kind==='thief'){mesh(new THREE.SphereGeometry(.3,6,5),color,0,1.64,.06,g);box(.35,.07,.1,'#d5c395',0,1.63,-.24,g);}
 const legs=[];for(const side of [-1,1]){legs.push(box(.2,.55,.24,'#333d39',side*.2,.28,0,g));box(.26,.13,.38,'#444a40',side*.2,.08,-.06,g);box(.28,.5,.3,color,side*.45,1.05,0,g);}
 g.userData.legs=legs;let weapon=new THREE.Group();weapon.position.set(.55,.95,-.12);g.add(weapon);g.userData.weapon=weapon;
 if(kind==='archer'){const bow=mesh(new THREE.TorusGeometry(.48,.055,5,12,Math.PI),'#bb9757',0,0,-.28,weapon);bow.rotation.z=-Math.PI/2;box(.025,.9,.025,'#ddd1a4',0,0,-.28,weapon);}
 else if(kind==='mage'){box(.065,1.9,.065,'#96805a',0,.25,0,weapon);mesh(new THREE.OctahedronGeometry(.18),color,0,1.25,0,weapon,true);}
 else{box(kind==='warrior'?.24:.12,kind==='warrior'?1.6:1.05,.08,'#a7b4ae',0,.5,0,weapon);box(.43,.08,.12,'#a48b5e',0,.06,0,weapon);}
 if(kind==='church'||kind==='shield'){box(.58,.85,.15,'#828874',-.56,1,-.16,g);box(.06,.6,.03,'#d9bd74',-.56,1,-.25,g);}
 const cape=mesh(new THREE.ConeGeometry(.44,1.1,4,1,true),color,0,.9,.2,g);cape.scale.z=.5;g.scale.setScalar(scale);return g;}
const classKinds=['warrior','church','skeleton','mage','archer','thief'];
function disposeGroup(g){g.userData.spriteMaterial?.dispose();g.traverse(o=>{if(o.isMesh)o.geometry.dispose()});g.removeFromParent();}
function clearBattle(){moveGoal=null;attackTarget=null;hoverTarget=null;for(const e of enemies)e.healthLabel?.remove();for(const e of enemies)disposeGroup(e.mesh);for(const a of allies)disposeGroup(a.mesh);for(const x of [...shots,...effects,...drops]){x.mesh?.removeFromParent();x.mesh?.geometry?.dispose();if(x.disposable)x.mesh?.material.dispose();}for(const z of zones){z.mesh?.removeFromParent();z.mesh?.geometry?.dispose();z.mesh?.material.dispose();}enemies=[];allies=[];shots=[];effects=[];zones=[];drops=[];corpses=[];timers=[];boss=null;$('bossbar').hidden=true;}
function buildWorld(isTown){clearBattle();disposeGroup(world);scene.add(world);while(world.children.length)world.remove(world.children[0]);
 scene.background.set(isTown?'#172628':'#171c23');scene.fog.color.copy(scene.background);
 const floorMat=isTown?'#35443e':'#343b3b';box(62,.5,62,'#1f2a29',0,-.55,0);
 for(let x=-28;x<=28;x+=4)for(let z=-28;z<=28;z+=4){let c=new THREE.Color(floorMat).multiplyScalar(rnd(.8,1.1));box(3.94,.2,3.94,c.getHexString().padStart(6,'0').replace(/^/,'#'),x,-.2+rnd(-.015,.015),z);}
 for(let i=-28;i<=28;i+=4){box(3.9,2.7,1.1,'#47514a',i,1,-30);box(1.1,2.7,3.9,'#47514a',-30,1,i);}
 for(const [x,z] of [[-18,-18],[18,-18],[-18,18],[18,18],[-10,-10],[10,-10]]){box(1.7,.35,1.7,'#626b5a',x,0,z);mesh(new THREE.CylinderGeometry(.6,.8,4.3,7),'#566254',x,2.1,z);box(1.6,.3,1.6,'#778071',x,4.3,z);mesh(new THREE.IcosahedronGeometry(.25),'#d3a563',x,4.7,z,world,true);const l=new THREE.PointLight('#e6af67',16,8);l.position.set(x,4.8,z);world.add(l);}
 for(let i=0;i<55;i++){let x=rnd(-28,28),z=rnd(-28,28);if(Math.abs(x)<5&&Math.abs(z)<7)continue;mesh(new THREE.DodecahedronGeometry(rnd(.12,.6),0),'#48554b',x,.1,z).rotation.set(rnd(0,3),rnd(0,3),0);}
 let seal=mesh(new THREE.TorusGeometry(4,.065,6,60),'#c8a967',0,.02,0,world,true);seal.rotation.x=Math.PI/2;
 for(let i=0;i<8;i++){const a=i*Math.PI/4;box(.15,.05,1.3,'#bdaa77',Math.sin(a)*4.8,0,Math.cos(a)*4.8).rotation.y=a;}
 const portal=mesh(new THREE.TorusGeometry(1.8,.14,8,48),isTown?'#8ecac0':'#dab87a',0,2,-9,world,true);portal.rotation.z=.1;portal.userData.portal=true;
 box(4,.5,2,'#657367',0,.1,-9);if(!isTown){for(let i=0;i<8;i++)box(1.2,1.8,1.2,'#4b5550',Math.sin(i)*24,.6,Math.cos(i)*24);}
}
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;toastTime=3.5;}
function message(a,b=''){ $('centerMessage').innerHTML=a+(b?'<small>'+b+'</small>':'');msgTime=3;}
let audio;function sound(freq=140,len=.08,type='triangle',vol=.05){if(!settings.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*.35),audio.currentTime+len);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+len);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+len);}catch{}}
function burst(x,z,color='#d3bd8a',n=10,power=1){for(let i=0;i<Math.ceil(n*settings.vfx)&&effects.length<260;i++){const m=mesh(new THREE.IcosahedronGeometry(rnd(.04,.12)*power),color,x,.7,z,scene,true);effects.push({mesh:m,life:rnd(.2,.6),max:.6,vx:rnd(-4,4)*power,vy:rnd(2,5)*power,vz:rnd(-4,4)*power});}}
function ring(x,z,r,color='#d2b575',life=.45){const m=new THREE.Mesh(new THREE.RingGeometry(.9*r,r,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.08,z);scene.add(m);effects.push({mesh:m,life,max:life,ring:true,disposable:true});}
function targetMarker(color,inner=.72){const marker=new THREE.Mesh(new THREE.RingGeometry(inner,1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,side:THREE.DoubleSide,depthTest:false,depthWrite:false}));marker.rotation.x=-Math.PI/2;marker.position.y=.11;marker.renderOrder=5;marker.visible=false;scene.add(marker);return marker;}
const hoverMarker=targetMarker('#f4d477',.78),selectedMarker=targetMarker('#ff754f',.7);
function beam(x,z,tx,tz,color='#e6d49b',width=.1){const len=Math.hypot(tx-x,tz-z);const m=mesh(new THREE.CylinderGeometry(width,width,len,6),color,(tx+x)/2,.9,(tz+z)/2,scene,true);m.rotation.z=Math.PI/2;m.rotation.y=-Math.atan2(tz-z,tx-x);effects.push({mesh:m,life:.16,max:.16});}
function number(n,x,z,crit=false,color){const el=document.createElement('span');el.className='damageNum'+(crit?' crit':'');el.textContent=typeof n==='number'?Math.round(n):n;if(color)el.style.color=color;$('floats').append(el);floaters.push({el,x,z,y:1.8,life:1});}
function charSkills(){return DB.skills.filter(s=>s.characterId===p.classId)}
function newPlayer(ci){let c=DB.characters[ci];return {classId:c.id,hp:250,maxHp:250,res:100,maxRes:100,level:1,xp:0,gold:0,points:3,inventory:[],equipment:{},skillLevels:{},branches:{},loadout:DB.skills.filter(s=>s.specializationId===c.specs[0]).map(s=>s.id),specialization:c.specs[0],weapon:defaultWeaponIndex(DB,c.id),cd:{},buffs:{},souls:0,faith:0,sin:0,suspicion:0,combo:0,potions:5,highest:1,completed:0};}
function playerClass(){return DB.characters.find(c=>c.id===p.classId)}
function ensurePlayer(){p.cd={};p.buffs={};p.baseHp=250+(p.level-1)*28;p.maxHp=p.baseHp;p.hp=p.maxHp;p.res=100;p.maxRes=100;p.souls=p.souls||0;p.points??=3;p.branches??={};p.completed??=0;p.potions??=5;p.inventory??=[];p.equipment??={};for(const item of p.inventory)assignWeaponIdentity(DB,item,p.classId);syncEquippedWeapon(DB,p);}
function save(){if(!started)return;try{localStorage.setItem(SAVE,JSON.stringify({version:1,p,act,settings}));}catch{toast('저장 공간이 부족해 자동 저장하지 못했습니다.');}}
function startGame(resume=false){if(resume){try{const s=JSON.parse(localStorage.getItem(SAVE));if(!s?.p||!DB.characters.some(c=>c.id===s.p.classId))throw Error();p=s.p;act=s.act||1;settings={...settings,...s.settings};ensurePlayer();}catch{toast('저장 파일을 읽지 못했습니다.');return;}}else{p=newPlayer(selected);act=1;}
 started=true;paused=false;$('selectScreen').hidden=true;previewHero?.removeFromParent();const classIndex=DB.characters.indexOf(playerClass());hero=person(playerClass().color,classKinds[classIndex],1.12,{atlas:'players',row:playerSpriteRow(p.classId)});scene.add(hero);goTown();renderHotbar();save();sound(240,.3);}
function goTown(){town=true;floor=0;cleared=false;buildWorld(true);hero.position.set(0,0,2);p.hp=p.maxHp;p.res=p.maxRes;p.cd={};p.buffs={};p.potions=Math.max(p.potions,5);$('location').innerHTML='버려진 성역 <small>마을 · 안전 지역</small>';$('questTitle').textContent='잊힌 자들의 성역';$('questText').textContent='장비와 스킬을 준비하세요. 던전은 매번 새롭게 채워집니다.';$('enterBtn').hidden=false;$('enterBtn').textContent=`제 ${act}막 던전 진입 →`;$('returnBtn').hidden=true;$('floorLabel').textContent='SANCTUARY';save();}
function enterDungeon(){if(!started)return;town=false;floor++;cleared=false;kills=0;buildWorld(false);hero.position.set(0,0,16);p.buffs={};const names=['역병의 지하묘지','불타는 수용소','뼈의 왕좌','추락한 대성당','버림받은 왕국'];$('location').innerHTML=names[(act-1)%5]+` <small>제 ${act}막 · ${floor}층</small>`;$('questTitle').textContent=floor===3?'왕좌를 무너뜨려라':'길을 막는 자들';$('questText').textContent=floor===3?'보스를 쓰러뜨리고 보상을 획득하세요.':'적을 처치하고 하층으로 향하세요.';$('enterBtn').hidden=true;$('returnBtn').hidden=false;$('floorLabel').textContent=`ACT ${String(act).padStart(2,'0')} / FLOOR ${floor}`;
 if(act===1){if(floor===3){const profile=act1BossProfile();spawnMonster(profile.dbIndex,0,-9,profile);for(let i=0;i<6;i++){const minion=act1MonsterProfile(i);spawnMonster(minion.dbIndex,rnd(-13,13),rnd(-14,2),minion);}}else{let count=14+floor*4+Math.min(act,10);for(let i=0;i<count;i++){const profile=act1MonsterProfile(i+(floor-1)*2);spawnMonster(profile.dbIndex,rnd(-23,23),rnd(-22,7),profile);}}}else if(floor===3){spawnMonster(20+(act-1)%5,0,-9);for(let i=0;i<6;i++)spawnMonster((act*3+i)%20,rnd(-13,13),rnd(-14,2));}else{let count=14+floor*4+Math.min(act,10);for(let i=0;i<count;i++)spawnMonster((i+(act-1)*4+(floor-1)*7)%20,rnd(-23,23),rnd(-22,7));}message(names[(act-1)%5],`제 ${floor}층 · 돌아갈 곳은 아직 있다`);}
function spawnMonster(index,x,z,profile=null){if(enemies.filter(e=>!e.dead).length>65)return;const base=DB.monsters[index],d=profile?{...base,name:profile.name}:base;const scale=d.boss?2.2:index>=15?1.35:1;let kind=['ranged','poison','web'].includes(d.behavior)?'archer':['revive','fire','cold','teleport','summon'].includes(d.behavior)?'mage':['shield','knight'].includes(d.behavior)?'shield':d.behavior.includes('skeleton')||index===1?'skeleton':'human';const spriteRow=profile?.row??monsterSpriteRow(d.id,index,d.boss);let m=person(d.color,kind,scale,{atlas:'monsters',row:spriteRow,boss:d.boss});if(d.behavior==='bat'){m.scale.y=.6;box(2.2,.12,.5,d.color,0,1,0,m);}if(d.behavior==='web'){m.scale.y=.5;for(let j=0;j<4;j++)box(1.4,.07,.09,d.color,0,.5,j*.24-.3,m);}if(d.boss){mesh(new THREE.TorusGeometry(.34,.06,5,12),'#dac184',0,2,0,m);}
 m.position.set(x,0,z);scene.add(m);let multi=(1+(act-1)*.3+(floor-1)*.14)*settings.difficulty;let e={id:++spawnSerial,def:d,index,mesh:m,x,z,hp:d.hp*multi,maxHp:d.hp*multi,cd:rnd(.3,2),status:{},phase:0,dead:false,elite:index>=15,damage:d.damage*multi};if(e.elite&&!d.boss)e.affix=pick(['冰','吸','迅']);enemies.push(e);if(d.boss){boss=e;$('bossbar').hidden=false;$('bossbar').querySelector('span').textContent=d.name;}return e;}
function addZone(x,z,r,duration,damage,color,enemy=false,tag='',delay=0){let m=new THREE.Mesh(new THREE.CircleGeometry(r,40),new THREE.MeshBasicMaterial({color,transparent:true,opacity:delay?.12:.18,side:THREE.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.04,z);scene.add(m);const zz={x,z,r,life:duration,damage,enemy,tag,tick:0,delay,mesh:m};zones.push(zz);return zz;}
function schedule(delay,fn){timers.push({time:delay,fn});}
function equipmentItems(){return Object.values(p.equipment).filter(Boolean).map(id=>p.inventory.find(i=>i.uid===id)).filter(Boolean);}
function stats(){const eq=equipmentItems();let damage=(20+(p.level-1)*3+DB.weapons[p.weapon].damage*.65)*(1+eq.reduce((n,i)=>n+(i.power||0),0)/100);let speed=eq.filter(i=>i.effect==='속도').length*.08+(p.buffs.haste? .3:0)+(p.buffs.link||0)*.03;if(p.weapon===1)speed+=.05;let crit=.08+(p.weapon===0?.05:0)+eq.filter(i=>i.effect==='치명').length*.06;return {damage,speed,crit,eq};}
function tagItems(tag){return equipmentItems().filter(i=>i.tag==='ALL'||i.tag===tag)}
function damageEnemy(e,base,s,options={}){if(!e||e.dead)return 0;e.labelUntil=clock+4;e.mesh.userData.hitUntil=clock+.13;let st=stats(),d=base*(1+(p.buffs.link||0)*.03),tag=s?.tag||'MELEE';let crit=Math.random()<st.crit+(p.buffs.aim?.25:0);if(crit)d*=1.7;if(e.status.mark)d*=1.3;if(e.status.break)d*=1.25;if(e.status.freeze&&tag==='STAGGER'){d*=1.7;e.status.freeze=0;burst(e.x,e.z,'#a5d9e8',14);}
 if(e.def.behavior==='shield'||e.def.behavior==='knight'){let forward=new THREE.Vector3(0,0,-1).applyQuaternion(e.mesh.quaternion);let to=new THREE.Vector3(hero.position.x-e.x,0,hero.position.z-e.z).normalize();if(forward.dot(to)>.3&&!e.status.break)d*=.45;}
 if(e.def.behavior==='golem')d*=.65;if(p.buffs.berserk)d*=1.5;if(p.buffs.evadeboost)d*=1.2;if(p.buffs.hurt)d*=1.2;if(p.buffs.damage)d*=1.3;const w=DB.weapons[p.weapon];if(w.name==='양손도끼'&&e.hp/e.maxHp<.2)d*=1.25;if(w.name==='장창'&&distance(e,hero.position)>2)d*=1.12;if(w.name==='장궁'&&distance(e,hero.position)>8)d*=1.15;if(w.name==='지팡이'&&s?.id)d*=1.08;if(w.name==='해골봉'&&tag==='SUMMON')d*=1.1;if(w.name==='한손도끼'&&Math.random()<.15)e.status.bleed=4;if(w.name==='철퇴'||w.name==='석궁')d*=1.1;if(w.name==='낫'&&enemies.filter(v=>!v.dead&&distance(v,hero.position)<4).length>1)d*=1.15;if(w.name==='양손망치'&&!e.def.boss)e.status.stagger=.45;if(p.classId==='C06')d*=1+Math.min(p.combo,20)*.015;if(p.classId==='C02')d*=1+Math.abs(p.faith-p.sin)*.003;
 if(p.specialization===s?.specializationId)d*=1.12;if(s){const lev=p.skillLevels[s.id]||1;d*=1+(lev-1)*.1;if(p.branches[s.id]==='power')d*=1.2;let mods=st.eq.filter(i=>i.skillId===s.id);if(mods.some(i=>i.effect==='강화'))d*=1.4;}
 if(tag==='SUMMON')d*=1+tagItems(tag).filter(i=>i.effect==='소환').length*.15;
 if(!e.def.boss&&!options.dot){let away=new THREE.Vector3(e.x-hero.position.x,0,e.z-hero.position.z).normalize();let force=['STAGGER','MELEE','SHIELD'].includes(tag)?.32:.06;e.x+=away.x*force;e.z+=away.z*force;}e.hp-=d;e.status.stagger=Math.max(e.status.stagger||0,e.def.boss?.025:.14);if(!options.dot){if(tag==='FIRE')e.status.burn=3;if(tag==='POISON')e.status.poison=5;if(tag==='COLD')e.status.slow=3;}
 if(p.classId==='C06')p.combo=clamp(p.combo+1,0,30);number(d,e.x,e.z,crit);burst(e.x,e.z,tagColor(tag),crit?7:3,.7);if(crit){shake=Math.max(shake,.13);hitstop=.035;}sound(crit?90:180,.045,'triangle',.015);
 let rings=tagItems(tag);p.hp=Math.min(p.maxHp,p.hp+d*.03*rings.filter(i=>i.effect==='흡혈').length);p.res=clamp(p.res+2*rings.filter(i=>i.effect==='자원').length,0,p.maxRes);
 if(st.eq.some(i=>i.effect==='연계'&&(i.tag===tag))){p.buffs.link=Math.min(5,(p.buffs.link||0)+1);p.buffs.linktime=6;}
 if(e.hp<=0)killEnemy(e,s);return d;}
function killEnemy(e,s){if(e.dead)return;e.dead=true;e.healthLabel?.remove();if(attackTarget===e)attackTarget=null;if(hoverTarget===e)hoverTarget=null;const x=e.x,z=e.z;burst(x,z,e.def.color,e.def.boss?38:9,1.3);if(e.mesh.userData.spriteFrames){corpses.push({x,z,life:18,mesh:e.mesh,enemy:e});animateSpriteActor(e.mesh,'death',0,e.id);}else{e.mesh.removeFromParent();corpses.push({x,z,life:18});}kills++;p.gold+=Math.round(rnd(3,8)*(e.def.boss?20:1));p.xp+=e.def.boss?180:16+e.index;p.souls=Math.min(30,p.souls+1);p.res=Math.min(p.maxRes,p.res+5);if(p.buffs.laststand)p.hp=Math.min(p.maxHp,p.hp+20);
 if(e.status.infect&&allies.length<10)summon('zombie',x,z);if(e.def.behavior==='explode')addZone(x,z,3,1.3,e.damage*2,'#e59054',true,'explosion',.7);
 if(tagItems(s?.tag||'MELEE').some(i=>i.effect==='폭발')){ring(x,z,3,'#e2a272');for(const other of enemies)if(!other.dead&&distance(other,e)<3)damageEnemy(other,stats().damage*.4,null);}
 if(e.def.boss){dropItem(x,z,true);dropItem(x+1,z,true);p.completed++;p.highest=Math.max(p.highest,act+1);}else if(Math.random()<.24)dropItem(x,z);if(Math.random()<.09&&p.potions<9)p.potions++;
 while(p.xp>=p.level*100){p.xp-=p.level*100;p.level++;p.points+=3;p.baseHp=(p.baseHp||250)+28;p.maxHp=p.baseHp;p.hp=p.maxHp;message('LEVEL UP',`레벨 ${p.level} · 스킬 포인트 +3`);ring(hero.position.x,hero.position.z,5,'#dfc88f',1);sound(500,.5);}
 if(!enemies.some(x=>!x.dead)){cleared=true;$('enterBtn').hidden=false;$('enterBtn').textContent=floor<3?'하층으로 이동 →':'보상 획득 · 다음 막으로 →';$('questText').textContent='지역을 확보했습니다. 전리품을 챙기세요.';message(floor===3?'왕좌가 무너졌다':'지역 확보',floor===3?'다음 막의 문이 열립니다.':'전리품을 챙기고 더 깊이 내려가세요.');save();}}
function hurt(amount,source,impact='normal'){if(!started||town||p.hp<=0||p.buffs.invulnerable||p.buffs.evade)return;if(p.buffs.parry){p.buffs.parry=0;ring(hero.position.x,hero.position.z,4,'#ede2a6');if(source)damageEnemy(source,stats().damage*3,{tag:'SHIELD'});p.res=Math.min(100,p.res+20);return;}const armor=equipmentItems().filter(i=>['갑옷','투구','바지'].includes(i.slot)).reduce((n,i)=>n+(i.power||0),0);amount*=1-Math.min(.3,armor*.002);if(p.buffs.guard)amount*=.25;if(p.buffs.protect)amount*=.7;if(p.buffs.shield){let a=Math.min(amount,p.buffs.shield);p.buffs.shield-=a;amount-=a;}if(p.buffs.laststand&&p.hp-amount<=0)amount=Math.max(0,p.hp-1);p.hp=Math.max(0,p.hp-amount);const heavy=impact==='heavy'||source?.def?.boss||amount>=p.maxHp*.12;if(heavy){hero.userData.attack=0;hero.userData.hitUntil=clock+.24;p.cd.basic=Math.min(p.cd.basic||0,.18);shake=.25;}else{hero.userData.softHitUntil=clock+.12;shake=Math.max(shake,.1);}p.combo=0;p.buffs.hurt=3;$('damageflash').style.opacity=.9;number(-amount,hero.position.x,hero.position.z,false,'#ed877c');if(p.hp<=0){message('다시, 혼자가 되었다','성역에서 재정비하고 돌아오세요.');p.gold=Math.floor(p.gold*.9);paused=true;showPanel('여정은 끝나지 않았다',`<p>제 ${act}막 ${floor}층에서 쓰러졌습니다. 보유 금화의 10%를 잃었습니다.</p><button class="gold" id="revive">성역에서 부활</button>`);$('revive').onclick=()=>{closePanel();goTown();};}}
function tagColor(t){return {FIRE:'#ef9251',COLD:'#a1d8ea',LIGHTNING:'#b1b5ff',SPACE:'#b9a0e4',POISON:'#a6c775',BLOOD:'#da6575',SUMMON:'#a9d2b1',LIGHT:'#e9dc9b',SHADOW:'#b995db',STEALTH:'#b99bcc'}[t]||'#d3ba86';}
function closest(x=hero.position.x,z=hero.position.z,range=99){return enemies.filter(e=>!e.dead&&Math.hypot(e.x-x,e.z-z)<range).sort((a,b)=>Math.hypot(a.x-x,a.z-z)-Math.hypot(b.x-x,b.z-z))[0];}
function area(x,z,r,d,s,extra){ring(x,z,r,tagColor(s?.tag));for(const e of enemies)if(!e.dead&&Math.hypot(e.x-x,e.z-z)<r){damageEnemy(e,d,s);if(extra)Object.assign(e.status,extra);}}
function projectile(x,z,tx,tz,d,s,opts={}){let dir=new THREE.Vector3(tx-x,0,tz-z).normalize();if(dir.length()<.1)dir.set(0,0,-1);let m=mesh(new THREE.IcosahedronGeometry(opts.size||(opts.enemy?.14:.16)),opts.color||tagColor(s?.tag),x,.9,z,scene,true);shots.push({mesh:m,x,z,dir,d,s,life:2,speed:opts.speed||17,hit:new Set(),...opts});}
function summon(kind,x=hero.position.x+rnd(-2,2),z=hero.position.z+rnd(-2,2)){const slotCost=['knight','hire1'].includes(kind)?3:kind==='mage'?2:1;while(allies.reduce((v,a)=>v+(a.slotCost||1),0)+slotCost>10){let old=allies.shift();disposeGroup(old.mesh);}const hire=kind.startsWith('hire'),ix=hire?Number(kind.slice(-1)):0;let type=kind==='archer'||kind==='hire2'?'archer':kind==='mage'?'mage':kind==='knight'||kind==='hire1'?'shield':'skeleton';let m=person(hire?'#b99863':'#a2bd9c',type,kind==='knight'||kind==='hire1'?1.25:.85);if(kind==='hire0'){m.rotation.x=-.5;m.scale.y=.65;}m.position.set(x,0,z);scene.add(m);const trait=hire?pick(['튼튼한','포악한','민첩한','식탐']):'';allies.push({kind,slotCost,mesh:m,x,z,hp:(kind==='hire1'?420:180)*(trait==='튼튼한'?1.4:1),maxHp:kind==='hire1'?420:180,cd:rnd(.1,.5),life:120,trait});ring(x,z,1,'#94c6aa');}
function dashTo(tx,tz,length=5,damage=0,s){let from=hero.position.clone(),dir=new THREE.Vector3(tx-from.x,0,tz-from.z).normalize();if(dir.length()<.1)dir.set(0,0,-1);hero.position.addScaledVector(dir,length);hero.position.x=clamp(hero.position.x,-28,28);hero.position.z=clamp(hero.position.z,-28,28);beam(from.x,from.z,hero.position.x,hero.position.z,tagColor(s?.tag),.2);p.buffs.evade=.35;if(damage)for(let i=0;i<=4;i++)area(from.x+dir.x*length*i/4,from.z+dir.z*length*i/4,1.3,damage/2,s);}
function cast(s,echo=false,scale=1){if(!s||!started||paused||p.hp<=0)return;let st=stats();if(!echo){if((p.cd[s.id]||0)>0)return;let cost=s.cost*(p.branches[s.id]==='utility'?.75:1);if(p.res<cost){toast('자원이 부족합니다. 기본 공격으로 회복하세요.');return;}if(s.tag==='BLOOD'&&p.hp>cost+1){p.hp-=cost*.3;cost*=.7;}p.res-=cost;const frames=Math.max(7,Math.ceil(s.baseCastFrames/(1+st.speed)));p.cd[s.id]=Math.max(frames/60,s.cooldown/(1+st.speed*.4));if(p.classId==='C02'){p.faith=clamp(p.faith+(s.tag==='LIGHT'||s.tag==='SHIELD'?5:-2),0,100);p.sin=clamp(p.sin+(s.tag==='BLOOD'||s.tag==='JUDGMENT'?5:-2),0,100);}if(p.classId==='C06')p.suspicion=clamp(p.suspicion+15,0,100);
 if(st.eq.some(i=>i.skillId===s.id&&i.effect==='변형')&&!['fireball','skeleton','assassinate'].includes(s.mode))schedule(.3,()=>cast(s,true,.55));if(p.buffs.clone&&!['clone','exchange'].includes(s.mode))schedule(.18,()=>cast(s,true,.35));
 if(p.classId==='C04'&&lastFusion&&lastFusion!==s.tag&&clock-lastCast<5){const pair=[lastFusion,s.tag];if(pair.includes('SPACE'))addZone(aim.x,aim.z,4,3,st.damage*.6,tagColor(s.tag),false,'gravity');else area(aim.x,aim.z,3.5,st.damage*.7,s,{slow:2});toast('주문 융합 · '+pair.join(' × '));}lastFusion=s.tag;lastCast=clock;
 }const x=hero.position.x,z=hero.position.z,tx=aim.x,tz=aim.z,e=closest(tx,tz,8),d=st.damage*s.coefficient*scale,r=s.radius*(st.eq.some(i=>i.skillId===s.id&&i.effect==='강화')?1.25:1),c=tagColor(s.tag),mode=s.mode;
 hero.rotation.y=Math.atan2(-(tx-x),-(tz-z));hero.userData.attack=.25;sound(s.ultimate?65:220,.12,'sawtooth',.018);if(s.ultimate){shake=.4;message(s.name);}
 const buff=(name,t=6)=>{p.buffs[name]=t;ring(x,z,2,c);};const aoe=(radius=r,dd=d,px=x,pz=z,extra)=>area(px,pz,radius,dd,s,extra);
 switch(mode){
 case 'cleave':case 'sweep':case 'slam':case 'flurry':case 'poisonblade':case 'backstab':{const dir=new THREE.Vector3(tx-x,0,tz-z).normalize();aoe(r*.7,d,x+dir.x*1.3,z+dir.z*1.3,mode==='poisonblade'?{poison:6}:undefined);if(mode==='flurry')for(let i=1;i<3;i++)schedule(i*.12,()=>area(hero.position.x,hero.position.z,r*.7,d*.35,s));if(mode==='backstab'&&p.buffs.stealth&&e)damageEnemy(e,d*2,s);break;}
 case 'quake':case 'nova':case 'burst':case 'bladestorm':case 'bloodsea':aoe(s.ultimate?10:r);if(mode==='bloodsea'){addZone(x,z,9,8,d*.2,c,false,'BLOOD');p.hp=Math.min(p.maxHp,p.hp+100);}if(mode==='bladestorm')addZone(x,z,6,5,d*.2,c);break;
 case 'launch':aoe(r,d,x,z,{stagger:1.2});break;
 case 'break':case 'corrode':aoe(r,d,x,z,{break:8,poison:mode==='corrode'?7:0});break;
 case 'dash':case 'blinkstrike':dashTo(e?.x??tx,e?.z??tz,mode==='blinkstrike'?Math.min(8,Math.hypot(tx-x,tz-z)):5,d,s);break;
 case 'evade':dashTo(tx,tz,5);buff('evade',.8);break;
 case 'charge':buff('guard',.65);ring(x,z,3,c,.65);schedule(.65,()=>area(hero.position.x,hero.position.z,r+2,d*1.6,s,{stagger:1}));break;
 case 'orbit':case 'storm':case 'bladestorm':addZone(x,z,r+1,5,d*.35,c,false,s.tag);break;
 case 'wave':case 'pierce':case 'return':projectile(x,z,tx,tz,d,s,{pierce:true,size:.6,returning:mode==='return'});break;
 case 'swap':p.weapon=nextClassWeaponIndex(DB,p.classId,p.weapon);weaponCycle++;buff('damage',5);aoe(r,d*(1+weaponCycle%3*.3));toast(DB.weapons[p.weapon].name+' 교대');break;
 case 'heal':case 'miracle':p.hp=Math.min(p.maxHp,p.hp+(mode==='miracle'?p.maxHp:d*2));aoe(mode==='miracle'?10:r,d*.5);break;
 case 'cleanse':p.buffs={};buff('invulnerable',1.2);p.hp=Math.min(p.maxHp,p.hp+d);break;
 case 'beam':{beam(x,z,tx,tz,c,.18);const len=Math.hypot(tx-x,tz-z),dir=new THREE.Vector3(tx-x,0,tz-z).normalize();for(const v of enemies){if(v.dead)continue;let along=(v.x-x)*dir.x+(v.z-z)*dir.z;let perp=Math.abs((v.x-x)*dir.z-(v.z-z)*dir.x);if(along>=0&&along<=Math.min(18,len+2)&&perp<1)damageEnemy(v,d,s);}break;}
 case 'pillar':case 'rain':case 'arrowstorm':case 'meteor':case 'thunder':{let count=['rain','arrowstorm'].includes(mode)?7:1;for(let i=0;i<count;i++){let xx=tx+(count>1?rnd(-4,4):0),zz=tz+(count>1?rnd(-4,4):0);ring(xx,zz,mode==='meteor'?6:r,c,.65+i*.08);schedule(.55+i*.09,()=>{beam(xx,zz,xx+.01,zz,c,.4);area(xx,zz,mode==='meteor'?7:r,d/count*2,s);burst(xx,zz,c,20,2);});}break;}
 case 'mark':if(e){e.status.mark=10;ring(e.x,e.z,1,c,1);}break;
 case 'bind':case 'paralyze':aoe(r,d,tx,tz,{freeze:3});break;
 case 'execute':case 'assassinate':case 'snipe':{if(e){if(mode==='assassinate')dashTo(e.x,e.z,Math.max(0,distance(e,hero.position)-.8));let mul=e.hp/e.maxHp<.3?2:1;if(p.buffs.stealth)mul*=2.5;beam(x,z,e.x,e.z,c,.12);damageEnemy(e,d*mul,s);if(mode==='assassinate'&&e.dead){buff('stealth',4);if(st.eq.some(i=>i.skillId===s.id&&i.effect==='변형')){let next=closest(e.x,e.z,9);if(next)dashTo(next.x,next.z,Math.max(0,distance(next,hero.position)-1));}}}else projectile(x,z,tx,tz,d,s,{pierce:true,speed:35});break;}
 case 'judgment':aoe(s.ultimate?10:r,d*1.3,tx,tz,{mark:5});break;
 case 'sacrifice':p.hp=Math.max(1,p.hp-p.maxHp*.1);buff('damage',9);aoe(r,d*1.3);break;
 case 'buff':buff('haste',8);break;
 case 'laststand':buff('laststand',6);break;
 case 'guard':buff('guard',5);break;case 'parry':buff('parry',1.2);break;case 'counter':buff('parry',1.5);aoe(r,d*.7);break;case 'shieldbash':aoe(3,d,x,z,{stagger:2});break;
 case 'taunt':buff('protect',6);for(const v of enemies)if(distance(v,hero.position)<10)v.status.taunt=6;break;
 case 'sanctuary':addZone(x,z,5,7,0,c,false,'heal');buff('protect',7);break;
 case 'skeleton':case 'archer':case 'mage':case 'knight':case 'hire0':case 'hire1':case 'hire2':case 'hire3':summon(mode);break;
 case 'command':buff('command',7);for(const a of allies)a.cd=0;aoe(4,d*.3,tx,tz);break;
 case 'fortify':for(const a of allies)a.hp=Math.min(a.maxHp,a.hp+d*2);buff('command',8);break;
 case 'infect':case 'plague':aoe(s.ultimate?12:r,d*.6,tx,tz,{infect:12,poison:8});break;
 case 'pool':case 'wall':case 'trap':addZone(tx,tz,mode==='wall'?r*.7:r,6,d*.35,c,false,s.tag);break;
 case 'detonate':for(const a of allies){area(a.x,a.z,4,d,s);a.life=0;}break;
 case 'mutate':for(const a of allies){a.mesh.scale.multiplyScalar(1.12);a.maxHp*=1.2;a.hp=a.maxHp;}buff('command',8);break;
 case 'drain':if(e){let dealt=damageEnemy(e,d,s);p.hp=Math.min(p.maxHp,p.hp+dealt*.6);beam(x,z,e.x,e.z,c,.1);}break;
 case 'clone':case 'afterimage':buff('clone',mode==='clone'?7:4);summon('shadow');break;
 case 'extract':aoe(r,d*.6,tx,tz);p.souls=Math.min(30,p.souls+3);break;
 case 'possess':if(e&&!e.def.boss){e.status.possess=8;e.status.freeze=8;summon('shadow',e.x,e.z);}else if(e)damageEnemy(e,d*2,s);break;
 case 'release':aoe(s.ultimate?14:r+2,d*(1+p.souls*.12));p.souls=0;break;
 case 'projectile':case 'fireball':case 'explosive':case 'piercing':case 'homing':case 'frostshot':case 'overcharge':projectile(x,z,tx,tz,d,s,{explode:mode==='fireball'||mode==='explosive',pierce:mode==='piercing',homing:mode==='homing',freeze:mode==='frostshot',split:mode==='fireball'&&st.eq.some(i=>i.skillId===s.id&&i.effect==='변형'),overcharge:mode==='overcharge'});break;
 case 'triple':case 'split':case 'flurryshot':{let a=Math.atan2(tz-z,tx-x);for(let i=-1;i<=1;i++)projectile(x,z,x+Math.cos(a+i*.15)*20,z+Math.sin(a+i*.15)*20,d*.65,s,{pierce:mode==='flurryshot',split:mode==='split'});break;}
 case 'cone':{let dir=new THREE.Vector3(tx-x,0,tz-z).normalize();ring(x,z,r+2,c);for(const v of enemies)if(!v.dead&&distance(v,hero.position)<r+4){let vd=new THREE.Vector3(v.x-x,0,v.z-z).normalize();if(vd.dot(dir)>.5)damageEnemy(v,d,s);}break;}
 case 'freeze':case 'blizzard':aoe(s.ultimate?12:r,d,tx,tz,{freeze:s.ultimate?5:3});break;
 case 'chain':{let list=enemies.filter(v=>!v.dead).sort((a,b)=>distance(a,{x:tx,z:tz})-distance(b,{x:tx,z:tz})).slice(0,6),xx=x,zz=z;for(const v of list){beam(xx,zz,v.x,v.z,c);damageEnemy(v,d*.7,s);xx=v.x;zz=v.z;}break;}
 case 'teleport':dashTo(tx,tz,Math.min(10,Math.hypot(tx-x,tz-z)));aoe(3,d);break;
 case 'gravity':case 'rift':case 'compress':case 'collapse':addZone(tx,tz,s.ultimate?9:r,mode==='compress'?2:6,d*.45,c,false,'gravity');break;
 case 'exchange':if(e&&!e.def.boss){const ex=e.x,ez=e.z;e.x=x;e.z=z;e.mesh.position.set(x,0,z);hero.position.set(ex,0,ez);damageEnemy(e,d,s);}else{const a=allies[0];if(a){let ax=a.x,az=a.z;a.x=x;a.z=z;hero.position.set(ax,0,az);}else dashTo(tx,tz,6);}buff('evade',.7);break;
 case 'slowtime':aoe(r+3,d*.3,tx,tz,{slow:8});break;
 case 'aim':buff('aim',8);break;
 case 'feed':p.hp=Math.min(p.maxHp,p.hp+40);for(const a of allies)a.hp=a.maxHp;buff('command',8);break;
 case 'stealth':case 'smoke':buff('stealth',6);p.suspicion=0;if(mode==='smoke')aoe(4,d*.3,x,z,{slow:4});break;
 case 'venom':if(e){e.status.poison=10;e.status.venom=1;damageEnemy(e,d,s);}break;
 case 'detonatepoison':for(const v of enemies)if(!v.dead&&v.status.poison){damageEnemy(v,d*(1+v.status.poison*.15),s);v.status.poison=0;ring(v.x,v.z,2,c);}break;
 case 'berserk':buff('berserk',12);buff('haste',12);break;
 case 'invulnerable':buff('invulnerable',7);aoe(8,d*.4);break;
 case 'army':for(let i=0;i<6;i++)summon(p.classId==='C05'?'hire'+i%4:['skeleton','archer','mage','knight'][i%4]);buff('command',10);break;
 case 'arsenal':for(let i=0;i<4;i++)schedule(i*.25,()=>area(hero.position.x,hero.position.z,5+i,d*.5,s));break;
 case 'massassassin':for(const v of enemies.filter(e=>!e.dead).slice(0,8))damageEnemy(v,d*1.5,s);buff('stealth',5);break;
 case 'shadowarmy':buff('clone',15);for(let i=0;i<4;i++)summon('shadow');break;
 default:aoe(r,d,tx,tz);}
 if(p.branches[s.id]==='utility')p.hp=Math.min(p.maxHp,p.hp+5);}
function dropItem(x,z,legendary=false){const rarity=legendary||Math.random()<.38?'전설':pick(['일반','마법','희귀']);let item;if(rarity==='전설'){let pool=DB.items.filter(i=>i.tag==='ALL'||i.skillId?.startsWith(playerClass().specs[0])||i.tag===DB.specs.find(s=>s.id===p.specialization).tag||!i.skillId);if(Math.random()<.4)pool=DB.items;item={...pick(pool)};}else{let slot=pick(['무기','투구','갑옷','장갑','바지','신발','목걸이','반지']);item={id:'base',name:pick(['이름 없는','금이 간','주워온','남겨진'])+' '+slot,slot,rarity,power:rarity==='희귀'?12:rarity==='마법'?7:3,description:'공격력 증가 · 방어 보조',effect:'기본'};}
 item.uid=crypto.randomUUID();item.level=p.level;item.power+=Math.floor(act*1.5);assignWeaponIdentity(DB,item,p.classId);const color=rarity==='전설'?'#e3b666':rarity==='희귀'?'#d6d494':'#8bb3c0';let m=mesh(new THREE.OctahedronGeometry(.24),color,x,.35,z,scene,true);let light=mesh(new THREE.CylinderGeometry(.07,.2,2.5,6),color,0,1,0,m,true);light.material=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.3});drops.push({x,z,mesh:m,item});ring(x,z,.7,color,.8);}
function loot(all=false){let found=0;for(let i=drops.length-1;i>=0;i--){let d=drops[i];if(all||distance(d,hero.position)<3){if(p.inventory.length>=160){toast('가방이 가득 찼습니다. 장비를 정리하세요.');break;}p.inventory.push(d.item);d.mesh.removeFromParent();drops.splice(i,1);found++;}}if(found){toast(`전리품 ${found}개 획득 · I로 장비 확인`);sound(620,.12);save();}else toast('가까운 전리품이 없습니다.');}
function basic(){if(!started||paused||p.cd.basic>0||p.hp<=0)return;let w=DB.weapons[p.weapon],profile=basicAttackProfile(DB,p.weapon),st=stats();p.cd.basic=1/(w.speed*(1+st.speed));p.res=Math.min(p.maxRes,p.res+(w.name==='마법봉'?11:10));if(w.name==='활'){p.buffs.link=Math.min(5,(p.buffs.link||0)+1);p.buffs.linktime=3;}hero.userData.attack=profile.duration;hero.userData.attackDuration=profile.duration;hero.userData.attackMotion=profile.motion;let x=hero.position.x,z=hero.position.z,s={tag:profile.tag};hero.rotation.y=Math.atan2(-(aim.x-x),-(aim.z-z));if(profile.projectile)projectile(x,z,aim.x,aim.z,st.damage,s,{pierce:profile.pierce,speed:profile.speed,size:profile.size,color:profile.color});else{let dir=new THREE.Vector3(aim.x-x,0,aim.z-z).normalize(),reach=w.range*profile.reach;area(x+dir.x*reach*.55,z+dir.z*reach*.55,w.range*profile.radius,st.damage,s,profile.status);}sound(profile.projectile?170:95,profile.duration*.35,profile.projectile?'sine':'triangle');}
function dodge(){if(p.cd.dodge>0||paused)return;p.cd.dodge=2.5;let v=movement();if(v.length()<.1)v.set(aim.x-hero.position.x,0,aim.z-hero.position.z).normalize();dashTo(hero.position.x+v.x,hero.position.z+v.z,4.5);if(equipmentItems().some(i=>i.effect==='회피'))p.buffs.evadeboost=4;}
function potion(){if(p.cd.potion>0||p.potions<=0||p.hp>=p.maxHp||paused)return;p.potions--;p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.5);p.cd.potion=8;ring(hero.position.x,hero.position.z,2,'#bbdfad');toast(`회복약 사용 · ${p.potions}개 남음`);}
function movement(){let v=new THREE.Vector3((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),0,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0));v.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/4);return v.normalize();}
function enemyAttack(e,dt){const d=e.def,b=d.behavior;let tx=hero.position.x,tz=hero.position.z;let targetAlly=null;if(!e.status.taunt){targetAlly=allies.filter(a=>a.hp>0).sort((a,b)=>distance(a,e)-distance(b,e))[0];if(targetAlly&&distance(targetAlly,e)<distance(e,hero.position)*.8){tx=targetAlly.x;tz=targetAlly.z;}else targetAlly=null;}
 let dis=Math.hypot(tx-e.x,tz-e.z);const ranged=['ranged','poison','web','fire','cold','revive','summon','teleport'].includes(b);let speed=d.speed*(e.status.slow?.4:1)*(e.affix==='迅'?1.35:1)*(b==='rage'&&e.hp/e.maxHp<.4?1.7:1);
 if(p.buffs.stealth&&p.suspicion<100&&!targetAlly&&!d.boss){dis=999;speed*=.2;}
 if(e.status.freeze||e.status.stagger)return;
 if(dis<(d.boss?34:28)&&dis>(ranged?9:1.65*d.boss+1.25)){let sign=ranged&&dis<6?-1:1;let dx=(tx-e.x)/dis,dz=(tz-e.z)/dis;e.x+=dx*speed*dt*sign;e.z+=dz*speed*dt*sign;e.mesh.rotation.y=Math.atan2(-dx,-dz);}
 e.cd-=dt;if(e.cd>0||dis>35)return;
 if(d.boss){let stage=e.hp/e.maxHp<.45?2:1;if(b==='spiderboss'&&stage===2&&!e.enraged){e.enraged=true;e.phase=0;message('거미어미고아가 격노했다','거미줄이 빠르게 퍼집니다');ring(e.x,e.z,7,'#d7efad',1.2);burst(e.x,e.z,'#a8cf74',28,1.6);}e.cd=b==='spiderboss'&&stage===2?1.9:2.6;e.phase++;if(e.phase%3===0){let n=b==='skeletonboss'||b==='spiderboss'?4:2;for(let i=0;i<n;i++){if(b==='spiderboss'){const minion=act1MonsterProfile(3);spawnMonster(minion.dbIndex,e.x+rnd(-4,4),e.z+rnd(-4,4),minion);}else spawnMonster(b==='skeletonboss'?1:b==='plagueboss'?0:(e.phase+i)%15,e.x+rnd(-4,4),e.z+rnd(-4,4));}ring(e.x,e.z,5,d.color);}
 else if(e.phase%3===1){for(let i=0;i<stage+1;i++){let px=tx+rnd(-2,2),pz=tz+rnd(-2,2),radius=b==='spiderboss'?(stage===2?4:3.5):b==='angelboss'?4:3.5,delay=b==='spiderboss'&&stage===2?.7:.9;addZone(px,pz,radius,b==='spiderboss'?3:2,e.damage*1.6,d.color,true,b==='spiderboss'?'web':b,delay);ring(px,pz,radius,'#d7efad',delay);}}
 else if(b==='demonboss'||b==='kingboss'){const ex=e.x,ez=e.z;beam(ex,ez,tx,tz,'#cb6858',.04);schedule(.75,()=>{if(e.dead)return;e.x=clamp(tx,-28,28);e.z=clamp(tz,-28,28);ring(e.x,e.z,4,d.color);if(distance(e,hero.position)<4)hurt(e.damage*1.7,e);});}
 else{for(let i=0;i<8*stage;i++){let a=i*Math.PI*2/(8*stage);projectile(e.x,e.z,e.x+Math.cos(a)*20,e.z+Math.sin(a)*20,e.damage,null,{enemy:true,color:d.color,speed:7,web:b==='spiderboss'});}}return;}
 if(b==='consume'){let corpse=corpses.find(c=>distance(c,e)<6&&c.life>0);if(corpse&&e.hp<e.maxHp){e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.2);corpse.life=0;number('섭취',e.x,e.z);e.cd=3;return;}}
 if(b==='revive'){let corpse=corpses.find(c=>c.life>0&&distance(c,e)<10);if(corpse){spawnMonster(0,corpse.x,corpse.z);corpse.life=0;e.cd=7;return;}}
 if(b==='summon'){spawnMonster(1,e.x+rnd(-2,2),e.z+rnd(-2,2));e.cd=8;return;}
 if(b==='teleport'){ring(e.x,e.z,2,d.color);e.x=clamp(tx+rnd(-10,10),-27,27);e.z=clamp(tz+rnd(-10,10),-27,27);addZone(tx,tz,3,2,e.damage,d.color,true,'magic',.9);e.cd=5;return;}
 if(b==='cold'){addZone(tx,tz,3,4,e.damage*.5,d.color,true,'cold',.7);e.cd=4;return;}
 if(ranged&&dis<20){projectile(e.x,e.z,tx,tz,e.damage,null,{enemy:true,color:d.color,speed:b==='fire'?10:8,poison:b==='poison',web:b==='web'});e.cd=2;return;}
 if(['rush','bat','knight','hook'].includes(b)&&dis<12&&dis>3){let xx=tx,zz=tz;ring(xx,zz,2,d.color,.6);e.cd=4;schedule(.6,()=>{if(e.dead)return;if(b==='hook'){beam(e.x,e.z,xx,zz,d.color);if(Math.hypot(hero.position.x-xx,hero.position.z-zz)<2){hero.position.x=(hero.position.x+e.x)/2;hero.position.z=(hero.position.z+e.z)/2;hurt(e.damage,e);}}else{e.x=xx;e.z=zz;if(distance(e,hero.position)<2)hurt(e.damage*1.5,e);}});return;}
 if(dis<2.5){e.cd=b==='fast'?.65:1.25;e.mesh.userData.attack=.3;let xx=tx,zz=tz;schedule(.28,()=>{if(e.dead)return;if(targetAlly&&targetAlly.hp>0&&distance(targetAlly,e)<3){targetAlly.hp-=e.damage;}else if(Math.hypot(hero.position.x-xx,hero.position.z-zz)<2.1){hurt(e.damage,e);if(b==='vampire')e.hp=Math.min(e.maxHp,e.hp+e.damage);if(e.affix==='冰')p.buffs.slow=2;}});}else e.cd=.2;
}
function update(dt){clock+=dt;if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').style.opacity=0;}if(msgTime>0){msgTime-=dt;if(msgTime<=0)$('centerMessage').innerHTML='';}let opacity=parseFloat($('damageflash').style.opacity)||0;$('damageflash').style.opacity=Math.max(0,opacity-dt*2);
 for(let i=floaters.length-1;i>=0;i--){let f=floaters[i];f.life-=dt;f.y+=dt;const v=new THREE.Vector3(f.x,f.y,f.z).project(camera);f.el.style.left=(v.x*.5+.5)*innerWidth+'px';f.el.style.top=(-v.y*.5+.5)*innerHeight+'px';f.el.style.opacity=f.life;if(f.life<=0){f.el.remove();floaters.splice(i,1);}}
 for(let i=effects.length-1;i>=0;i--){const f=effects[i];f.life-=dt;if(f.vx){f.mesh.position.x+=f.vx*dt;f.mesh.position.z+=f.vz*dt;f.mesh.position.y+=f.vy*dt;f.vy-=12*dt;}if(f.ring){f.mesh.scale.setScalar(1+(1-f.life/f.max)*.3);f.mesh.material.opacity=f.life/f.max*.6;}if(f.life<=0){f.mesh.removeFromParent();f.mesh.geometry.dispose();if(f.disposable)f.mesh.material.dispose();effects.splice(i,1);}}
 if(!started){if(previewHero){previewHero.rotation.y=Math.sin(clock*.3)*.2-.35;previewHero.position.y=Math.sin(clock)*.025;animateSpriteActor(previewHero,'idle',clock);}return;}
 if(paused)return;for(let i=timers.length-1;i>=0;i--){timers[i].time-=dt;if(timers[i].time<=0){const fn=timers[i].fn;timers.splice(i,1);fn();}}
 for(const k in p.cd)p.cd[k]=Math.max(0,p.cd[k]-dt);for(const k in p.buffs)if(!['link','shield'].includes(k))p.buffs[k]=Math.max(0,p.buffs[k]-dt);if(!p.buffs.linktime)p.buffs.link=0;
 p.res=Math.min(p.maxRes,p.res+dt*4);p.suspicion=Math.max(0,p.suspicion-dt*10);p.combo=Math.max(0,p.combo-dt*.3);if(p.buffs.stealth&&p.suspicion>=100)p.buffs.stealth=0;
 const mv=movement();let speed=5.8*(p.buffs.slow?.5:1)*(p.buffs.haste?1.2:1);
 const manual=mv.lengthSq()>0;
 if(manual){moveGoal=null;attackTarget=null;}
 if(attackTarget?.dead)attackTarget=null;
 if(keys.shift){moveGoal=null;attackTarget=null;mv.set(0,0,0);}
 else if(!manual){
  if(attackTarget){const dist=distance(attackTarget,hero.position);aim.set(attackTarget.x,0,attackTarget.z);const reach=Math.max(.8,DB.weapons[p.weapon].range*.75);if(dist>reach)mv.set(attackTarget.x-hero.position.x,0,attackTarget.z-hero.position.z).normalize().multiplyScalar(Math.min(1,(dist-reach)/(speed*dt||1)));else basic();}
  else if(moveGoal){const dist=distance(moveGoal,hero.position);if(dist<.08)moveGoal=null;else mv.set(moveGoal.x-hero.position.x,0,moveGoal.z-hero.position.z).normalize().multiplyScalar(Math.min(1,dist/(speed*dt||1)));}
 }
 hero.position.addScaledVector(mv,speed*dt);hero.position.x=clamp(hero.position.x,-28,28);hero.position.z=clamp(hero.position.z,-28,28);if(mv.length())hero.rotation.y=Math.atan2(-mv.x,-mv.z);
 const heroAttacking=hero.userData.attack>0;for(const leg of hero.userData.legs)leg.rotation.x=Math.sin(clock*13+(leg.position.x>0?0:Math.PI))*.5*mv.length();if(hero.userData.attack>0){hero.userData.attack-=dt;const duration=hero.userData.attackDuration||.25,progress=clamp(hero.userData.attack/duration,0,1),heavy=['smash','slam','cleave','cast-heavy','crossbow-shot'].includes(hero.userData.attackMotion);hero.userData.weapon.rotation.x=-Math.sin(progress*Math.PI)*(heavy?2.35:1.55);hero.userData.weapon.rotation.z=['sweep','reap'].includes(hero.userData.attackMotion)?Math.sin(progress*Math.PI)*1.1:0;}else{hero.userData.weapon.rotation.x=0;hero.userData.weapon.rotation.z=0;}animateSpriteActor(hero,heroAttacking?'attack':hero.userData.hitUntil>clock?'hit':mv.length()?'walk':'idle',clock);
 hero.visible=!(p.buffs.stealth&&Math.floor(clock*12)%3===0);if(mouse.down&&keys.shift)basic();
 for(const e of enemies){if(e.dead)continue;for(const k in e.status)e.status[k]=Math.max(0,e.status[k]-dt);if(e.status.burn||e.status.poison||e.status.bleed){e.dot=(e.dot||0)-dt;if(e.dot<=0){e.dot=.8;damageEnemy(e,stats().damage*.18,{tag:e.status.poison?'POISON':e.status.burn?'FIRE':'BLEED'},{dot:true});}}enemyAttack(e,dt);e.x=clamp(e.x,-28,28);e.z=clamp(e.z,-28,28);const enemyMoving=Math.hypot(e.x-e.mesh.position.x,e.z-e.mesh.position.z)>.015;e.mesh.position.set(e.x,0,e.z);for(const l of e.mesh.userData.legs)l.rotation.x=Math.sin(clock*8+e.id+(l.position.x>0?0:Math.PI))*.3;const enemyAttacking=e.mesh.userData.attack>0;if(e.mesh.userData.attack>0){e.mesh.userData.attack-=dt;e.mesh.userData.weapon.rotation.x=-Math.sin(e.mesh.userData.attack/.3*Math.PI)*1.5;}else e.mesh.userData.weapon.rotation.x=0;animateSpriteActor(e.mesh,e.mesh.userData.hitUntil>clock?'hit':enemyAttacking?'attack':enemyMoving?'walk':'idle',clock,e.id);}
 for(let i=allies.length-1;i>=0;i--){let a=allies[i];a.life-=dt;a.cd-=dt;let e=closest(a.x,a.z,22),ranged=a.kind==='archer'||a.kind==='mage'||a.kind==='hire2';let tx=e?e.x:hero.position.x,tz=e?e.z:hero.position.z,dist=Math.hypot(tx-a.x,tz-a.z);if(dist>(e?(ranged?7:1.4):3)){let speed=a.kind==='hire0'?7:a.trait==='민첩한'?6:4;a.x+=(tx-a.x)/dist*dt*speed;a.z+=(tz-a.z)/dist*dt*speed;a.mesh.rotation.y=Math.atan2(-(tx-a.x),-(tz-a.z));}if(e&&dist<(ranged?12:2.5)&&a.cd<=0){a.cd=a.kind==='hire3'&&a.hp/a.maxHp<.5?.4:1;let dmg=stats().damage*(p.buffs.command?1.5:.75)*(a.trait==='포악한'?1.3:1);if(ranged)projectile(a.x,a.z,e.x,e.z,dmg,{tag:'SUMMON'});else damageEnemy(e,dmg,{tag:'SUMMON'});if(a.kind==='hire0')e.status.stagger=.7;}a.mesh.position.set(a.x,0,a.z);if(a.hp<=0&&a.kind==='skeleton'&&!a.reborn&&equipmentItems().some(i=>i.skillId==='S09_01'&&i.effect==='변형')){a.reborn=true;a.hp=a.maxHp*.6;ring(a.x,a.z,2,'#c0d5ab');}if(a.life<=0||a.hp<=0){disposeGroup(a.mesh);allies.splice(i,1);}}
 for(let i=shots.length-1;i>=0;i--){const s=shots[i];s.life-=dt;if(s.homing){let e=closest(s.x,s.z,15);if(e)s.dir.lerp(new THREE.Vector3(e.x-s.x,0,e.z-s.z).normalize(),dt*5).normalize();}if(s.returning&&s.life<1)s.dir.set(hero.position.x-s.x,0,hero.position.z-s.z).normalize();s.x+=s.dir.x*s.speed*dt;s.z+=s.dir.z*s.speed*dt;s.mesh.position.set(s.x,.9,s.z);if(s.enemy){if(Math.hypot(s.x-hero.position.x,s.z-hero.position.z)<.75){hurt(s.d);if(s.web)p.buffs.slow=3;s.life=0;}}else for(const e of enemies){if(e.dead||s.hit.has(e.id))continue;if(Math.hypot(s.x-e.x,s.z-e.z)<(e.def.boss?1.7:.8)){s.hit.add(e.id);damageEnemy(e,s.d,s.s);if(s.freeze)e.status.freeze=2;if(s.overcharge)area(e.x,e.z,3,s.d*.4,s.s);if(s.explode)area(e.x,e.z,3,s.d*.5,s.s);if(s.split){for(let j=-1;j<=1;j+=2)projectile(e.x,e.z,e.x+s.dir.x*10+j*4,e.z+s.dir.z*10+j*4,s.d*.4,s.s,{pierce:true});}if(!s.pierce)s.life=0;break;}}if(s.life<=0){s.mesh.removeFromParent();s.mesh.geometry.dispose();shots.splice(i,1);}}
 for(let i=zones.length-1;i>=0;i--){let z=zones[i];if(z.delay>0){z.delay-=dt;z.mesh.material.opacity=.1+.2*(Math.sin(clock*15)*.5+.5);continue;}z.mesh.material.opacity=.22;z.life-=dt;z.tick-=dt;if(z.tag==='gravity'&&!z.enemy){for(const e of enemies)if(!e.dead&&distance(e,z)<z.r){e.x+=(z.x-e.x)*dt*.7;e.z+=(z.z-e.z)*dt*.7;}}if(z.tick<=0){z.tick=.7;if(z.enemy){if(distance(z,hero.position)<z.r){hurt(z.damage);if(z.tag==='cold'||z.tag==='web')p.buffs.slow=2;}}else if(z.tag==='heal'){if(distance(z,hero.position)<z.r)p.hp=Math.min(p.maxHp,p.hp+12);}else for(const e of enemies)if(!e.dead&&distance(e,z)<z.r)damageEnemy(e,z.damage,{tag:z.tag||'SPACE'});}if(z.life<=0){z.mesh.removeFromParent();z.mesh.geometry.dispose();z.mesh.material.dispose();zones.splice(i,1);}}
 for(const c of corpses){c.life-=dt;if(c.mesh)animateSpriteActor(c.mesh,c.life>17.55?'death':'corpse',18-c.life,c.enemy?.id||0);}for(const c of corpses)if(c.life<=0&&c.mesh)disposeGroup(c.mesh);corpses=corpses.filter(c=>c.life>0);for(const d of drops){d.mesh.rotation.y+=dt;d.mesh.position.y=.4+Math.sin(clock*2)*.08;}if(boss&&!boss.dead)$('bossbar').querySelector('i').style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';else $('bossbar').hidden=true;
 uiTime-=dt;if(uiTime<=0){uiTime=.1;updateHud();}autosave-=dt;if(autosave<=0){autosave=15;save();}}
function updateHud(){let st=stats();p.baseHp=250+(p.level-1)*28;p.maxHp=Math.round(p.baseHp*(1+st.eq.filter(i=>i.effect==='보호').length*.12));p.hp=Math.min(p.hp,p.maxHp);$('charName').textContent=playerClass().name;$('level').textContent=`Lv.${p.level}`;$('gold').textContent=`${p.gold.toLocaleString()} G`;$('hpNumber').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('resNumber').textContent=Math.floor(p.res);$('resourceName').textContent=playerClass().resource;$('hud').querySelector('.hp>div').style.height=p.hp/p.maxHp*100+'%';$('hud').querySelector('.resource>div').style.height=p.res/p.maxRes*100+'%';$('xpFill').style.width=p.xp/(p.level*100)*100+'%';let b=[];if(p.buffs.stealth)b.push(`은신 · 탐지 ${Math.floor(p.suspicion)}%`);if(p.classId==='C02')b.push(`신앙 ${Math.floor(p.faith)} / 죄업 ${Math.floor(p.sin)}`);if(p.classId==='C03')b.push(`영혼 ${p.souls}`);if(allies.length)b.push(`소환 슬롯 ${allies.reduce((n,a)=>n+(a.slotCost||1),0)}/10`);if(p.buffs.berserk)b.push('광폭화');if(p.buffs.clone)b.push('그림자 복제');if(p.buffs.link)b.push(`연계 ×${p.buffs.link}`);if(p.combo>3)b.push(`콤보 ${Math.floor(p.combo)}`);b.push(`회복약 ${p.potions}`);$('buffs').textContent=b.join(' · ');for(const btn of $('hotbar').children){let id=btn.dataset.id,c=p.cd[id]||0;btn.querySelector('.cool').hidden=c<=0;btn.querySelector('.cool').textContent=c>0?(c<1?c.toFixed(1):Math.ceil(c)):'';}
 drawMap();}
function drawMap(){let ctx=$('minimap').getContext('2d');ctx.clearRect(0,0,180,180);ctx.strokeStyle='#7b8d7660';ctx.strokeRect(8,8,164,164);const point=(x,z,c,r=2)=>{ctx.fillStyle=c;ctx.beginPath();ctx.arc(90+x*2.6,90+z*2.6,r,0,Math.PI*2);ctx.fill();};for(const e of enemies)if(!e.dead)point(e.x,e.z,e.def.boss?'#ecc889':'#bb7364',e.def.boss?4:2);for(const d of drops)point(d.x,d.z,'#e1bd73',2);for(const a of allies)point(a.x,a.z,'#8ec4b0');point(hero.position.x,hero.position.z,'#e9ebdc',3);point(0,-9,'#93bec5',3);}
const runes={MELEE:'⚔',BLEED:'⫶',STAGGER:'✦',WEAPON:'⚒',LIGHT:'✧',JUDGMENT:'†',BLOOD:'♦',SHIELD:'◇',SUMMON:'♜',POISON:'♧',SPIRIT:'◈',FIRE:'♨',COLD:'❄',LIGHTNING:'ϟ',SPACE:'◎',PROJECTILE:'➶',SNIPER:'⊕',STEALTH:'◐',SHADOW:'◑',DASH:'»'};
function renderHotbar(){const key=['1','2','3','4','5','6','R'];$('hotbar').innerHTML=p.loadout.map((id,i)=>{let s=DB.skills.find(s=>s.id===id);return `<button class="skillKey ${i===6?'ultimate':''}" data-id="${id}" title="${s.name} · ${s.cost} 자원 · ${s.cooldown}초" style="--skill-color:${tagColor(s.tag)}"><span class="key">${key[i]}</span><span class="rune">${runes[s.tag]||'✦'}</span><span class="name">${s.name}</span><span class="cool" hidden></span></button>`;}).join('');for(const b of $('hotbar').children)b.onclick=()=>cast(DB.skills.find(s=>s.id===b.dataset.id));}
function showPanel(title,html){paused=true;mouse.down=false;moveGoal=null;attackTarget=null;$('panelTitle').textContent=title;$('panelContent').innerHTML=html;if(!$('panel').open)$('panel').showModal();}
function closePanel(){if(started&&p.hp<=0){$('panel').close();paused=false;goTown();return;}$('panel').close();paused=false;keys={};save();}
function skillPanel(specId=p.specialization){let sp=DB.specs.find(s=>s.id===specId);let list=DB.skills.filter(s=>s.specializationId===specId);showPanel('특화와 스킬',`<div class="tabs">${DB.specs.filter(s=>s.characterId===p.classId).map(s=>`<button data-spec="${s.id}" class="${s.id===specId?'active':''}">${s.name}</button>`).join('')}</div><p>${sp.description}</p><div class="statrow"><span>남은 스킬 포인트 <b>${p.points}</b></span><span>선택 특화: ${DB.specs.find(s=>s.id===p.specialization).name} · 해당 스킬 피해 +12%</span></div><button id="setSpec">${sp.name} 특화 적용 · 기본 스킬 배치</button><div class="skillGrid" style="margin-top:15px">${list.map(s=>`<article class="entry"><h4>${runes[s.tag]||'✦'} ${s.name} ${s.ultimate?'· 궁극기':''}</h4><small>${s.castType} · ${s.tag} · Lv.${p.skillLevels[s.id]||1}</small><p>위력 ${Math.round(s.coefficient*100)}% · 자원 ${s.cost}<br>재사용 ${s.cooldown}초 · ${behaviorText(s.mode)}</p><button data-up="${s.id}" ${p.points<=0?'disabled':''}>강화 +1</button><select data-slot="${s.id}" aria-label="${s.name} 단축키 배치"><option value="">단축키 배치</option>${(s.ultimate?[6]:[0,1,2,3,4,5]).map(n=>`<option value="${n}">${n===6?'R':n+1}번 슬롯</option>`).join('')}</select><select data-branch="${s.id}" aria-label="${s.name} 강화 분기"><option value="none">기본 분기</option><option value="power" ${p.branches[s.id]==='power'?'selected':''}>공격 · 피해 +20%</option><option value="utility" ${p.branches[s.id]==='utility'?'selected':''}>유틸 · 자원 -25%, 사용 시 회복</option></select></article>`).join('')}</div>`);
 document.querySelectorAll('[data-spec]').forEach(b=>b.onclick=()=>skillPanel(b.dataset.spec));$('setSpec').onclick=()=>{p.specialization=specId;p.loadout=list.map(s=>s.id);renderHotbar();skillPanel(specId);save();};document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{if(p.points>0){p.skillLevels[b.dataset.up]=(p.skillLevels[b.dataset.up]||1)+1;p.points--;skillPanel(specId);}});document.querySelectorAll('[data-slot]').forEach(b=>b.onchange=()=>{if(b.value==='')return;let id=b.dataset.slot,idx=Number(b.value),old=p.loadout.indexOf(id);if(old>=0)[p.loadout[idx],p.loadout[old]]=[p.loadout[old],p.loadout[idx]];else p.loadout[idx]=id;renderHotbar();toast('스킬 배치를 변경했습니다.');save();});document.querySelectorAll('[data-branch]').forEach(b=>b.onchange=()=>{p.branches[b.dataset.branch]=b.value;save();});}
function behaviorText(m){return ({cleave:'전방 광역 베기',sweep:'넓은 휩쓸기',quake:'지면 광역 충격',skeleton:'해골 전사 소환 · 슬롯 1',archer:'원거리 해골 소환 · 슬롯 1',mage:'해골 술사 소환 · 슬롯 2',knight:'고체력 해골 소환 · 슬롯 3',infect:'감염된 적 처치 시 좀비 부활',detonate:'소환수를 폭발시켜 광역 피해',clone:'스킬을 지연 복제하는 분신',exchange:'적 또는 소환수와 위치 교환',gravity:'적을 끌어당기는 중력장',stealth:'은신 및 탐지 게이지 감소',parry:'공격을 막고 반격',guard:'받는 피해 감소',army:'소환 군단 동시 호출',feed:'회복과 소환수 강화',mark:'받는 피해 증가 표식',charge:'준비 후 강한 광역 타격',heal:'체력 회복과 빛 공격',possess:'일반 적 빙의 및 아군 생성',release:'저장한 영혼을 소모하여 광역 공격',swap:'무기를 교대하고 연계 강화',snipe:'장거리 단일 표적 공격',bloodsea:'피의 장판과 흡혈 회복',laststand:'효과 중 치명상에서 생존',cleanse:'상태 정화와 짧은 무적',wall:'지속 피해 영역',rift:'공간을 찢어 지속 피해',trap:'지속 피해 함정',buff:'속도 증가',dash:'돌진 경로 공격',projectile:'조준 방향 투사체',pool:'지속 피해 지대',storm:'주변 지속 피해',rain:'지정 위치 연속 타격',nova:'주변 광역 공격',hire0:'돌진 고용고아 · 슬롯 1',hire1:'탱커 고용고아 · 슬롯 3',hire2:'원거리 고용고아 · 슬롯 1',hire3:'광폭 고용고아 · 슬롯 1'}[m])||'조준 방향으로 특화 효과 발동';}
const bagFilters={query:'',rarity:'',slot:'',unequipped:false};
function bagPanel(){let st=stats(),weapon=DB.weapons[p.weapon],slots=['무기','보조무기','투구','갑옷','장갑','바지','신발','목걸이','반지1','반지2'];showPanel('장비와 소지품',`<div class="statrow"><span>공격력 ${Math.round(st.damage)}</span><span>치명 ${Math.round(st.crit*100)}%</span><span>시전속도 ${Math.round(st.speed*100)}% · ${Math.ceil(24/(1+st.speed))}F</span><span>다음 단계 ${Math.ceil((24/(Math.ceil(24/(1+st.speed))-1)-1)*100)}%</span><span>${p.gold} G</span></div><p>사용 무기 <strong id="currentWeapon">${weapon.name}</strong> · ${weapon.description}</p><div class="equipment">${slots.map(slot=>{let it=p.inventory.find(i=>i.uid===p.equipment[slot]),type=it?.weaponId?DB.weapons.find(w=>w.id===it.weaponId)?.name:'';return `<div class="entry"><small>${slot}</small><h4>${it?it.name:'미장착'}</h4>${type?`<small>${type}</small>`:''}${it?`<button data-unequip="${slot}">해제</button>`:''}</div>`;}).join('')}</div><div class="statrow"><span>가방 ${p.inventory.length}/160</span><button id="sellCommon">미장착 일반·마법·희귀 판매</button><button id="buyPotion">회복약 +1 · 30 G</button></div><div class="statrow"><label>검색 <input id="bagSearch" type="search" placeholder="아이템 이름·효과 검색"></label><label>등급 <select id="bagRarity"><option value="">전체 등급</option>${['일반','마법','희귀','전설'].map(r=>`<option value="${r}">${r}</option>`).join('')}</select></label><label>부위 <select id="bagSlot"><option value="">전체 부위</option>${['무기','보조무기','투구','갑옷','장갑','바지','신발','목걸이','반지'].map(r=>`<option value="${r}">${r}</option>`).join('')}</select></label><label><input id="bagUnequipped" type="checkbox"> 미장착만</label><span id="bagResultCount" role="status"></span></div><div id="bagItems" class="itemGrid">${p.inventory.map(i=>{let type=i.weaponId?DB.weapons.find(w=>w.id===i.weaponId)?.name:'';return `<article class="entry" data-bag-item="${i.uid}"><small>${i.rarity} · ${i.slot}${type?' · '+type:''} · Lv.${i.level||1}</small><h4>${i.name}</h4><p>${i.description}<br>공격력 +${i.power}%</p><button data-equip="${i.uid}">${Object.values(p.equipment).includes(i.uid)?'장착 중':'장착'}</button><button data-sell="${i.uid}">판매 +${i.rarity==='전설'?40:10} G</button></article>`;}).join('')||'<p class="empty">몬스터를 처치하고 E로 전리품을 획득하세요.</p>'}</div>`);
 $('bagSearch').value=bagFilters.query;$('bagRarity').value=bagFilters.rarity;$('bagSlot').value=bagFilters.slot;$('bagUnequipped').checked=bagFilters.unequipped;
 const applyFilters=()=>{
  const query=bagFilters.query.trim().toLocaleLowerCase(),equipped=new Set(Object.values(p.equipment));
  let count=0;const byId=new Map(p.inventory.map(i=>[i.uid,i]));
  for(const card of $('bagItems').querySelectorAll('[data-bag-item]')){
   const item=byId.get(card.dataset.bagItem);
   const matches=item&&(!bagFilters.rarity||item.rarity===bagFilters.rarity)&&(!bagFilters.slot||item.slot===bagFilters.slot)&&(!bagFilters.unequipped||!equipped.has(item.uid))&&[item.name,item.description,item.tag,item.effect].join(' ').toLocaleLowerCase().includes(query);
   card.hidden=!matches;if(matches)count++;
  }
  $('bagResultCount').textContent=count+' / '+p.inventory.length+'개';
  let empty=$('bagNoResults');if(!empty){empty=document.createElement('p');empty.id='bagNoResults';empty.className='empty';empty.textContent='조건에 맞는 아이템이 없습니다.';$('bagItems').append(empty);}
  empty.hidden=count>0||p.inventory.length===0;
 };
 $('bagSearch').oninput=e=>{bagFilters.query=e.target.value;applyFilters();};$('bagRarity').onchange=e=>{bagFilters.rarity=e.target.value;applyFilters();};$('bagSlot').onchange=e=>{bagFilters.slot=e.target.value;applyFilters();};$('bagUnequipped').onchange=e=>{bagFilters.unequipped=e.target.checked;applyFilters();};applyFilters();
 document.querySelectorAll('[data-unequip]').forEach(b=>b.onclick=()=>{delete p.equipment[b.dataset.unequip];syncEquippedWeapon(DB,p);bagPanel();save();});document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let i=p.inventory.find(i=>i.uid===b.dataset.equip);if(Object.values(p.equipment).includes(i.uid))return;assignWeaponIdentity(DB,i,p.classId);let slot=i.slot==='반지'?(!p.equipment['반지1']?'반지1':!p.equipment['반지2']?'반지2':'반지1'):i.slot;p.equipment[slot]=i.uid;syncEquippedWeapon(DB,p);bagPanel();save();});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>{if(Object.values(p.equipment).includes(b.dataset.sell)){toast('장착 해제 후 판매할 수 있습니다.');return;}let i=p.inventory.find(i=>i.uid===b.dataset.sell);p.gold+=i.rarity==='전설'?40:10;p.inventory=p.inventory.filter(i=>i.uid!==b.dataset.sell);bagPanel();save();});$('sellCommon').onclick=()=>{let ids=new Set(Object.values(p.equipment));p.inventory=p.inventory.filter(i=>{if(i.rarity!=='전설'&&!ids.has(i.uid)){p.gold+=10;return false;}return true;});bagPanel();save();};$('buyPotion').onclick=()=>{if(p.gold>=30&&p.potions<9){p.gold-=30;p.potions++;bagPanel();save();}else toast('금화가 부족하거나 회복약이 가득 찼습니다.');};}
function codexPanel(type='monster',query=''){let tabs=`<div class="tabs"><button id="monstersTab" class="${type==='monster'?'active':''}">몬스터 · 25종</button><button id="itemsTab" class="${type==='item'?'active':''}">전설 · 512종</button></div><input id="codexSearch" type="search" placeholder="이름 또는 태그 검색" aria-label="도감 검색"><div id="codexEntries" class="itemGrid"></div>`;showPanel('잊힌 기록',tabs);function draw(q){let list=(type==='monster'?DB.monsters:DB.items).filter(i=>(i.name+' '+(i.tag||'')+' '+i.description).toLowerCase().includes(q.toLowerCase()));$('codexEntries').innerHTML=list.map(i=>`<article class="entry"><small>${type==='monster'?i.category:i.rarity+' · '+i.slot}</small><h4>${i.name}</h4><p>${i.description}</p><small>${type==='monster'?'기본 체력 '+i.hp:i.tag+' · '+i.effect}</small></article>`).join('')||'<p>검색 결과가 없습니다.</p>';}$('monstersTab').onclick=()=>codexPanel('monster');$('itemsTab').onclick=()=>codexPanel('item');$('codexSearch').oninput=e=>draw(e.target.value);draw(query);}
function settingsPanel(){showPanel('성역 설정',`<div class="setting"><span>이펙트 강도</span><select id="vfxSetting">${[[.5,'50%'],[1,'100%'],[1.5,'150%'],[2,'정신나감 200%']].map(([v,n])=>`<option value="${v}" ${settings.vfx===v?'selected':''}>${n}</option>`).join('')}</select></div><div class="setting"><span>효과음</span><input id="soundSetting" type="checkbox" ${settings.sound?'checked':''}></div><div class="setting"><span>카메라 흔들림</span><input id="shakeSetting" type="checkbox" ${settings.shake?'checked':''}></div><div class="setting"><span>다음 던전 난이도</span><select id="difficultySetting">${[[.7,'이야기'],[1,'일반'],[1.5,'악몽'],[2,'지옥']].map(([v,n])=>`<option value="${v}" ${settings.difficulty===v?'selected':''}>${n}</option>`).join('')}</select></div><p>진행은 이 브라우저에 자동 저장됩니다. 백업 파일로 다른 기기에 옮길 수 있습니다.</p><button id="exportSave">저장 파일 내보내기</button> <label><button id="importSaveBtn">저장 파일 불러오기</button><input id="importSave" type="file" accept="application/json" hidden></label><hr><button id="changeChar">캐릭터 선택으로</button>`);
 $('vfxSetting').onchange=e=>settings.vfx=Number(e.target.value);$('soundSetting').onchange=e=>settings.sound=e.target.checked;$('shakeSetting').onchange=e=>settings.shake=e.target.checked;$('difficultySetting').onchange=e=>settings.difficulty=Number(e.target.value);$('exportSave').onclick=()=>{save();let url=URL.createObjectURL(new Blob([localStorage.getItem(SAVE)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download='goablo-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('importSaveBtn').onclick=()=>$('importSave').click();$('importSave').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(s.version!==1||!DB.characters.some(c=>c.id===s.p?.classId)||!Array.isArray(s.p.inventory)||!s.p.loadout?.every(id=>DB.skills.some(s=>s.id===id)))throw Error();localStorage.setItem(SAVE,JSON.stringify(s));location.reload();}catch{toast('유효한 고아블로 저장 파일이 아닙니다.');}};$('changeChar').onclick=()=>{save();location.reload();};}
function chooseClass(i){selected=i;let c=DB.characters[i];document.querySelectorAll('.classChoice').forEach((b,j)=>b.classList.toggle('active',i===j));$('classDescription').innerHTML=`<h3>${c.name}</h3><p>${DB.specs.filter(s=>s.characterId===c.id).map(s=>s.name).join(' · ')}<br>고유 자원: ${c.resource}</p>`;previewHero&&disposeGroup(previewHero);previewHero=person(c.color,classKinds[i],2.5,{atlas:'players',row:playerSpriteRow(c.id)});previewHero.position.set(-2,0,0);previewHero.rotation.y=-.3;scene.add(previewHero);}
$('classChoices').innerHTML=DB.characters.map((c,i)=>`<button class="classChoice" data-class="${i}"><strong style="color:${c.color}">${c.name}</strong><small>${DB.specs.find(s=>s.characterId===c.id).name} 외 3특화</small></button>`).join('');document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>chooseClass(Number(b.dataset.class)));
$('startBtn').onclick=()=>{if(localStorage.getItem(SAVE)){if(!confirm('새 여정을 시작하면 이 브라우저의 기존 저장을 덮어씁니다. 시작할까요?'))return;}startGame();};$('continueBtn').hidden=!localStorage.getItem(SAVE);$('continueBtn').onclick=()=>startGame(true);$('enterBtn').onclick=()=>{if(town)enterDungeon();else if(cleared){loot(true);if(floor===3){act++;goTown();}else enterDungeon();}};$('returnBtn').onclick=()=>{if(!paused)goTown();};$('skillsBtn').onclick=()=>started&&skillPanel();$('bagBtn').onclick=()=>started&&bagPanel();$('codexBtn').onclick=()=>codexPanel();$('settingsBtn').onclick=()=>started&&settingsPanel();$('closePanel').onclick=closePanel;$('panel').addEventListener('cancel',e=>{e.preventDefault();closePanel();});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;keys[e.key.toLowerCase()]=true;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(!started||e.repeat)return;if(e.key==='Escape'){if($('panel').open)closePanel();else settingsPanel();return;}if($('panel').open)return;let i='123456'.indexOf(e.key);if(i>=0)cast(DB.skills.find(s=>s.id===p.loadout[i]));if(e.key.toLowerCase()==='r')cast(DB.skills.find(s=>s.id===p.loadout[6]));if(e.key===' ')dodge();if(e.key.toLowerCase()==='q')potion();if(e.key.toLowerCase()==='e')loot();if(e.key.toLowerCase()==='k')skillPanel();if(e.key.toLowerCase()==='i')bagPanel();if(e.key.toLowerCase()==='t')goTown();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{keys={};mouse.down=false;if(started){save();if(!paused)settingsPanel();}});
function updatePointer(e){
 const rect=$('world').getBoundingClientRect();
 mouse.x=(e.clientX-rect.left)/rect.width*2-1;mouse.y=-(e.clientY-rect.top)/rect.height*2+1;
 ray.setFromCamera(mouse,camera);ray.ray.intersectPlane(plane,aim);
}
function pointedEnemy(){
 const living=enemies.filter(e=>!e.dead),hits=ray.intersectObjects(living.map(e=>e.mesh),true);
 if(hits.length){let obj=hits[0].object;while(obj){const enemy=living.find(e=>e.mesh===obj);if(enemy)return enemy;obj=obj.parent;}}
 let best=null,bestDistance=Infinity;
 for(const enemy of living){const point=new THREE.Vector3(enemy.x,enemy.mesh.userData.labelHeight*.5,enemy.z).project(camera);if(point.z< -1||point.z>1)continue;const screenDistance=Math.hypot(point.x-mouse.x,point.y-mouse.y),threshold=enemy.def.boss?.16:.105;if(screenDistance<threshold&&screenDistance<bestDistance){best=enemy;bestDistance=screenDistance;}}
 return best;
}
function setClickGoal(){
 const enemy=pointedEnemy();
 if(enemy){const fresh=attackTarget!==enemy||clock-(enemy.selectedAt||0)>.25;attackTarget=enemy;moveGoal=null;enemy.labelUntil=clock+4;if(fresh){enemy.selectedAt=clock;ring(enemy.x,enemy.z,enemy.def.boss?2.2:1.25,'#ffb35c',.28);sound(260,.045,'square',.018);}}
 else{attackTarget=null;moveGoal={x:clamp(aim.x,-28,28),z:clamp(aim.z,-28,28)};}
}
$('world').addEventListener('pointermove',e=>{updatePointer(e);hoverTarget=started&&!paused&&!town?pointedEnemy():null;$('world').style.cursor=hoverTarget?'crosshair':'';if(hoverTarget)hoverTarget.labelUntil=clock+.12;if(started&&!paused&&mouse.down&&!keys.shift)setClickGoal();});
$('world').addEventListener('pointerleave',()=>{hoverTarget=null;$('world').style.cursor='';});
$('world').addEventListener('pointerdown',e=>{
 updatePointer(e);if(!started||paused)return;
 if(e.button===0){mouse.down=true;keys.shift=e.shiftKey;if(e.shiftKey){moveGoal=null;attackTarget=null;basic();}else setClickGoal();}
 if(e.button===2)cast(DB.skills.find(s=>s.id===p.loadout[0]));
});window.addEventListener('pointerup',()=>mouse.down=false);$('world').addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('beforeunload',save);
function updateEnemyLabels(){
 for(const e of enemies){
  const visible=started&&!town&&!e.dead&&(e===hoverTarget||e===attackTarget||e.labelUntil>clock);
  if(!visible){if(e.healthLabel)e.healthLabel.hidden=true;continue;}
  if(!e.healthLabel){
   const label=document.createElement('div');label.className='enemyHealthLabel';
   Object.assign(label.style,{position:'fixed',pointerEvents:'none',transform:'translate(-50%,-100%)',width:e.def.boss?'170px':'120px',textAlign:'center',color:'#f6ead4',fontSize:'12px',textShadow:'0 1px 3px #000',zIndex:'8'});
   const name=document.createElement('div');name.textContent=e.def.name;
   const track=document.createElement('div');Object.assign(track.style,{height:'6px',background:'#211918',border:'1px solid #b59a69',marginTop:'3px'});
   const fill=document.createElement('div');Object.assign(fill.style,{height:'100%',background:e.def.boss?'#d6a653':'#c7554c'});
   track.append(fill);label.append(name,track);document.body.append(label);e.healthLabel=label;e.healthFill=fill;
  }
  const v=new THREE.Vector3(e.x,e.mesh.userData.labelHeight||2.2*e.mesh.scale.y,e.z).project(camera);
  e.healthLabel.hidden=v.z< -1||v.z>1||Math.abs(v.x)>1.15||Math.abs(v.y)>1.15;
  e.healthLabel.style.left=(v.x*.5+.5)*innerWidth+'px';e.healthLabel.style.top=(-v.y*.5+.5)*innerHeight+'px';
  e.healthFill.style.width=clamp(e.hp/e.maxHp*100,0,100)+'%';
 }
}
function updateTargetMarkers(){
 const place=(marker,enemy,base)=>{marker.visible=!!enemy&&!enemy.dead;if(!marker.visible)return;const scale=(enemy.def.boss?1.75:1)*(base+Math.sin(clock*7)*.06);marker.position.set(enemy.x,.11,enemy.z);marker.scale.setScalar(scale);};
 place(hoverMarker,hoverTarget,.95);place(selectedMarker,attackTarget,1.08);
}
document.querySelector('.controls').textContent='좌클릭 이동·적 공격 · Shift+좌클릭 제자리 공격 · WASD 이동 · 우클릭 스킬 · SPACE 회피 · Q 회복 · E 줍기';
if(new URLSearchParams(location.search).get('test')==='1'){
 const actorState=(mesh,enemy)=>({name:enemy?.def.name,boss:!!enemy?.def.boss,behavior:enemy?.def.behavior,enraged:!!enemy?.enraged,atlas:mesh?.userData.spriteAtlas,row:mesh?.userData.spriteRow,state:mesh?.userData.spriteState,frame:mesh?.userData.spriteFrame});
 globalThis.__goabloTest=Object.freeze({
  snapshot:()=>({started,paused,town,act,floor,clock,cleared,spriteStatus:document.documentElement.dataset.spriteStatus,bossBarHidden:$('bossbar').hidden,enemies:enemies.filter(e=>!e.dead).map(e=>actorState(e.mesh,e)),zones:zones.map(z=>({tag:z.tag,r:z.r,delay:z.delay,enemy:z.enemy})),corpses:corpses.map(c=>({...actorState(c.mesh,c.enemy),life:c.life}))}),
  firstEnemyScreenPoint:()=>{for(const enemy of enemies){if(enemy.dead)continue;const point=new THREE.Vector3(enemy.x,enemy.mesh.userData.labelHeight*.5,enemy.z).project(camera),x=(point.x*.5+.5)*innerWidth,y=(-point.y*.5+.5)*innerHeight;if(point.z>-1&&point.z<1&&x>60&&x<innerWidth-60&&y>60&&y<innerHeight-60)return {x,y,name:enemy.def.name};}return null;},
  targeting:()=>({hover:hoverTarget?.def.name||null,selected:attackTarget?.def.name||null,hoverMarker:hoverMarker.visible,selectedMarker:selectedMarker.visible}),
  probeHitContinuity:()=>{p.buffs.invulnerable=0;p.buffs.evade=0;p.cd.basic=0;basic();const before=hero.userData.attack;hurt(p.maxHp*.03,{def:{boss:false}});const afterNormal=hero.userData.attack;p.cd.basic=0;basic();hurt(p.maxHp*.03,{def:{boss:true}});return {before,afterNormal,afterHeavy:hero.userData.attack,heavyHitUntil:hero.userData.hitUntil>clock};},
  triggerBossEnrage:()=>{if(!boss||boss.dead)return false;boss.hp=boss.maxHp*.44;boss.cd=0;update(.01);return true;},
  defeatAll:()=>{for(const e of [...enemies])if(!e.dead)killEnemy(e,null);},
  protectPlayer:()=>{p.buffs.invulnerable=30;},
  step:seconds=>{for(let elapsed=0;elapsed<seconds;elapsed+=1/60)update(1/60);}
 });
}
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();buildWorld(true);chooseClass(0);
let last=performance.now();function frame(now){requestAnimationFrame(frame);let dt=Math.min((now-last)/1000,.05);last=now;if(hitstop>0){hitstop-=dt;dt*=.12;}update(dt);let center=started?hero.position:new THREE.Vector3(-2,0,0);const desired=new THREE.Vector3(center.x+18,24,center.z+21);camera.position.lerp(desired,1-Math.exp(-dt*5));const look=center.clone();look.y=.3;if(settings.shake&&shake>0){look.x+=rnd(-shake,shake);look.z+=rnd(-shake,shake);shake=Math.max(0,shake-dt);}camera.lookAt(look);sun.position.set(center.x-12,24,center.z+10);sun.target.position.copy(center);updateEnemyLabels();updateTargetMarkers();renderer.render(scene,camera);}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_goablo_progress',description:'현재 고아블로 캐릭터와 여정 진행 상태를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({started,town,act,floor,character:p?.classId,level:p?.level,hp:p?.hp,inventory:p?.inventory.length})});}catch{}}
